# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import oscal_pb2 as oscal__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in oscal_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OscalBridgeServiceStub(object):
    """OscalBridgeService serializes platform aggregates into OSCAL JSON
    v1.1.x and validates them via compliance-trestle round-trip.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SerializeSSP = channel.unary_unary(
                '/oscal.v1.OscalBridgeService/SerializeSSP',
                request_serializer=oscal__pb2.SerializeSSPRequest.SerializeToString,
                response_deserializer=oscal__pb2.SerializeSSPResponse.FromString,
                _registered_method=True)
        self.SerializeAssessment = channel.unary_unary(
                '/oscal.v1.OscalBridgeService/SerializeAssessment',
                request_serializer=oscal__pb2.SerializeAssessmentRequest.SerializeToString,
                response_deserializer=oscal__pb2.SerializeAssessmentResponse.FromString,
                _registered_method=True)
        self.SerializePOAM = channel.unary_unary(
                '/oscal.v1.OscalBridgeService/SerializePOAM',
                request_serializer=oscal__pb2.SerializePOAMRequest.SerializeToString,
                response_deserializer=oscal__pb2.SerializePOAMResponse.FromString,
                _registered_method=True)
        self.RoundTripValidate = channel.unary_unary(
                '/oscal.v1.OscalBridgeService/RoundTripValidate',
                request_serializer=oscal__pb2.RoundTripValidateRequest.SerializeToString,
                response_deserializer=oscal__pb2.RoundTripValidateResponse.FromString,
                _registered_method=True)
        self.ImportCatalog = channel.unary_unary(
                '/oscal.v1.OscalBridgeService/ImportCatalog',
                request_serializer=oscal__pb2.ImportCatalogRequest.SerializeToString,
                response_deserializer=oscal__pb2.ImportCatalogResponse.FromString,
                _registered_method=True)
        self.ImportProfile = channel.unary_unary(
                '/oscal.v1.OscalBridgeService/ImportProfile',
                request_serializer=oscal__pb2.ImportProfileRequest.SerializeToString,
                response_deserializer=oscal__pb2.ImportProfileResponse.FromString,
                _registered_method=True)
        self.ImportComponentDefinition = channel.unary_unary(
                '/oscal.v1.OscalBridgeService/ImportComponentDefinition',
                request_serializer=oscal__pb2.ImportComponentDefinitionRequest.SerializeToString,
                response_deserializer=oscal__pb2.ImportComponentDefinitionResponse.FromString,
                _registered_method=True)


class OscalBridgeServiceServicer(object):
    """OscalBridgeService serializes platform aggregates into OSCAL JSON
    v1.1.x and validates them via compliance-trestle round-trip.
    """

    def SerializeSSP(self, request, context):
        """SerializeSSP maps an SspInput to an OSCAL system-security-plan JSON
        document. The response carries the canonical JSON bytes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SerializeAssessment(self, request, context):
        """SerializeAssessment maps an AssessmentInput to an OSCAL
        assessment-plan JSON document AND an assessment-results JSON
        document (returned as two members).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SerializePOAM(self, request, context):
        """SerializePOAM maps a PoamInput to an OSCAL
        plan-of-action-and-milestones JSON document.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RoundTripValidate(self, request, context):
        """RoundTripValidate parses an OSCAL JSON document back through
        compliance-trestle and re-serializes it, asserting structural
        validity. AC-6 / AC-7. The export pipeline calls this on every
        bundle member before the bundle is finalized.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportCatalog(self, request, context):
        """ImportCatalog deserializes an inbound OSCAL `catalog` JSON document
        via compliance-trestle, validates it against OSCAL v1.1.x, and
        returns a normalized catalog projection (controls + group structure)
        OR a structured validation error. This is the INGEST direction of
        invariant #8 (slice 492). The bridge NEVER dereferences any `href`
        / external resource the document references (back-matter resources
        are opaque metadata). A document-size cap + parse timeout bound the
        expansion-attack surface (threat-model D/I).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportProfile(self, request, context):
        """ImportProfile resolves an inbound OSCAL `profile` JSON document against
        one or more SUPPLIED catalog documents and returns the resolved control
        projection (slice 511). The bridge applies the profile's import / merge /
        modify directives via compliance-trestle's profile-resolver inside an
        ISOLATED, ephemeral trestle workspace whose only catalogs are the ones
        the caller supplied. It NEVER dereferences an external `import.href`:
        every href is rewritten to point at a supplied catalog, and an href that
        names no supplied catalog is a structured error, not a fetch (P0-511-1 /
        threat-model I — the load-bearing difference from ImportCatalog). The
        resolved output is re-validated against OSCAL v1.1.x before it is
        returned. Caps (document size, resolved-control count, import-chain
        depth) bound the expansion-attack surface (threat-model D / AC-3).

        Slice 578 extends ImportProfile to CHAINED profile-over-profile
        resolution: a profile whose `import.href` names another SUPPLIED profile
        (not only a catalog) is resolved recursively until the chain bottoms out
        at a supplied catalog. The chain is bounded by a maximum depth and is
        rejected on a cycle (a profile that imports itself directly or
        transitively) — never an infinite loop / fetch. Every link's href is
        still rewritten to a sandboxed `trestle://` path pointing at a supplied
        document; an href that names no supplied document is a structured error,
        not a fetch (P0-578-1, carrying forward P0-511-1).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportComponentDefinition(self, request, context):
        """ImportComponentDefinition deserializes an inbound OSCAL
        `component-definition` JSON document via compliance-trestle, validates it
        against OSCAL v1.1.x, and returns a normalized projection of the defined
        components + their implemented-requirements — the VENDOR'S
        control-implementation CLAIMS (slice 512). A component-definition is the
        vendor-side artifact: a product vendor ships it to assert "this product
        implements control X this way". The Go side persists each
        implemented-requirement as a vendor-attributed CLAIM (NOT
        platform-verified evidence; never auto-satisfies a control — the
        load-bearing P0-512-1). Like ImportCatalog the bridge NEVER dereferences
        any `href` / external resource the document references (P0-512-2 /
        threat-model I): links / back-matter resources are opaque metadata. A
        document-size cap + component-count + requirement-count cap bound the
        expansion-attack surface (threat-model D / AC-3).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OscalBridgeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SerializeSSP': grpc.unary_unary_rpc_method_handler(
                    servicer.SerializeSSP,
                    request_deserializer=oscal__pb2.SerializeSSPRequest.FromString,
                    response_serializer=oscal__pb2.SerializeSSPResponse.SerializeToString,
            ),
            'SerializeAssessment': grpc.unary_unary_rpc_method_handler(
                    servicer.SerializeAssessment,
                    request_deserializer=oscal__pb2.SerializeAssessmentRequest.FromString,
                    response_serializer=oscal__pb2.SerializeAssessmentResponse.SerializeToString,
            ),
            'SerializePOAM': grpc.unary_unary_rpc_method_handler(
                    servicer.SerializePOAM,
                    request_deserializer=oscal__pb2.SerializePOAMRequest.FromString,
                    response_serializer=oscal__pb2.SerializePOAMResponse.SerializeToString,
            ),
            'RoundTripValidate': grpc.unary_unary_rpc_method_handler(
                    servicer.RoundTripValidate,
                    request_deserializer=oscal__pb2.RoundTripValidateRequest.FromString,
                    response_serializer=oscal__pb2.RoundTripValidateResponse.SerializeToString,
            ),
            'ImportCatalog': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportCatalog,
                    request_deserializer=oscal__pb2.ImportCatalogRequest.FromString,
                    response_serializer=oscal__pb2.ImportCatalogResponse.SerializeToString,
            ),
            'ImportProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportProfile,
                    request_deserializer=oscal__pb2.ImportProfileRequest.FromString,
                    response_serializer=oscal__pb2.ImportProfileResponse.SerializeToString,
            ),
            'ImportComponentDefinition': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportComponentDefinition,
                    request_deserializer=oscal__pb2.ImportComponentDefinitionRequest.FromString,
                    response_serializer=oscal__pb2.ImportComponentDefinitionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'oscal.v1.OscalBridgeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('oscal.v1.OscalBridgeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OscalBridgeService(object):
    """OscalBridgeService serializes platform aggregates into OSCAL JSON
    v1.1.x and validates them via compliance-trestle round-trip.
    """

    @staticmethod
    def SerializeSSP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/oscal.v1.OscalBridgeService/SerializeSSP',
            oscal__pb2.SerializeSSPRequest.SerializeToString,
            oscal__pb2.SerializeSSPResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SerializeAssessment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/oscal.v1.OscalBridgeService/SerializeAssessment',
            oscal__pb2.SerializeAssessmentRequest.SerializeToString,
            oscal__pb2.SerializeAssessmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SerializePOAM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/oscal.v1.OscalBridgeService/SerializePOAM',
            oscal__pb2.SerializePOAMRequest.SerializeToString,
            oscal__pb2.SerializePOAMResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RoundTripValidate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/oscal.v1.OscalBridgeService/RoundTripValidate',
            oscal__pb2.RoundTripValidateRequest.SerializeToString,
            oscal__pb2.RoundTripValidateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ImportCatalog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/oscal.v1.OscalBridgeService/ImportCatalog',
            oscal__pb2.ImportCatalogRequest.SerializeToString,
            oscal__pb2.ImportCatalogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ImportProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/oscal.v1.OscalBridgeService/ImportProfile',
            oscal__pb2.ImportProfileRequest.SerializeToString,
            oscal__pb2.ImportProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ImportComponentDefinition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/oscal.v1.OscalBridgeService/ImportComponentDefinition',
            oscal__pb2.ImportComponentDefinitionRequest.SerializeToString,
            oscal__pb2.ImportComponentDefinitionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
