package controlimport

import (
	"bytes"
	"errors"
	"strings"
	"testing"

	"github.com/xuri/excelize/v2"
)

func makeControlXLSX(t *testing.T, rows [][]string) []byte {
	t.Helper()
	f := excelize.NewFile()
	defer f.Close()
	sheet := f.GetSheetName(0)
	for r, row := range rows {
		for c, val := range row {
			cell, err := excelize.CoordinatesToCellName(c+1, r+1)
			if err != nil {
				t.Fatalf("coords: %v", err)
			}
			if err := f.SetCellStr(sheet, cell, val); err != nil {
				t.Fatalf("set %s: %v", cell, err)
			}
		}
	}
	var buf bytes.Buffer
	if err := f.Write(&buf); err != nil {
		t.Fatalf("write xlsx: %v", err)
	}
	return buf.Bytes()
}

func TestParseCSVControlSet(t *testing.T) {
	raw := []byte("Control ID,Title,Description,Owner\nAC-1,MFA required,All workforce users use MFA,Security\n")
	got, err := ParseCSV(raw)
	if err != nil {
		t.Fatalf("ParseCSV: %v", err)
	}
	if len(got.Controls) != 1 {
		t.Fatalf("controls = %d, want 1", len(got.Controls))
	}
	c := got.Controls[0]
	if c.ExternalID != "AC-1" || c.Title != "MFA required" || c.Description != "All workforce users use MFA" {
		t.Fatalf("parsed control mismatch: %+v", c)
	}
	if c.RowNumber != 2 || c.SourceFormat != "csv" {
		t.Fatalf("row/source mismatch: %+v", c)
	}
	if len(got.UnmappedColumns) != 1 || got.UnmappedColumns[0] != "Owner" {
		t.Fatalf("unmapped columns = %v", got.UnmappedColumns)
	}
}

func TestParseXLSXControlSetRoundTrip(t *testing.T) {
	raw := makeControlXLSX(t, [][]string{
		{"Generated by GRC", "", ""},
		{"ID", "Name", "Control Text"},
		{"IAM-02", "Access reviews", "Privileged access is reviewed quarterly."},
		{"", "", ""},
		{"BAD", "", "missing title"},
	})
	got, err := ParseXLSX(raw)
	if err != nil {
		t.Fatalf("ParseXLSX: %v", err)
	}
	if len(got.Controls) != 1 {
		t.Fatalf("controls = %d, want 1", len(got.Controls))
	}
	c := got.Controls[0]
	if c.ExternalID != "IAM-02" || c.Title != "Access reviews" {
		t.Fatalf("parsed control mismatch: %+v", c)
	}
	if !strings.Contains(c.Description, "quarterly") {
		t.Fatalf("description did not round-trip: %+v", c)
	}
}

func TestParseRequiresMinimumColumns(t *testing.T) {
	_, err := ParseCSV([]byte("ID,Title\nAC-1,MFA\n"))
	if !errors.Is(err, ErrNoHeaderRow) {
		t.Fatalf("want ErrNoHeaderRow, got %v", err)
	}
}

func TestReadAllBounded(t *testing.T) {
	raw := strings.NewReader("abc")
	got, err := ReadAllBounded(raw)
	if err != nil {
		t.Fatalf("ReadAllBounded: %v", err)
	}
	if string(got) != "abc" {
		t.Fatalf("got %q", got)
	}
	tooLarge := strings.NewReader(strings.Repeat("x", MaxUploadBytes+1))
	_, err = ReadAllBounded(tooLarge)
	if !errors.Is(err, ErrUploadTooLarge) {
		t.Fatalf("want ErrUploadTooLarge, got %v", err)
	}
}
