-- Slice 030 — OSCAL SSP + POA&M export aggregation queries.
--
-- These are READ-ONLY. The export pipeline (internal/oscal) aggregates a
-- frozen AuditPeriod's data across the platform and hands it to the
-- Python oscal-bridge for serialization. Every query is tenant-scoped on
-- $1; RLS is the defense-in-depth layer, the WHERE clause is the primary
-- correctness guarantee (mirrors the slice-028 period package pattern).
--
-- The "frozen horizon" enforcement (invariant 10) lives in the Go
-- aggregator: it refuses to run unless the period's status is 'frozen',
-- then passes the period's frozen_at as the upper bound to the
-- horizon-bounded queries below.

-- name: ListPopulationsForPeriod :many
-- Sample populations attached to one audit period. The slice-026
-- populations table carries audit_period_id (slice 028 added the FK).
SELECT id, tenant_id, control_id, time_window_start, time_window_end,
       frozen_at, row_count, created_by, created_at, audit_period_id
FROM populations
WHERE tenant_id = $1
  AND audit_period_id = $2
ORDER BY created_at ASC, id ASC;

-- name: ListWalkthroughsForPeriod :many
-- Walkthroughs pinned to one audit period (slice 027). The export emits
-- each as an OSCAL assessment-results observation.
SELECT id, tenant_id, audit_period_id, control_id, narrative, transcript,
       canonical_hash, status, created_by, created_at, updated_at
FROM walkthroughs
WHERE tenant_id = $1
  AND audit_period_id = $2
ORDER BY created_at ASC, id ASC;

-- name: ListAuditNotesForPeriod :many
-- Every audit note for one period across all scope types (slice 029).
-- The export emits each as an observation annotation. Visibility is NOT
-- filtered here: the audit-handoff bundle is generated by an authorized
-- operator and includes the full audit-note record (the visibility
-- model is an in-product UI concern, not an export-time redaction).
SELECT id, tenant_id, audit_period_id, author_user_id, scope_type,
       scope_id, body, visibility, created_at
FROM audit_notes
WHERE tenant_id = $1
  AND audit_period_id = $2
ORDER BY created_at ASC, id ASC;

-- name: ListFailingEvaluationsAsOf :many
-- POA&M source (slice-030 decision D3): the latest evaluation per
-- (control, scope_cell) whose result is 'fail', bounded by the frozen
-- horizon. DISTINCT ON collapses the append-only control_evaluations
-- history to the current row per cell as of $3 (the period's frozen_at),
-- then the outer filter keeps only the failing ones.
--
-- A failing control evaluation IS a finding for v1 — there is no separate
-- findings table. See docs/audit-log/030-oscal-ssp-poam-export-decisions.md.
SELECT * FROM (
    SELECT DISTINCT ON (control_id, scope_cell_id)
        id, tenant_id, control_id, scope_cell_id, eval_run_id,
        evaluated_at, result, freshness_status, last_observed_at
    FROM control_evaluations
    WHERE tenant_id = $1
      AND evaluated_at <= $2
    ORDER BY control_id, scope_cell_id, evaluated_at DESC, created_at DESC
) latest
WHERE latest.result = 'fail'
ORDER BY latest.control_id ASC, latest.scope_cell_id ASC;
