-- Slice 030 — OSCAL SSP + POA&M export aggregation queries.
--
-- These are READ-ONLY. The export pipeline (internal/oscal) aggregates a
-- frozen AuditPeriod's data across the platform and hands it to the
-- Python oscal-bridge for serialization. Every query is tenant-scoped on
-- $1; RLS is the defense-in-depth layer, the WHERE clause is the primary
-- correctness guarantee (mirrors the slice-028 period package pattern).
--
-- The "frozen horizon" enforcement (invariant 10) lives in the Go
-- aggregator: it refuses to run unless the period's status is 'frozen',
-- then passes the period's frozen_at as the upper bound to the
-- horizon-bounded queries below.

-- name: ListPopulationsForPeriod :many
-- Sample populations attached to one audit period. The slice-026
-- populations table carries audit_period_id (slice 028 added the FK).
SELECT id, tenant_id, control_id, time_window_start, time_window_end,
       frozen_at, row_count, created_by, created_at, audit_period_id
FROM populations
WHERE tenant_id = $1
  AND audit_period_id = $2
ORDER BY created_at ASC, id ASC;

-- name: ListWalkthroughsForPeriod :many
-- Walkthroughs pinned to one audit period (slice 027). The export emits
-- each as an OSCAL assessment-results observation.
SELECT id, tenant_id, audit_period_id, control_id, narrative, transcript,
       canonical_hash, status, created_by, created_at, updated_at
FROM walkthroughs
WHERE tenant_id = $1
  AND audit_period_id = $2
ORDER BY created_at ASC, id ASC;

-- name: ListAuditNotesForPeriod :many
-- Every audit note for one period across all scope types (slice 029).
-- The export emits each as an observation annotation. Visibility is NOT
-- filtered here: the audit-handoff bundle is generated by an authorized
-- operator and includes the full audit-note record (the visibility
-- model is an in-product UI concern, not an export-time redaction).
SELECT id, tenant_id, audit_period_id, author_user_id, scope_type,
       scope_id, body, visibility, created_at
FROM audit_notes
WHERE tenant_id = $1
  AND audit_period_id = $2
ORDER BY created_at ASC, id ASC;

-- name: ListFailingEvaluationsAsOf :many
-- POA&M source (slice-030 decision D3): the latest evaluation per
-- (control, scope_cell) whose result is 'fail', bounded by the frozen
-- horizon. DISTINCT ON collapses the append-only control_evaluations
-- history to the current row per cell as of $3 (the period's frozen_at),
-- then the outer filter keeps only the failing ones.
--
-- A failing control evaluation IS a finding for v1 — there is no separate
-- findings table. See docs/audit-log/030-oscal-ssp-poam-export-decisions.md.
SELECT * FROM (
    SELECT DISTINCT ON (control_id, scope_cell_id)
        id, tenant_id, control_id, scope_cell_id, eval_run_id,
        evaluated_at, result, freshness_status, last_observed_at
    FROM control_evaluations
    WHERE tenant_id = $1
      AND evaluated_at <= $2
    ORDER BY control_id, scope_cell_id, evaluated_at DESC, created_at DESC
) latest
WHERE latest.result = 'fail'
ORDER BY latest.control_id ASC, latest.scope_cell_id ASC;

-- name: ListSampledEvidenceForPeriod :many
-- Slice 494 (AC-1/AC-2): the DRAWN sample evidence ids for every population
-- pinned to one audit period. Joins populations -> samples -> sample_evidence.
--
-- Invariant #10 by construction (AC-2/AC-7): the rows in sample_evidence were
-- materialized at draw-time over the FROZEN population (slice 026's
-- ListPopulationEvidenceIDs filters `observed_at <= frozen_at`), so a record
-- observed after the period's frozen_at was never in the draw and cannot
-- appear here. This query carries the already-frozen-correct draw forward; it
-- never re-samples live data.
--
-- When a population has multiple samples (re-draws), only the MOST-RECENT
-- sample's draw is carried (the operative sample). The DISTINCT ON collapses
-- to one sample per population by created_at DESC; the full re-draw history
-- stays in sample_audit_log (slice 026), not in the AR.
--
-- Ordered by population then ordinal (the deterministic Fisher-Yates shuffle
-- position) so the AR's sampled_evidence_ids preserve the auditor's sample
-- order (AC-9 reproducibility).
SELECT
    latest.population_id,
    se.evidence_record_id,
    se.ordinal
FROM (
    SELECT DISTINCT ON (s.population_id)
        s.id           AS sample_id,
        s.population_id AS population_id
    FROM samples s
    JOIN populations p
        ON p.tenant_id = s.tenant_id AND p.id = s.population_id
    WHERE s.tenant_id = $1
      AND p.audit_period_id = $2
    ORDER BY s.population_id, s.created_at DESC, s.id DESC
) latest
JOIN sample_evidence se
    ON se.tenant_id = $1 AND se.sample_id = latest.sample_id
ORDER BY latest.population_id ASC, se.ordinal ASC;

-- name: ListWalkthroughAttachmentsForPeriod :many
-- Slice 494 (AC-4/AC-5): attachment references for every walkthrough pinned
-- to one audit period. Carries metadata only (id, filename, content hash,
-- content type, annotation jsonb, storage_key) — the attachment BYTES live in
-- the slice-036 object store and are NEVER read here (P0-494-2). The export
-- references them by hash + storage_key.
--
-- Ordered by (walkthrough, uploaded_at, id) so the per-walkthrough attachment
-- order is stable and the exporter's cap (slice 494 D3) selects a
-- deterministic prefix.
SELECT
    wa.walkthrough_id,
    wa.id,
    wa.storage_key,
    wa.content_type,
    wa.sha256_hash,
    wa.annotations
FROM walkthrough_attachments wa
JOIN walkthroughs w
    ON w.tenant_id = wa.tenant_id AND w.id = wa.walkthrough_id
WHERE wa.tenant_id = $1
  AND w.audit_period_id = $2
ORDER BY wa.walkthrough_id ASC, wa.uploaded_at ASC, wa.id ASC;
