import Link from "next/link";

import { signOut } from "@/app/login/actions";
import { Button } from "@/components/ui/button";

// Slice 075 — the top-nav header. Replaces the slice-005 text placeholder
// ("security-atlas" span) with the canonical mark wrapped in a Link to
// /dashboard.
//
// The logo is rendered via a <picture> element with theme-aware sources
// (light + dark variants under web/public/), mirroring slice 057's
// README screenshot pattern. Both <source> media-queries point at
// distinct SVG variants generated by `just regen-logo` from the
// canonical candidate-04 SVG.
//
// AC-5 of slice 075: 24-32px logo height. We use h-7 (28px) — sits
// inside the h-14 (56px) top-bar with breathing room above + below.
// The Link wrapper makes the logo a click-target back to /dashboard
// (the same anchor an authenticated user expects when clicking the
// brand mark of any SaaS web app).
//
// The "security-atlas" wordmark stays as text next to the mark so the
// header still works for screen readers and for users on text-mode
// browsers (the mark's <img alt> is decorative-of-the-wordmark; the
// wordmark itself carries the brand name).
export function TopBar() {
  return (
    <header className="flex h-14 shrink-0 items-center justify-between border-b bg-background px-6">
      <div className="flex items-center gap-3">
        <Link
          href="/dashboard"
          className="flex items-center gap-2 rounded-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
          aria-label="security-atlas — go to dashboard"
        >
          <picture>
            <source
              media="(prefers-color-scheme: dark)"
              srcSet="/logo-dark.svg"
            />
            <source
              media="(prefers-color-scheme: light)"
              srcSet="/logo-light.svg"
            />
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src="/logo-light.svg"
              alt=""
              width={28}
              height={28}
              className="h-7 w-7"
            />
          </picture>
          <span className="text-base font-semibold">security-atlas</span>
        </Link>
        <span className="text-xs text-muted-foreground">v0 · self-host</span>
      </div>
      <form action={signOut}>
        <Button type="submit" variant="ghost" size="sm">
          Sign out
        </Button>
      </form>
    </header>
  );
}
