"use client";

import { useState } from "react";

import { CloudRoutingBanner } from "@/components/llm/cloud-routing-banner";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import {
  parseMappingSuggest,
  type MappingSuggestViewModel,
} from "@/lib/questionnaire/mapping-suggest";

interface MappingSuggestPanelProps {
  questionnaireID: string;
  questionID: string;
  onApproved: (scfAnchorID: string) => void;
}

export function MappingSuggestPanel({
  questionnaireID,
  questionID,
  onApproved,
}: MappingSuggestPanelProps) {
  const [vm, setVm] = useState<MappingSuggestViewModel | null>(null);
  const [loading, setLoading] = useState(false);
  const [acting, setActing] = useState(false);
  const [actionError, setActionError] = useState<string | null>(null);

  async function suggest(): Promise<void> {
    setLoading(true);
    setActionError(null);
    try {
      const res = await fetch(
        `/api/questionnaires/${questionnaireID}/questions/${questionID}/scf-mapping/ai-suggest`,
        { method: "POST" },
      );
      let raw: unknown = null;
      try {
        raw = await res.json();
      } catch {
        raw = null;
      }
      setVm(parseMappingSuggest(res.ok, res.status, raw));
    } finally {
      setLoading(false);
    }
  }

  async function act(kind: "approve" | "reject"): Promise<void> {
    if (!vm || !vm.proposalId) return;
    setActing(true);
    setActionError(null);
    try {
      const res = await fetch(
        `/api/questionnaires/${questionnaireID}/questions/${questionID}/scf-mapping/${vm.proposalId}/${kind}`,
        { method: "POST" },
      );
      if (!res.ok) {
        let msg = `${res.status} ${res.statusText}`;
        try {
          const j = (await res.json()) as { error?: string };
          if (j.error) msg = j.error;
        } catch {
          // body not JSON
        }
        setActionError(msg);
        return;
      }
      if (kind === "approve") {
        onApproved(vm.scfAnchorId);
      } else {
        setVm(null);
      }
    } finally {
      setActing(false);
    }
  }

  return (
    <div
      data-testid="mapping-suggest-panel"
      className="rounded-md border border-border bg-muted/20 p-3 space-y-3"
    >
      <div className="flex items-center justify-between gap-3">
        <div>
          <div className="text-[11px] uppercase tracking-wider font-medium text-muted-foreground">
            SCF mapping
          </div>
          <div className="text-xs text-amber-700 dark:text-amber-400">
            needs mapping
          </div>
        </div>
        <button
          type="button"
          data-testid="mapping-suggest-button"
          disabled={loading}
          onClick={() => {
            void suggest();
          }}
          className="text-xs px-3 py-1 rounded-md border border-border bg-card hover:bg-muted/40 disabled:opacity-50"
        >
          {loading ? "Mapping..." : "Suggest mapping"}
        </button>
      </div>

      <CloudRoutingBanner />

      {vm && vm.cloudRouted ? (
        <Alert data-testid="mapping-suggest-cloud-banner">
          <AlertTitle>Cloud LLM routing</AlertTitle>
          <AlertDescription>
            This mapping suggestion was generated by a cloud LLM. Tenant data
            left the deployment for this request.
          </AlertDescription>
        </Alert>
      ) : null}

      {vm && (vm.status === "manual" || vm.status === "suppressed") ? (
        <Alert data-testid="mapping-suggest-manual">
          <AlertDescription>{vm.message}</AlertDescription>
        </Alert>
      ) : null}

      {vm && vm.status === "error" ? (
        <Alert variant="destructive" data-testid="mapping-suggest-error">
          <AlertDescription>{vm.message}</AlertDescription>
        </Alert>
      ) : null}

      {vm && vm.status === "proposed" ? (
        <div className="space-y-3" data-testid="mapping-suggest-proposal">
          <div className="flex flex-wrap items-center gap-2 text-[11px]">
            <span className="px-1.5 py-0.5 rounded bg-amber-500/15 text-amber-700 font-semibold">
              AI PROPOSAL · NOT APPROVED
            </span>
            {vm.modelLabel ? (
              <span className="text-muted-foreground font-mono">
                {vm.modelLabel}
              </span>
            ) : null}
          </div>
          <div className="rounded-md border border-border bg-card p-3">
            <div className="font-mono text-sm font-semibold text-primary">
              SCF:{vm.scfAnchorId}
            </div>
            {vm.title ? (
              <div className="text-sm text-foreground mt-1">{vm.title}</div>
            ) : null}
            <div className="text-sm text-muted-foreground mt-2">
              {vm.rationale}
            </div>
          </div>

          {actionError ? (
            <Alert variant="destructive" data-testid="mapping-action-error">
              <AlertDescription>{actionError}</AlertDescription>
            </Alert>
          ) : null}

          <div className="flex items-center gap-2">
            <button
              type="button"
              data-testid="mapping-approve"
              disabled={!vm.canApprove || acting}
              onClick={() => {
                void act("approve");
              }}
              className="text-xs px-3 py-1 rounded-md border border-primary bg-primary/10 text-primary font-medium hover:bg-primary/20 disabled:opacity-50"
            >
              {acting ? "Approving..." : "Approve mapping"}
            </button>
            <button
              type="button"
              data-testid="mapping-reject"
              disabled={acting}
              onClick={() => {
                void act("reject");
              }}
              className="text-xs px-3 py-1 rounded-md border border-border bg-card hover:bg-muted/40 disabled:opacity-50"
            >
              Reject
            </button>
          </div>
        </div>
      ) : null}
    </div>
  );
}
