// Slice 263 — Stage C suggestions panel (deterministic, AI-clean).
//
// Closes ISC-26..ISC-30 + AC-12..AC-14:
//
//   - Calls GET /api/questionnaires/{id}/suggestions?anchor=<SCF anchor>
//     (forwards to slice 155's deterministic SuggestForAnchor pgx query).
//   - Renders the TOP 3 results, ranked by the backend's most-recent-N
//     order (slice 155 D2; this slice's D3).
//   - Each card: 2-line excerpt of the prior answer + the SCF anchor ID
//     + the source label + a "Use this answer" button. Clicking the
//     button REPLACES the textarea content (NO append mode in v1).
//   - When the backend returns zero suggestions, renders a muted
//     "No prior answers for this anchor" caption.
//
// AI-assist boundary (P0-263-1) — load-bearing invariant enforcement:
//   This panel renders the suggestions endpoint output verbatim. The
//   endpoint is a deterministic SQL "most-recent-N for this anchor"
//   query (slice 155 D2 — see internal/questionnaire/library.go). It
//   is NOT an LLM call. The panel does NOT render:
//     - model name / version / provider badges
//     - confidence numbers / probability scores
//     - retrieval-context panels
//     - "AI drafted" / "Generated by …" labels
//     - any visual treatment that implies AI inference
//   The data is operator-authored prior answers; the panel surfaces
//   them as a faster way to copy-paste from history.

"use client";

import { useQuery } from "@tanstack/react-query";

import type { Suggestion } from "./types";

interface SuggestionsResp {
  suggestions: Suggestion[];
}

const TOP_N = 3;

async function fetchSuggestions(
  questionnaireID: string,
  anchor: string,
): Promise<Suggestion[]> {
  const qs = new URLSearchParams({ anchor });
  const res = await fetch(
    `/api/questionnaires/${questionnaireID}/suggestions?${qs.toString()}`,
    { cache: "no-store" },
  );
  if (!res.ok) {
    // Silent failure — the panel hides itself rather than nagging the
    // operator with a destructive toast. Authoring still works without
    // suggestions.
    return [];
  }
  const body = (await res.json()) as SuggestionsResp;
  return (body.suggestions ?? []).slice(0, TOP_N);
}

interface SuggestionsPanelProps {
  questionnaireID: string;
  anchor: string;
  onUseAnswer: (text: string) => void;
}

export function SuggestionsPanel({
  questionnaireID,
  anchor,
  onUseAnswer,
}: SuggestionsPanelProps) {
  const suggestionsQ = useQuery({
    queryKey: ["questionnaire-suggestions", questionnaireID, anchor],
    queryFn: () => fetchSuggestions(questionnaireID, anchor),
    enabled: anchor.length > 0,
  });

  // Silent absence — no decorative empty-state graphics; just a muted
  // caption. The panel itself is not "AI" so we don't badge it.
  if (anchor.length === 0) {
    return (
      <div
        data-testid="suggestions-panel"
        className="border border-border rounded-xl bg-muted/20 px-5 py-4 text-xs text-muted-foreground"
      >
        No SCF anchor mapped for this question — no prior answers to
        surface.
      </div>
    );
  }

  if (suggestionsQ.isLoading) {
    return (
      <div
        data-testid="suggestions-panel-loading"
        className="border border-border rounded-xl bg-muted/20 px-5 py-4 text-xs text-muted-foreground"
      >
        Looking up prior answers…
      </div>
    );
  }

  const items = suggestionsQ.data ?? [];

  if (items.length === 0) {
    return (
      <div
        data-testid="suggestions-panel-empty"
        className="border border-border rounded-xl bg-muted/20 px-5 py-4 text-xs text-muted-foreground"
      >
        No prior answers for this anchor.
      </div>
    );
  }

  return (
    <div
      data-testid="suggestions-panel"
      className="border border-border rounded-xl bg-card overflow-hidden"
    >
      <div className="flex items-center justify-between px-5 py-3 border-b border-border bg-muted/30">
        <div className="text-sm font-semibold text-foreground">
          Prior answers for SCF:{anchor}
        </div>
        <div className="font-mono text-[11px] text-muted-foreground">
          {items.length} {items.length === 1 ? "entry" : "entries"} ·
          most recent first
        </div>
      </div>
      {items.map((s) => (
        <SuggestionCard
          key={s.ID}
          suggestion={s}
          onUseAnswer={() => onUseAnswer(s.CanonicalText)}
        />
      ))}
    </div>
  );
}

interface SuggestionCardProps {
  suggestion: Suggestion;
  onUseAnswer: () => void;
}

function SuggestionCard({ suggestion, onUseAnswer }: SuggestionCardProps) {
  return (
    <div
      data-testid="suggestion-card"
      className="px-5 py-4 border-b border-border last:border-b-0 bg-card"
    >
      <div className="flex items-center justify-between mb-2">
        <span className="text-xs font-medium text-foreground">
          {suggestion.SourceLabel || "(no source label)"}
        </span>
        <button
          type="button"
          data-testid="suggestion-use-button"
          onClick={onUseAnswer}
          className="text-xs text-primary hover:underline font-medium"
        >
          Use this answer →
        </button>
      </div>
      <p className="text-sm leading-relaxed text-foreground/80 line-clamp-3">
        {suggestion.CanonicalText}
      </p>
      <div className="mt-2 text-[11px] text-muted-foreground font-mono">
        SCF:{suggestion.ScfAnchorID}
      </div>
    </div>
  );
}
