#!/usr/bin/env bash
#
# human-approver-guard.sh — falsifier for ISA.md ISC-4: "No audit-binding
# artifact reaches a customer or auditor without a recorded human approver."
#
# The claim has two ways to be false, named in ISC-4 itself:
#   (a) a row exists with ai_assisted=true AND human_approved=true AND a
#       null/empty human_approver — the shared `ai_assist_human_approver_guard`
#       CHECK (slice 498) should make this unreachable on every table that
#       carries the three columns.
#   (b) a publish path exists that bypasses the guard entirely — a table an
#       auditor-facing artifact flows through that never had the guard
#       columns to begin with, so nothing gates it.
#
# This probe checks both, dynamically for (a) and by name for (b). It is
# expected to fail on (b) today: the `artifacts` table (internal/artifact,
# migrations/sql/20260511000008_artifacts.sql) is the generic blob store
# behind the OSCAL SSP/POA&M `:download` route (internal/api/register_audit.go)
# and the walkthrough `/export` route — both handed directly to an auditor —
# and its own package doc says it holds "typical SOC 2 audit-pack bundles and
# annual policy exports". It carries none of ai_assisted / human_approved /
# human_approver. Nothing stops AI-generated bytes from being uploaded there
# and downloaded with zero record of human approval.
#
# Required env:
#   DATABASE_URL — connection string for a role with full pg_catalog
#                  visibility (atlas_migrate). Matches scripts/audit-rls.sh's
#                  convention: this is a structural check, not an RLS-scoped
#                  data check, so the migrate role is correct here.
#
# Exit codes:
#   0 — claim holds: no guard-violating row anywhere, and every table backing
#       a publish/download path carries the guard.
#   1 — claim is false: a violating row exists, or a publish-path table
#       lacks the guard columns entirely.
#   3 — cannot run: DATABASE_URL unset, psql missing, or connection failed.
#       This is a precondition failure, not a finding — do not read it as
#       either a pass or a fail on the claim.

set -Eeuo pipefail

if [[ -z "${DATABASE_URL:-}" ]]; then
  echo "human-approver-guard: DATABASE_URL is not set" >&2
  exit 3
fi

if ! command -v psql >/dev/null 2>&1; then
  echo "human-approver-guard: psql not on PATH" >&2
  exit 3
fi

if ! psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -Atqc 'select 1' >/dev/null 2>&1; then
  echo "human-approver-guard: could not connect via DATABASE_URL" >&2
  exit 3
fi

failed=0

# ---- (a) any row already violating the guard, on any table that carries
# the three columns. Expected to return zero rows today — the CHECK
# constraint should make this shape unreachable — but checked directly
# rather than assumed, since a probe that trusts the thing it is meant to
# falsify is not a falsifier.
# Results land in a TEMP table rather than RAISE NOTICE: NOTICE goes to
# psql's stderr, which `-Atq` output capture on stdout would silently drop.
# A plain SELECT at the end is what -Atq is meant to capture.
violations="$(psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -Atq <<'SQL'
CREATE TEMP TABLE guard_scan(table_name text, violation_count integer);
DO $$
DECLARE
    r RECORD;
    cnt INTEGER;
BEGIN
    FOR r IN
        SELECT c.table_name
        FROM information_schema.columns c
        WHERE c.table_schema = 'public'
          AND c.column_name = 'ai_assisted'
          AND EXISTS (
              SELECT 1 FROM information_schema.columns c2
              WHERE c2.table_schema = 'public' AND c2.table_name = c.table_name
                AND c2.column_name = 'human_approved'
          )
          AND EXISTS (
              SELECT 1 FROM information_schema.columns c3
              WHERE c3.table_schema = 'public' AND c3.table_name = c.table_name
                AND c3.column_name = 'human_approver'
          )
    LOOP
        EXECUTE format(
            'SELECT count(*) FROM %I WHERE ai_assisted = TRUE AND human_approved = TRUE '
            'AND (human_approver IS NULL OR length(trim(human_approver)) = 0)',
            r.table_name
        ) INTO cnt;
        IF cnt > 0 THEN
            INSERT INTO guard_scan VALUES (r.table_name, cnt);
        END IF;
    END LOOP;
END $$;
SELECT table_name || E'\t' || violation_count FROM guard_scan ORDER BY table_name;
SQL
)"

if [[ -n "$violations" ]]; then
  echo "human-approver-guard: FALSE — rows exist with ai_assisted=true, human_approved=true, and no human_approver" >&2
  echo "$violations" >&2
  failed=1
fi

# ---- (b) known publish/download paths whose backing table must carry the
# guard columns if it can hold AI-derived content, named by hand because the
# gap is structural (missing columns), not something a generic scan over
# "tables with ai_assisted" can discover — a table that bypasses the guard
# has no ai_assisted column to find in the first place.
#
# `artifacts` (internal/artifact) backs the OSCAL SSP/POA&M `:download`
# route and the walkthrough `/export` route (internal/api/register_audit.go)
# — both leave the system into an auditor's hands — and its own doc comment
# names it as the store for audit-pack bundles and policy exports.
publish_path_tables="artifacts"
for t in $publish_path_tables; do
  has_guard="$(psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -Atqc "
    SELECT (count(*) FILTER (WHERE column_name = 'ai_assisted') > 0
        AND count(*) FILTER (WHERE column_name = 'human_approved') > 0
        AND count(*) FILTER (WHERE column_name = 'human_approver') > 0)
    FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = '$t';
  ")"
  if [[ "$has_guard" != "t" ]]; then
    echo "human-approver-guard: FALSE — table '$t' backs an auditor-facing download path (OSCAL export, walkthrough export) but carries no ai_assisted/human_approved/human_approver columns, so nothing gates what gets published through it — a publish path that bypasses the guard entirely (ISC-4)" >&2
    failed=1
  fi
done

if [[ "$failed" -ne 0 ]]; then
  exit 1
fi

echo "human-approver-guard: PASS — no violating rows, and every named publish-path table carries the guard"
exit 0
