-- migrations/sql/20260612050000_board_narrative_ai.sql
--
-- Slice 440 — Board-narrative AI v0 (cited, numeric-verified, per-section
-- approval). The HIGHEST-RISK AI-WRITE surface in security-atlas: an
-- AI-drafted board-report SECTION an operator approves before it ships into
-- the board pack. Board members are non-technical and take the output at face
-- value, so the hallucination cost is asymmetric — the guardrails are the
-- constitutional boundary, not a nicety.
--
-- ----------------------------------------------------------------------------
-- WHY.
--
-- Slice 182 landed the board-narrative FOUNDATION (the tone anti-pattern
-- reference, ADR, and the documented schema extensions) but no implementation.
-- CLAUDE.md §"Board-narrative AI-assist (load-bearing — OQ #14 resolved)"
-- locks all seven guardrails and the schema-level extensions:
--
--     "Schema-level extensions when board-narrative v0 ships: the
--      ai_assisted=true <-> human_approver invariant extends to require
--      additional columns on board-narrative records: prompt_version,
--      model_name, model_version, model_provider (all NOT NULL). Old reports
--      stay immutable — versioning is snapshot-at-generation."
--
-- This migration lands the per-section board-narrative record carrying those
-- columns + the approval triple, and ADOPTS the slice-498 shared
-- `ai_assist_human_approver_guard(...)` CHECK so the schema-level invariant
--
--     ai_assisted=TRUE => (human_approved=TRUE => human_approver present)
--
-- is enforced at the DB layer — identically to questionnaire_answers (slice
-- 441) and mcp_write_proposals (slice 173). The predicate is NOT re-authored
-- (P0-498-4 discipline): we call the shared function.
--
-- ----------------------------------------------------------------------------
-- DESIGN CALLS (JUDGMENT slice — full rationale in
-- docs/audit-log/440-board-narrative-ai-v0-decisions.md):
--
--   * ONE section in v0 (control_coverage_summary). The table carries a
--     section_key so the follow-on sections coexist without a schema change.
--     A (tenant, period_end, section_key) draft is regenerated by UPSERT — the
--     latest draft for a section replaces the prior unapproved draft; the
--     immutable forensic history of EVERY generation lives in the append-only
--     slice-498 ai_generations ledger (surface='board_narrative'), so this
--     table is a current-state table and the audit trail is the ledger's job.
--
--   * Editable current-state, immutable forensics. This table is UPDATEable
--     (the operator edits the draft inline and approves it — guardrail 7);
--     "old reports stay immutable" is satisfied by the append-only
--     ai_generations ledger, which snapshots the system prompt + context +
--     raw draft at generation time and is never rewritten. The board pack that
--     consumes the APPROVED final_text is itself frozen by the slice-032
--     board-pack publish lifecycle. Separating editable current-state from the
--     immutable ledger mirrors the slice-441 questionnaire_answers split.
--
--   * Provenance completeness enforced ONLY when ai_assisted=TRUE — a
--     conditional CHECK, identical to questionnaire_answers (slice 441): an
--     AI-drafted section must carry a reconstructable model; a future
--     manually-authored section (ai_assisted=FALSE) is exempt because it has
--     no model.
--
--   * Per-section approval state lives on the row: ai_assisted /
--     human_approved / human_approver. Approval is a SEPARATE operator UPDATE
--     that records the approver — there is NO auto-approve path (P0-440-1).
--
-- ----------------------------------------------------------------------------
-- Constitutional invariants honored:
--
--   AI-assist boundary (hard): the shared CHECK is the schema-level
--     ai_assisted <-> human_approver enforcement; human_approved=TRUE without
--     human_approver is impossible at the DB layer (P0-440-2, AC-19). The
--     product never auto-approves — approval is a separate operator UPDATE
--     recording the approver. The four provenance columns are the
--     model-name+version+provider+prompt audit the boundary requires.
--   #6  Tenant isolation at the DB layer: four-policy FORCE ROW LEVEL SECURITY
--     on app.current_tenant. A Tenant-B narrative can never read or cite a
--     Tenant-A row (P0-440-3, AC-18) — the new table is RLS-scoped exactly
--     like board_briefs + questionnaire_answers.
--
-- Idempotency / reversibility (AC-22): paired
-- 20260612050000_board_narrative_ai.down.sql drops the table (CASCADE removes
-- its policies + indexes) for a clean up->down->up round-trip. No TYPE created.
-- ----------------------------------------------------------------------------

CREATE TABLE board_narrative_sections (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id       UUID NOT NULL REFERENCES tenants (id) ON DELETE CASCADE,

    -- The numbered section this record drafts. v0 ships exactly one
    -- ('control_coverage_summary'); follow-on sections add their own keys
    -- without a schema change.
    section_key     TEXT NOT NULL,

    -- The report period the section summarizes (YYYY-MM-DD). LABELS the
    -- section; the rollup numbers were computed live at generation time
    -- (same "the pin is immutability, not a time-travel query" discipline as
    -- the slice-031 brief).
    period_end      TEXT NOT NULL,

    -- The raw model draft, exactly as it passed the four pre-operator gates
    -- (citation / numeric / shape / tone). Bound as a parameterized value by
    -- the writer (P0-498-7) — never interpolated into SQL.
    raw_draft       TEXT NOT NULL,

    -- The operator's inline-edited text (guardrail 7 editor-mode). Empty until
    -- the operator edits; final_text is what ships.
    operator_edit   TEXT NOT NULL DEFAULT '',

    -- The approved final text (the operator's edited draft at approval time).
    -- Empty until approved. This is what the board pack consumes.
    final_text      TEXT NOT NULL DEFAULT '',

    -- The resolved, tenant-owned citations the section makes (JSONB array of
    -- {kind,id}). Every entry was proven in-grounding AND tenant-owned before
    -- the draft was persisted (guardrail 4).
    citations       JSONB NOT NULL DEFAULT '[]'::jsonb,

    -- Who triggered the generation (the authenticated credential id).
    authored_by     TEXT NOT NULL DEFAULT '',

    -- ===== AI-assist boundary approval triple =====
    -- True for an AI-drafted section (always TRUE in v0 — there is no manual
    -- path yet). The guard only constrains rows where this is TRUE.
    ai_assisted     BOOLEAN NOT NULL DEFAULT TRUE,

    -- True once an operator has approved the section (one-click per section —
    -- guardrail 2). FALSE for a fresh draft.
    human_approved  BOOLEAN NOT NULL DEFAULT FALSE,

    -- The operator id/credential that approved the section. NULL until
    -- approved. The shared guard forbids ai_assisted=TRUE + human_approved=TRUE
    -- with this NULL/blank (P0-440-2).
    human_approver  TEXT NULL,

    -- ===== snapshot-at-generation model provenance =====
    -- (slice-182 schema contract; mirrors ai_generations + questionnaire_answers.)
    prompt_version  TEXT NOT NULL DEFAULT '',
    model_name      TEXT NOT NULL DEFAULT '',
    model_version   TEXT NOT NULL DEFAULT '',
    model_provider  TEXT NOT NULL DEFAULT '',

    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- One current-state draft per (tenant, period, section): regeneration
    -- UPSERTs over the prior unapproved draft. The immutable history is the
    -- ai_generations ledger, not this table.
    CONSTRAINT board_narrative_sections_tenant_period_section_uniq
        UNIQUE (tenant_id, period_end, section_key)
);

-- The AI-assist boundary CHECK, ADOPTED from the slice-498 reusable function
-- (NOT re-authored). Fails ONLY for the forbidden shape: ai_assisted=TRUE AND
-- human_approved=TRUE AND a missing-or-empty human_approver. Schema-level
-- mirror of internal/llm's EnforceApproval (belt-and-suspenders: Go rejects
-- early, the DB is authoritative).
ALTER TABLE board_narrative_sections
    ADD CONSTRAINT board_narrative_sections_ai_assist_invariant
        CHECK (ai_assist_human_approver_guard(
            ai_assisted, human_approved, human_approver));

-- Provenance completeness, conditional on ai_assisted. An AI-drafted section
-- must carry a reconstructable model (no row whose model is unknown —
-- R-mitigation); a future manual section is exempt because it has no model.
ALTER TABLE board_narrative_sections
    ADD CONSTRAINT board_narrative_sections_ai_provenance_nonempty
        CHECK (
            NOT ai_assisted
            OR (
                length(prompt_version) > 0
                AND length(model_name) > 0
                AND length(model_version) > 0
                AND length(model_provider) > 0
            )
        );

CREATE INDEX board_narrative_sections_tenant_period_idx
    ON board_narrative_sections (tenant_id, period_end);

-- Four-policy FORCE ROW LEVEL SECURITY on app.current_tenant (invariant #6).
-- SELECT + INSERT + UPDATE + DELETE, each tenant-scoped — a Tenant-B caller can
-- neither read nor mutate a Tenant-A section. UPDATE is permitted (the operator
-- edits + approves the draft in place); the immutable forensic record is the
-- append-only ai_generations ledger, not this current-state table.
ALTER TABLE board_narrative_sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE board_narrative_sections FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_read ON board_narrative_sections
    FOR SELECT
    USING (current_tenant_matches(tenant_id));
CREATE POLICY tenant_write ON board_narrative_sections
    FOR INSERT
    WITH CHECK (current_tenant_matches(tenant_id));
CREATE POLICY tenant_update ON board_narrative_sections
    FOR UPDATE
    USING (current_tenant_matches(tenant_id))
    WITH CHECK (current_tenant_matches(tenant_id));
CREATE POLICY tenant_delete ON board_narrative_sections
    FOR DELETE
    USING (current_tenant_matches(tenant_id));

GRANT SELECT, INSERT, UPDATE, DELETE ON board_narrative_sections TO atlas_app;
