-- security-atlas — slice 126: external audit-log sink fallback table.
--
-- The slice-126 sink (internal/audit/sink) fans out every per-domain
-- audit-log INSERT to an external JSONL+HMAC file via a buffered channel
-- + writer goroutine. When the buffer overflows OR a sink-side write
-- fails (disk full, permission, broken pipe), the sink writes one row
-- to THIS table as the durable failure ledger.
--
-- Why this table exists:
--   * P0-A1 of slice 126 forbids silent-drop on backpressure. Every
--     record either makes the sink OR lands here.
--   * Ops needs a queryable artifact to investigate gaps — an ERROR
--     slog line alone is insufficient because the line is itself in
--     the in-app log surface which the in-app admin can read/redact.
--   * The append-only RLS + grant shape mirrors slice 062's
--     me_audit_log + the slice 036 four-policy precedent: SELECT +
--     INSERT only at the policy layer, SELECT + INSERT only at the
--     grant layer. atlas_app physically cannot UPDATE or DELETE a
--     row even with a misconfigured query.
--
-- What this table does NOT do:
--   * It does NOT mirror the full Entry.PayloadJSON. PayloadJSON could
--     be very large (e.g., evidence-audit payloads). The fallback's
--     job is to FLAG the gap and let ops correlate against the in-app
--     row, not to be a parallel evidence ledger.
--   * It does NOT replace the JSONL sink. Successful sink writes never
--     land here.
--
-- Constitutional invariants honored:
--   * Invariant #6 (RLS tenant isolation): four-policy append-only
--     with current_tenant_matches() under FORCE ROW LEVEL SECURITY.
--     atlas_app cannot read or write a row for another tenant.
--   * Canvas §4.3 (append-only ledger): no UPDATE/DELETE policy; no
--     UPDATE/DELETE grant. Append-only by construction.
--
-- Idempotency: the entire migration is wrapped in IF NOT EXISTS guards
-- where Postgres syntax allows. Re-apply against an already-migrated
-- database is a no-op.

CREATE TABLE IF NOT EXISTS audit_sink_failures (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id           UUID NOT NULL,
    occurred_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- failure_reason discriminates the two sink-side failure modes the
    -- writer goroutine can produce. buffer_overflow = the bounded
    -- in-memory channel rejected the send (Emit's default branch).
    -- write_error = the file-side write failed after the channel
    -- accepted the entry (disk full, broken pipe, permission denied
    -- after a file rotation race).
    failure_reason      TEXT NOT NULL
                        CHECK (failure_reason IN ('buffer_overflow', 'write_error')),
    -- entry_kind / entry_actor / entry_target_type / entry_target_id /
    -- entry_action are projected from the canonical unifiedlog.Entry
    -- so a correlating query against the in-app row (SELECT ... FROM
    -- <kind>_audit_log WHERE actor_id = ... AND target_id = ... AND
    -- occurred_at = ...) works without joining payload_json.
    entry_kind          TEXT NOT NULL,
    entry_actor         TEXT NOT NULL,
    entry_target_type   TEXT NOT NULL,
    entry_target_id     TEXT NOT NULL,
    entry_action        TEXT NOT NULL,
    -- error_text carries the OS-level error string for write_error
    -- failures. Empty for buffer_overflow (no underlying error
    -- generated by the channel rejection itself).
    error_text          TEXT NOT NULL DEFAULT ''
);

-- Composite index for the natural query: "show me the last N sink
-- failures for this tenant." Matches the slice-124 unified audit-log
-- query shape so a future extension can UNION ALL this table into the
-- aggregator if/when warranted.
CREATE INDEX IF NOT EXISTS idx_audit_sink_failures_tenant_occurred
    ON audit_sink_failures (tenant_id, occurred_at DESC);

-- ===== RLS: four-policy append-only =====
--
-- Pattern mirrors slice 062 / slice 108: SELECT + INSERT policies
-- under FORCE ROW LEVEL SECURITY, no UPDATE/DELETE policy.

ALTER TABLE audit_sink_failures ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_sink_failures FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_read ON audit_sink_failures;
CREATE POLICY tenant_read ON audit_sink_failures
    FOR SELECT USING (current_tenant_matches(tenant_id));

DROP POLICY IF EXISTS tenant_write ON audit_sink_failures;
CREATE POLICY tenant_write ON audit_sink_failures
    FOR INSERT WITH CHECK (current_tenant_matches(tenant_id));

-- Intentionally NO update/delete policies — append-only.

-- ===== Grants =====
--
-- atlas_app gets SELECT + INSERT only. No UPDATE / DELETE grant means
-- a future RLS misconfiguration (e.g., an accidentally-added
-- update_for_all policy) cannot escalate atlas_app's actual privileges.
-- atlas_migrate retains full grants for schema-evolution migrations.

GRANT SELECT, INSERT ON audit_sink_failures TO atlas_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON audit_sink_failures TO atlas_migrate;
