#!/usr/bin/env bash
# Generate docs-site/docs/metrics-reference.md from catalogs/metrics/*.yaml.
#
# Slice 076 AC-18: a reference table auto-generated at docs-build time so
# the docs page is never stale relative to the catalog YAML. Integrated
# into `just metrics-reference` + the mkdocs build pipeline.
#
# Reads every metric definition + cascade-edge from the YAML files (one
# file per board cascade) and emits a Markdown reference with:
#   - a per-board section
#   - a Mermaid cascade diagram per board
#   - a definition table for every metric in that cascade
#
# Pure bash + awk + python (yaml parse). No build-time external deps
# beyond what the repo already ships.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CATALOG_DIR="$ROOT/catalogs/metrics"
OUT="$ROOT/docs-site/docs/metrics-reference.md"

if [[ ! -d "$CATALOG_DIR" ]]; then
  echo "no catalog dir at $CATALOG_DIR" >&2
  exit 1
fi

python3 - "$CATALOG_DIR" "$OUT" <<'PY'
import os
import sys
import glob

try:
    import yaml
except ImportError:
    sys.stderr.write("python3 yaml module required (pip install pyyaml)\n")
    sys.exit(2)

catalog_dir = sys.argv[1]
out_path = sys.argv[2]

files = sorted(glob.glob(os.path.join(catalog_dir, "*.yaml")))
out = []
out.append("# Metrics reference\n")
out.append("> Auto-generated from `catalogs/metrics/*.yaml` by `just metrics-reference`.")
out.append("> Do NOT edit by hand. Edit the YAML and re-run the generator.\n")
out.append("## Catalog overview\n")
out.append("| Files | Metrics | Cascade edges |")
out.append("| --- | --- | --- |")

all_metrics = []
all_edges = []
per_file_sections = []

for fp in files:
    with open(fp) as f:
        data = yaml.safe_load(f) or {}
    metrics = data.get("metrics", [])
    file_section = []
    fname = os.path.basename(fp)
    title = fname.replace("-", " ").replace(".yaml", "").title()
    file_section.append(f"\n## {title}\n")
    file_section.append(f"_Source: `catalogs/metrics/{fname}`_\n")
    # Cascade Mermaid diagram for this board file.
    file_section.append("```mermaid")
    file_section.append("flowchart TB")
    for m in metrics:
        mid = m["id"]
        all_metrics.append(m)
        for p in m.get("parents", []) or []:
            parent_id = p["parent_id"]
            file_section.append(f"  {parent_id} --> {mid}")
            all_edges.append({"parent": parent_id, "child": mid})
    for m in metrics:
        mid = m["id"]
        # node label
        label = m["name"].replace('"', '\\"')
        file_section.append(f'  {mid}["{label}"]')
    file_section.append("```\n")

    # Per-metric definition table.
    file_section.append("| ID | Level | Cadence | Compute | Unit | Notes |")
    file_section.append("| --- | --- | --- | --- | --- | --- |")
    for m in metrics:
        notes_short = (m.get("notes", "") or "").split("\n")[0].strip()
        if len(notes_short) > 80:
            notes_short = notes_short[:77] + "..."
        evaluator = m.get("compute_evaluator", "") or ""
        compute = m["compute_strategy"]
        if evaluator:
            compute = f"{compute} (`{evaluator}`)"
        file_section.append(
            f"| `{m['id']}` | {m['level']} | {m['cadence']} | {compute} | {m['unit']} | {notes_short} |"
        )
    per_file_sections.append("\n".join(file_section))

# Overview table.
out.append(f"| {len(files)} | {len(all_metrics)} | {len(all_edges)} |\n")
out.extend(per_file_sections)
out.append("\n---\n")
out.append("Generated by `scripts/gen-metrics-reference.sh`.")

with open(out_path, "w") as f:
    f.write("\n".join(out))

print(f"wrote {out_path}: {len(all_metrics)} metrics, {len(all_edges)} edges, {len(files)} files")
PY
