// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: action_plans.sql

package dbx

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const actionPlanControlExists = `-- name: ActionPlanControlExists :one
SELECT EXISTS (
    SELECT 1 FROM action_plan_controls
    WHERE tenant_id = $1 AND action_plan_id = $2 AND control_id = $3
)
`

type ActionPlanControlExistsParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	ActionPlanID pgtype.UUID `json:"action_plan_id"`
	ControlID    pgtype.UUID `json:"control_id"`
}

func (q *Queries) ActionPlanControlExists(ctx context.Context, arg ActionPlanControlExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, actionPlanControlExists, arg.TenantID, arg.ActionPlanID, arg.ControlID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const actionPlanControlExistsInTenant = `-- name: ActionPlanControlExistsInTenant :one
SELECT EXISTS (
    SELECT 1 FROM controls WHERE tenant_id = $1 AND id = $2
)
`

type ActionPlanControlExistsInTenantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

// AC-19: same cross-tenant deny for controls.
func (q *Queries) ActionPlanControlExistsInTenant(ctx context.Context, arg ActionPlanControlExistsInTenantParams) (bool, error) {
	row := q.db.QueryRow(ctx, actionPlanControlExistsInTenant, arg.TenantID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const actionPlanOwnerExistsInTenant = `-- name: ActionPlanOwnerExistsInTenant :one
SELECT EXISTS (
    SELECT 1 FROM users WHERE tenant_id = $1 AND id = $2
)
`

type ActionPlanOwnerExistsInTenantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

// AC-10 tampering guard: owner_id must resolve to a user in the caller's
// tenant. RLS hides cross-tenant users.
func (q *Queries) ActionPlanOwnerExistsInTenant(ctx context.Context, arg ActionPlanOwnerExistsInTenantParams) (bool, error) {
	row := q.db.QueryRow(ctx, actionPlanOwnerExistsInTenant, arg.TenantID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const actionPlanRiskExists = `-- name: ActionPlanRiskExists :one
SELECT EXISTS (
    SELECT 1 FROM action_plan_risks
    WHERE tenant_id = $1 AND action_plan_id = $2 AND risk_id = $3
)
`

type ActionPlanRiskExistsParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	ActionPlanID pgtype.UUID `json:"action_plan_id"`
	RiskID       pgtype.UUID `json:"risk_id"`
}

func (q *Queries) ActionPlanRiskExists(ctx context.Context, arg ActionPlanRiskExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, actionPlanRiskExists, arg.TenantID, arg.ActionPlanID, arg.RiskID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const actionPlanRiskExistsInTenant = `-- name: ActionPlanRiskExistsInTenant :one

SELECT EXISTS (
    SELECT 1 FROM risks WHERE tenant_id = $1 AND id = $2
)
`

type ActionPlanRiskExistsInTenantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

// ===== existence probes for cross-tenant linkage guards =====
// AC-17/AC-29: a risk_id that does not resolve in the caller's tenant is a
// 404 (cross-tenant deny). RLS hides the cross-tenant row so EXISTS is false.
func (q *Queries) ActionPlanRiskExistsInTenant(ctx context.Context, arg ActionPlanRiskExistsInTenantParams) (bool, error) {
	row := q.db.QueryRow(ctx, actionPlanRiskExistsInTenant, arg.TenantID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countActionPlanControls = `-- name: CountActionPlanControls :one
SELECT count(*)
FROM action_plan_controls
WHERE tenant_id = $1 AND action_plan_id = $2
`

type CountActionPlanControlsParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	ActionPlanID pgtype.UUID `json:"action_plan_id"`
}

func (q *Queries) CountActionPlanControls(ctx context.Context, arg CountActionPlanControlsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActionPlanControls, arg.TenantID, arg.ActionPlanID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActionPlanRisks = `-- name: CountActionPlanRisks :one
SELECT count(*)
FROM action_plan_risks
WHERE tenant_id = $1 AND action_plan_id = $2
`

type CountActionPlanRisksParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	ActionPlanID pgtype.UUID `json:"action_plan_id"`
}

func (q *Queries) CountActionPlanRisks(ctx context.Context, arg CountActionPlanRisksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActionPlanRisks, arg.TenantID, arg.ActionPlanID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActionPlan = `-- name: CreateActionPlan :one

INSERT INTO action_plans (
    id, tenant_id, title, description, triggering_event,
    owner_id, due_date, status, audit_period_id
)
VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9
)
RETURNING id, tenant_id, title, description, triggering_event, owner_id, due_date, status, audit_period_id, tombstoned_at, created_at, updated_at
`

type CreateActionPlanParams struct {
	ID              pgtype.UUID `json:"id"`
	TenantID        pgtype.UUID `json:"tenant_id"`
	Title           string      `json:"title"`
	Description     *string     `json:"description"`
	TriggeringEvent *string     `json:"triggering_event"`
	OwnerID         pgtype.UUID `json:"owner_id"`
	DueDate         pgtype.Date `json:"due_date"`
	Status          string      `json:"status"`
	AuditPeriodID   pgtype.UUID `json:"audit_period_id"`
}

// ActionPlan primitive (slice 384). Tenant-scoped CRUD + M2M linkage +
// append-only audit log. Every query filters tenant_id explicitly (RLS is
// the backstop; the explicit predicate keeps the plan index-friendly).
func (q *Queries) CreateActionPlan(ctx context.Context, arg CreateActionPlanParams) (ActionPlan, error) {
	row := q.db.QueryRow(ctx, createActionPlan,
		arg.ID,
		arg.TenantID,
		arg.Title,
		arg.Description,
		arg.TriggeringEvent,
		arg.OwnerID,
		arg.DueDate,
		arg.Status,
		arg.AuditPeriodID,
	)
	var i ActionPlan
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.TriggeringEvent,
		&i.OwnerID,
		&i.DueDate,
		&i.Status,
		&i.AuditPeriodID,
		&i.TombstonedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActionPlanByID = `-- name: GetActionPlanByID :one
SELECT id, tenant_id, title, description, triggering_event, owner_id, due_date, status, audit_period_id, tombstoned_at, created_at, updated_at
FROM action_plans
WHERE tenant_id = $1 AND id = $2 AND tombstoned_at IS NULL
`

type GetActionPlanByIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

// Live (non-tombstoned) plan by id. A tombstoned plan reads as absent
// (AC-14: subsequent GET returns 404).
func (q *Queries) GetActionPlanByID(ctx context.Context, arg GetActionPlanByIDParams) (ActionPlan, error) {
	row := q.db.QueryRow(ctx, getActionPlanByID, arg.TenantID, arg.ID)
	var i ActionPlan
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.TriggeringEvent,
		&i.OwnerID,
		&i.DueDate,
		&i.Status,
		&i.AuditPeriodID,
		&i.TombstonedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkActionPlanControl = `-- name: LinkActionPlanControl :exec

INSERT INTO action_plan_controls (action_plan_id, control_id, tenant_id, linked_by)
VALUES ($1, $2, $3, $4)
`

type LinkActionPlanControlParams struct {
	ActionPlanID pgtype.UUID `json:"action_plan_id"`
	ControlID    pgtype.UUID `json:"control_id"`
	TenantID     pgtype.UUID `json:"tenant_id"`
	LinkedBy     pgtype.UUID `json:"linked_by"`
}

// ===== M2M: controls =====
func (q *Queries) LinkActionPlanControl(ctx context.Context, arg LinkActionPlanControlParams) error {
	_, err := q.db.Exec(ctx, linkActionPlanControl,
		arg.ActionPlanID,
		arg.ControlID,
		arg.TenantID,
		arg.LinkedBy,
	)
	return err
}

const linkActionPlanRisk = `-- name: LinkActionPlanRisk :exec

INSERT INTO action_plan_risks (action_plan_id, risk_id, tenant_id, linked_by)
VALUES ($1, $2, $3, $4)
`

type LinkActionPlanRiskParams struct {
	ActionPlanID pgtype.UUID `json:"action_plan_id"`
	RiskID       pgtype.UUID `json:"risk_id"`
	TenantID     pgtype.UUID `json:"tenant_id"`
	LinkedBy     pgtype.UUID `json:"linked_by"`
}

// ===== M2M: risks =====
// Idempotent at the handler layer (it checks existence first); the PK makes
// a duplicate INSERT a unique-violation the store maps to 409.
func (q *Queries) LinkActionPlanRisk(ctx context.Context, arg LinkActionPlanRiskParams) error {
	_, err := q.db.Exec(ctx, linkActionPlanRisk,
		arg.ActionPlanID,
		arg.RiskID,
		arg.TenantID,
		arg.LinkedBy,
	)
	return err
}

const listActionPlanAuditLog = `-- name: ListActionPlanAuditLog :many
SELECT id, tenant_id, action_plan_id, actor_id, action_type, before_state, after_state, created_at
FROM action_plan_audit_log
WHERE tenant_id = $1 AND action_plan_id = $2
ORDER BY created_at ASC, id ASC
`

type ListActionPlanAuditLogParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	ActionPlanID pgtype.UUID `json:"action_plan_id"`
}

func (q *Queries) ListActionPlanAuditLog(ctx context.Context, arg ListActionPlanAuditLogParams) ([]ActionPlanAuditLog, error) {
	rows, err := q.db.Query(ctx, listActionPlanAuditLog, arg.TenantID, arg.ActionPlanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActionPlanAuditLog
	for rows.Next() {
		var i ActionPlanAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ActionPlanID,
			&i.ActorID,
			&i.ActionType,
			&i.BeforeState,
			&i.AfterState,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActionPlanControls = `-- name: ListActionPlanControls :many
SELECT control_id, linked_at, linked_by
FROM action_plan_controls
WHERE tenant_id = $1 AND action_plan_id = $2
ORDER BY linked_at ASC
`

type ListActionPlanControlsParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	ActionPlanID pgtype.UUID `json:"action_plan_id"`
}

type ListActionPlanControlsRow struct {
	ControlID pgtype.UUID        `json:"control_id"`
	LinkedAt  pgtype.Timestamptz `json:"linked_at"`
	LinkedBy  pgtype.UUID        `json:"linked_by"`
}

func (q *Queries) ListActionPlanControls(ctx context.Context, arg ListActionPlanControlsParams) ([]ListActionPlanControlsRow, error) {
	rows, err := q.db.Query(ctx, listActionPlanControls, arg.TenantID, arg.ActionPlanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActionPlanControlsRow
	for rows.Next() {
		var i ListActionPlanControlsRow
		if err := rows.Scan(&i.ControlID, &i.LinkedAt, &i.LinkedBy); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActionPlanIDsForControl = `-- name: ListActionPlanIDsForControl :many
SELECT ap.id, ap.title, ap.status, ap.due_date
FROM action_plan_controls apc
JOIN action_plans ap ON ap.id = apc.action_plan_id AND ap.tenant_id = apc.tenant_id
WHERE apc.tenant_id = $1 AND apc.control_id = $2 AND ap.tombstoned_at IS NULL
ORDER BY ap.created_at DESC
`

type ListActionPlanIDsForControlParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	ControlID pgtype.UUID `json:"control_id"`
}

type ListActionPlanIDsForControlRow struct {
	ID      pgtype.UUID `json:"id"`
	Title   string      `json:"title"`
	Status  string      `json:"status"`
	DueDate pgtype.Date `json:"due_date"`
}

// Powers the "Linked Action Plans" read-only section on /controls/{id} (AC-26).
func (q *Queries) ListActionPlanIDsForControl(ctx context.Context, arg ListActionPlanIDsForControlParams) ([]ListActionPlanIDsForControlRow, error) {
	rows, err := q.db.Query(ctx, listActionPlanIDsForControl, arg.TenantID, arg.ControlID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActionPlanIDsForControlRow
	for rows.Next() {
		var i ListActionPlanIDsForControlRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.DueDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActionPlanIDsForRisk = `-- name: ListActionPlanIDsForRisk :many
SELECT ap.id, ap.title, ap.status, ap.due_date
FROM action_plan_risks apr
JOIN action_plans ap ON ap.id = apr.action_plan_id AND ap.tenant_id = apr.tenant_id
WHERE apr.tenant_id = $1 AND apr.risk_id = $2 AND ap.tombstoned_at IS NULL
ORDER BY ap.created_at DESC
`

type ListActionPlanIDsForRiskParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	RiskID   pgtype.UUID `json:"risk_id"`
}

type ListActionPlanIDsForRiskRow struct {
	ID      pgtype.UUID `json:"id"`
	Title   string      `json:"title"`
	Status  string      `json:"status"`
	DueDate pgtype.Date `json:"due_date"`
}

// Powers the "Linked Action Plans" read-only section on /risks/{id} (AC-25).
// Joins to action_plans so tombstoned plans are excluded.
func (q *Queries) ListActionPlanIDsForRisk(ctx context.Context, arg ListActionPlanIDsForRiskParams) ([]ListActionPlanIDsForRiskRow, error) {
	rows, err := q.db.Query(ctx, listActionPlanIDsForRisk, arg.TenantID, arg.RiskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActionPlanIDsForRiskRow
	for rows.Next() {
		var i ListActionPlanIDsForRiskRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.DueDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActionPlanRisks = `-- name: ListActionPlanRisks :many
SELECT risk_id, linked_at, linked_by
FROM action_plan_risks
WHERE tenant_id = $1 AND action_plan_id = $2
ORDER BY linked_at ASC
`

type ListActionPlanRisksParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	ActionPlanID pgtype.UUID `json:"action_plan_id"`
}

type ListActionPlanRisksRow struct {
	RiskID   pgtype.UUID        `json:"risk_id"`
	LinkedAt pgtype.Timestamptz `json:"linked_at"`
	LinkedBy pgtype.UUID        `json:"linked_by"`
}

func (q *Queries) ListActionPlanRisks(ctx context.Context, arg ListActionPlanRisksParams) ([]ListActionPlanRisksRow, error) {
	rows, err := q.db.Query(ctx, listActionPlanRisks, arg.TenantID, arg.ActionPlanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActionPlanRisksRow
	for rows.Next() {
		var i ListActionPlanRisksRow
		if err := rows.Scan(&i.RiskID, &i.LinkedAt, &i.LinkedBy); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActionPlans = `-- name: ListActionPlans :many
SELECT id, tenant_id, title, description, triggering_event, owner_id, due_date, status, audit_period_id, tombstoned_at, created_at, updated_at
FROM action_plans
WHERE tenant_id = $1
  AND tombstoned_at IS NULL
  AND ($2::text IS NULL OR status = $2::text)
  AND (
        $3::timestamptz IS NULL
        OR (created_at, id) < ($3::timestamptz, $4::uuid)
      )
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListActionPlansParams struct {
	TenantID        pgtype.UUID        `json:"tenant_id"`
	Status          *string            `json:"status"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	RowLimit        int32              `json:"row_limit"`
}

// Cursor pagination on created_at DESC, id DESC. The cursor is the
// (created_at, id) of the last row of the previous page; when the cursor
// timestamp is NULL (sqlc.narg), the first page is returned. Tombstoned
// rows are excluded.
func (q *Queries) ListActionPlans(ctx context.Context, arg ListActionPlansParams) ([]ActionPlan, error) {
	rows, err := q.db.Query(ctx, listActionPlans,
		arg.TenantID,
		arg.Status,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActionPlan
	for rows.Next() {
		var i ActionPlan
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Title,
			&i.Description,
			&i.TriggeringEvent,
			&i.OwnerID,
			&i.DueDate,
			&i.Status,
			&i.AuditPeriodID,
			&i.TombstonedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActionPlansSnapshot = `-- name: ListActionPlansSnapshot :many
SELECT id, tenant_id, title, description, triggering_event, owner_id, due_date, status, audit_period_id, tombstoned_at, created_at, updated_at
FROM action_plans
WHERE tenant_id = $1
  AND tombstoned_at IS NULL
  AND created_at <= $2
ORDER BY created_at DESC, id DESC
`

type ListActionPlansSnapshotParams struct {
	TenantID  pgtype.UUID        `json:"tenant_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// AC-27 audit-period-freezing snapshot: only plans created on or before the
// period's frozen_at horizon are included in the period's snapshot. Live
// state continues independently; this read is the frozen view.
func (q *Queries) ListActionPlansSnapshot(ctx context.Context, arg ListActionPlansSnapshotParams) ([]ActionPlan, error) {
	rows, err := q.db.Query(ctx, listActionPlansSnapshot, arg.TenantID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActionPlan
	for rows.Next() {
		var i ActionPlan
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Title,
			&i.Description,
			&i.TriggeringEvent,
			&i.OwnerID,
			&i.DueDate,
			&i.Status,
			&i.AuditPeriodID,
			&i.TombstonedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tombstoneActionPlan = `-- name: TombstoneActionPlan :one
UPDATE action_plans
SET tombstoned_at = now(),
    updated_at = now()
WHERE tenant_id = $1 AND id = $2 AND tombstoned_at IS NULL
RETURNING id, tenant_id, title, description, triggering_event, owner_id, due_date, status, audit_period_id, tombstoned_at, created_at, updated_at
`

type TombstoneActionPlanParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

// Soft-delete (P0-384-6). Sets tombstoned_at; the row is preserved. A
// second tombstone is a no-op-miss (already tombstoned -> zero rows -> 404).
func (q *Queries) TombstoneActionPlan(ctx context.Context, arg TombstoneActionPlanParams) (ActionPlan, error) {
	row := q.db.QueryRow(ctx, tombstoneActionPlan, arg.TenantID, arg.ID)
	var i ActionPlan
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.TriggeringEvent,
		&i.OwnerID,
		&i.DueDate,
		&i.Status,
		&i.AuditPeriodID,
		&i.TombstonedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unlinkActionPlanControl = `-- name: UnlinkActionPlanControl :execrows
DELETE FROM action_plan_controls
WHERE tenant_id = $1 AND action_plan_id = $2 AND control_id = $3
`

type UnlinkActionPlanControlParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	ActionPlanID pgtype.UUID `json:"action_plan_id"`
	ControlID    pgtype.UUID `json:"control_id"`
}

func (q *Queries) UnlinkActionPlanControl(ctx context.Context, arg UnlinkActionPlanControlParams) (int64, error) {
	result, err := q.db.Exec(ctx, unlinkActionPlanControl, arg.TenantID, arg.ActionPlanID, arg.ControlID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unlinkActionPlanRisk = `-- name: UnlinkActionPlanRisk :execrows
DELETE FROM action_plan_risks
WHERE tenant_id = $1 AND action_plan_id = $2 AND risk_id = $3
`

type UnlinkActionPlanRiskParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	ActionPlanID pgtype.UUID `json:"action_plan_id"`
	RiskID       pgtype.UUID `json:"risk_id"`
}

func (q *Queries) UnlinkActionPlanRisk(ctx context.Context, arg UnlinkActionPlanRiskParams) (int64, error) {
	result, err := q.db.Exec(ctx, unlinkActionPlanRisk, arg.TenantID, arg.ActionPlanID, arg.RiskID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateActionPlan = `-- name: UpdateActionPlan :one
UPDATE action_plans
SET title = $3,
    description = $4,
    triggering_event = $5,
    owner_id = $6,
    due_date = $7,
    status = $8,
    audit_period_id = $9,
    updated_at = now()
WHERE tenant_id = $1 AND id = $2 AND tombstoned_at IS NULL
RETURNING id, tenant_id, title, description, triggering_event, owner_id, due_date, status, audit_period_id, tombstoned_at, created_at, updated_at
`

type UpdateActionPlanParams struct {
	TenantID        pgtype.UUID `json:"tenant_id"`
	ID              pgtype.UUID `json:"id"`
	Title           string      `json:"title"`
	Description     *string     `json:"description"`
	TriggeringEvent *string     `json:"triggering_event"`
	OwnerID         pgtype.UUID `json:"owner_id"`
	DueDate         pgtype.Date `json:"due_date"`
	Status          string      `json:"status"`
	AuditPeriodID   pgtype.UUID `json:"audit_period_id"`
}

// Updates the editable fields + status in one statement. The DB transition
// trigger (action_plans_status_transition_trg) rejects an illegal status
// edge; the store also validates before calling. updated_at is bumped.
func (q *Queries) UpdateActionPlan(ctx context.Context, arg UpdateActionPlanParams) (ActionPlan, error) {
	row := q.db.QueryRow(ctx, updateActionPlan,
		arg.TenantID,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.TriggeringEvent,
		arg.OwnerID,
		arg.DueDate,
		arg.Status,
		arg.AuditPeriodID,
	)
	var i ActionPlan
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.TriggeringEvent,
		&i.OwnerID,
		&i.DueDate,
		&i.Status,
		&i.AuditPeriodID,
		&i.TombstonedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const writeActionPlanAuditLog = `-- name: WriteActionPlanAuditLog :one

INSERT INTO action_plan_audit_log (
    id, tenant_id, action_plan_id, actor_id, action_type, before_state, after_state
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, action_plan_id, actor_id, action_type, before_state, after_state, created_at
`

type WriteActionPlanAuditLogParams struct {
	ID           pgtype.UUID `json:"id"`
	TenantID     pgtype.UUID `json:"tenant_id"`
	ActionPlanID pgtype.UUID `json:"action_plan_id"`
	ActorID      pgtype.UUID `json:"actor_id"`
	ActionType   string      `json:"action_type"`
	BeforeState  []byte      `json:"before_state"`
	AfterState   []byte      `json:"after_state"`
}

// ===== append-only audit log =====
// Every mutation writes one row (AC-16). UPDATE/DELETE are rejected by the
// append-only trigger; this INSERT is the only path that writes here.
func (q *Queries) WriteActionPlanAuditLog(ctx context.Context, arg WriteActionPlanAuditLogParams) (ActionPlanAuditLog, error) {
	row := q.db.QueryRow(ctx, writeActionPlanAuditLog,
		arg.ID,
		arg.TenantID,
		arg.ActionPlanID,
		arg.ActorID,
		arg.ActionType,
		arg.BeforeState,
		arg.AfterState,
	)
	var i ActionPlanAuditLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ActionPlanID,
		&i.ActorID,
		&i.ActionType,
		&i.BeforeState,
		&i.AfterState,
		&i.CreatedAt,
	)
	return i, err
}
