// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package dbx

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, tenant_id, token_hash, scope_predicate, allowed_kinds, issued_by, issued_at, expires_at, last_used_at, revoked_at, rotated_from, retires_at, is_admin, is_approver, owner_roles, last4, ttl_seconds
FROM api_keys
WHERE token_hash = $1
`

// Constant-time lookup by HMAC hash. Returns the row whether revoked, retired,
// or expired — the caller (credstore.Authenticate) is responsible for the
// state-check tree.
func (q *Queries) GetAPIKeyByHash(ctx context.Context, tokenHash []byte) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, tokenHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TokenHash,
		&i.ScopePredicate,
		&i.AllowedKinds,
		&i.IssuedBy,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.RotatedFrom,
		&i.RetiresAt,
		&i.IsAdmin,
		&i.IsApprover,
		&i.OwnerRoles,
		&i.Last4,
		&i.TtlSeconds,
	)
	return i, err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT id, tenant_id, token_hash, scope_predicate, allowed_kinds, issued_by, issued_at, expires_at, last_used_at, revoked_at, rotated_from, retires_at, is_admin, is_approver, owner_roles, last4, ttl_seconds
FROM api_keys
WHERE tenant_id = $1 AND id = $2
`

type GetAPIKeyByIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetAPIKeyByID(ctx context.Context, arg GetAPIKeyByIDParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByID, arg.TenantID, arg.ID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TokenHash,
		&i.ScopePredicate,
		&i.AllowedKinds,
		&i.IssuedBy,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.RotatedFrom,
		&i.RetiresAt,
		&i.IsAdmin,
		&i.IsApprover,
		&i.OwnerRoles,
		&i.Last4,
		&i.TtlSeconds,
	)
	return i, err
}

const insertAPIKey = `-- name: InsertAPIKey :one
INSERT INTO api_keys (
    id, tenant_id, token_hash, scope_predicate, allowed_kinds,
    issued_by, expires_at, rotated_from,
    is_admin, is_approver, owner_roles, last4, ttl_seconds
)
VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9, $10, $11, $12, $13
)
RETURNING id, tenant_id, token_hash, scope_predicate, allowed_kinds, issued_by, issued_at, expires_at, last_used_at, revoked_at, rotated_from, retires_at, is_admin, is_approver, owner_roles, last4, ttl_seconds
`

type InsertAPIKeyParams struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	TokenHash      []byte             `json:"token_hash"`
	ScopePredicate []byte             `json:"scope_predicate"`
	AllowedKinds   []string           `json:"allowed_kinds"`
	IssuedBy       pgtype.UUID        `json:"issued_by"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	RotatedFrom    pgtype.UUID        `json:"rotated_from"`
	IsAdmin        bool               `json:"is_admin"`
	IsApprover     bool               `json:"is_approver"`
	OwnerRoles     []string           `json:"owner_roles"`
	Last4          string             `json:"last4"`
	TtlSeconds     int64              `json:"ttl_seconds"`
}

// Persist a new API key. token_hash is HMAC-SHA256(plaintext, BEARER_HASH_KEY)
// per ADR 0002 — computed by the application layer before this call. last4 is
// the last four characters of the plaintext bearer (safe to surface).
func (q *Queries) InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, insertAPIKey,
		arg.ID,
		arg.TenantID,
		arg.TokenHash,
		arg.ScopePredicate,
		arg.AllowedKinds,
		arg.IssuedBy,
		arg.ExpiresAt,
		arg.RotatedFrom,
		arg.IsAdmin,
		arg.IsApprover,
		arg.OwnerRoles,
		arg.Last4,
		arg.TtlSeconds,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TokenHash,
		&i.ScopePredicate,
		&i.AllowedKinds,
		&i.IssuedBy,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.RotatedFrom,
		&i.RetiresAt,
		&i.IsAdmin,
		&i.IsApprover,
		&i.OwnerRoles,
		&i.Last4,
		&i.TtlSeconds,
	)
	return i, err
}

const listAPIKeysByTenant = `-- name: ListAPIKeysByTenant :many
SELECT id, tenant_id, token_hash, scope_predicate, allowed_kinds, issued_by, issued_at, expires_at, last_used_at, revoked_at, rotated_from, retires_at, is_admin, is_approver, owner_roles, last4, ttl_seconds
FROM api_keys
WHERE tenant_id = $1 AND revoked_at IS NULL
ORDER BY issued_at DESC
`

// Active keys for a tenant. Excludes revoked rows; includes retired-but-not-yet-
// past-grace predecessors so the admin UI can show "rotating out — valid until X."
func (q *Queries) ListAPIKeysByTenant(ctx context.Context, tenantID pgtype.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TokenHash,
			&i.ScopePredicate,
			&i.AllowedKinds,
			&i.IssuedBy,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.RotatedFrom,
			&i.RetiresAt,
			&i.IsAdmin,
			&i.IsApprover,
			&i.OwnerRoles,
			&i.Last4,
			&i.TtlSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE api_keys
SET revoked_at = now()
WHERE tenant_id = $1 AND id = $2
`

type RevokeAPIKeyParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error {
	_, err := q.db.Exec(ctx, revokeAPIKey, arg.TenantID, arg.ID)
	return err
}

const setAPIKeyRetiresAt = `-- name: SetAPIKeyRetiresAt :exec
UPDATE api_keys
SET retires_at = $3
WHERE tenant_id = $1 AND id = $2 AND revoked_at IS NULL
`

type SetAPIKeyRetiresAtParams struct {
	TenantID  pgtype.UUID        `json:"tenant_id"`
	ID        pgtype.UUID        `json:"id"`
	RetiresAt pgtype.Timestamptz `json:"retires_at"`
}

// Set the predecessor's retirement deadline on rotation. After retires_at the
// predecessor's bearer no longer authenticates (credstore.Authenticate enforces).
func (q *Queries) SetAPIKeyRetiresAt(ctx context.Context, arg SetAPIKeyRetiresAtParams) error {
	_, err := q.db.Exec(ctx, setAPIKeyRetiresAt, arg.TenantID, arg.ID, arg.RetiresAt)
	return err
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :exec
UPDATE api_keys
SET last_used_at = now()
WHERE token_hash = $1
`

// Best-effort timestamp bump. Failure here is logged but never blocks the
// authenticated request.
func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, touchAPIKeyLastUsed, tokenHash)
	return err
}
