// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artifacts.sql

package dbx

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createArtifact = `-- name: CreateArtifact :one
INSERT INTO artifacts (
    id, tenant_id, storage_key, content_hash, size_bytes,
    content_type, uploaded_by
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, tenant_id, storage_key, content_hash, size_bytes, content_type, uploaded_by, uploaded_at
`

type CreateArtifactParams struct {
	ID          pgtype.UUID `json:"id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
	StorageKey  string      `json:"storage_key"`
	ContentHash *string     `json:"content_hash"`
	SizeBytes   int64       `json:"size_bytes"`
	ContentType string      `json:"content_type"`
	UploadedBy  string      `json:"uploaded_by"`
}

// Insert an artifact row after the blob has been written to S3. RLS
// evaluates the INSERT WITH CHECK against current_tenant. content_hash
// may be NULL today but every code path in slice 036 supplies it.
func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, createArtifact,
		arg.ID,
		arg.TenantID,
		arg.StorageKey,
		arg.ContentHash,
		arg.SizeBytes,
		arg.ContentType,
		arg.UploadedBy,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StorageKey,
		&i.ContentHash,
		&i.SizeBytes,
		&i.ContentType,
		&i.UploadedBy,
		&i.UploadedAt,
	)
	return i, err
}

const findArtifactByHash = `-- name: FindArtifactByHash :one
SELECT id, tenant_id, storage_key, content_hash, size_bytes, content_type, uploaded_by, uploaded_at FROM artifacts
WHERE tenant_id = $1 AND content_hash = $2
`

type FindArtifactByHashParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	ContentHash *string     `json:"content_hash"`
}

// Dedup lookup: returns an existing artifact id when the same content
// has already been uploaded by this tenant. Partial unique index
// (tenant_id, content_hash) WHERE content_hash IS NOT NULL keeps the
// result single-row.
func (q *Queries) FindArtifactByHash(ctx context.Context, arg FindArtifactByHashParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, findArtifactByHash, arg.TenantID, arg.ContentHash)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StorageKey,
		&i.ContentHash,
		&i.SizeBytes,
		&i.ContentType,
		&i.UploadedBy,
		&i.UploadedAt,
	)
	return i, err
}

const getArtifact = `-- name: GetArtifact :one
SELECT id, tenant_id, storage_key, content_hash, size_bytes, content_type, uploaded_by, uploaded_at FROM artifacts
WHERE tenant_id = $1 AND id = $2
`

type GetArtifactParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

// Look up an artifact by id. RLS USING current_tenant_matches(tenant_id)
// means the row is invisible to other tenants — handler interprets
// pgx.ErrNoRows as 404 (no existence leak).
func (q *Queries) GetArtifact(ctx context.Context, arg GetArtifactParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifact, arg.TenantID, arg.ID)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StorageKey,
		&i.ContentHash,
		&i.SizeBytes,
		&i.ContentType,
		&i.UploadedBy,
		&i.UploadedAt,
	)
	return i, err
}

const listArtifactAccessLog = `-- name: ListArtifactAccessLog :many
SELECT id, tenant_id, artifact_id, action, actor, occurred_at FROM artifact_access_log
WHERE tenant_id = $1 AND artifact_id = $2
ORDER BY occurred_at DESC
LIMIT 100
`

type ListArtifactAccessLogParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	ArtifactID pgtype.UUID `json:"artifact_id"`
}

// Per-artifact recent history. Used by the admin view (slice 040) and
// the audit-export bundler (slice 029). Cap at 100 rows.
func (q *Queries) ListArtifactAccessLog(ctx context.Context, arg ListArtifactAccessLogParams) ([]ArtifactAccessLog, error) {
	rows, err := q.db.Query(ctx, listArtifactAccessLog, arg.TenantID, arg.ArtifactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArtifactAccessLog
	for rows.Next() {
		var i ArtifactAccessLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ArtifactID,
			&i.Action,
			&i.Actor,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logArtifactAccess = `-- name: LogArtifactAccess :exec
INSERT INTO artifact_access_log (
    id, tenant_id, artifact_id, action, actor
)
VALUES (
    $1, $2, $3, $4, $5
)
`

type LogArtifactAccessParams struct {
	ID         pgtype.UUID `json:"id"`
	TenantID   pgtype.UUID `json:"tenant_id"`
	ArtifactID pgtype.UUID `json:"artifact_id"`
	Action     string      `json:"action"`
	Actor      string      `json:"actor"`
}

// Append a row to the access log. Action is enforced by CHECK
// ('upload' | 'download'). Caller passes tenant_id + artifact_id + actor.
func (q *Queries) LogArtifactAccess(ctx context.Context, arg LogArtifactAccessParams) error {
	_, err := q.db.Exec(ctx, logArtifactAccess,
		arg.ID,
		arg.TenantID,
		arg.ArtifactID,
		arg.Action,
		arg.Actor,
	)
	return err
}
