// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backup_runs.sql

package dbx

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const finishBackupRunFailed = `-- name: FinishBackupRunFailed :one
UPDATE backup_runs
SET outcome     = 'failed',
    detail      = $2,
    finished_at = now()
WHERE id = $1
RETURNING id, kind, target_kind, artifact_name, outcome, size_bytes, content_hash, detail, started_at, finished_at
`

type FinishBackupRunFailedParams struct {
	ID     pgtype.UUID `json:"id"`
	Detail string      `json:"detail"`
}

// Transition a run to failed with a short reason. Never carries credentials.
func (q *Queries) FinishBackupRunFailed(ctx context.Context, arg FinishBackupRunFailedParams) (BackupRun, error) {
	row := q.db.QueryRow(ctx, finishBackupRunFailed, arg.ID, arg.Detail)
	var i BackupRun
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.TargetKind,
		&i.ArtifactName,
		&i.Outcome,
		&i.SizeBytes,
		&i.ContentHash,
		&i.Detail,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishBackupRunSucceeded = `-- name: FinishBackupRunSucceeded :one
UPDATE backup_runs
SET outcome      = 'succeeded',
    artifact_name = COALESCE($2, artifact_name),
    size_bytes   = $3,
    content_hash = $4,
    detail       = $5,
    finished_at  = now()
WHERE id = $1
RETURNING id, kind, target_kind, artifact_name, outcome, size_bytes, content_hash, detail, started_at, finished_at
`

type FinishBackupRunSucceededParams struct {
	ID           pgtype.UUID `json:"id"`
	ArtifactName *string     `json:"artifact_name"`
	SizeBytes    int64       `json:"size_bytes"`
	ContentHash  string      `json:"content_hash"`
	Detail       string      `json:"detail"`
}

// Transition a run to succeeded with the produced/verified artifact details.
func (q *Queries) FinishBackupRunSucceeded(ctx context.Context, arg FinishBackupRunSucceededParams) (BackupRun, error) {
	row := q.db.QueryRow(ctx, finishBackupRunSucceeded,
		arg.ID,
		arg.ArtifactName,
		arg.SizeBytes,
		arg.ContentHash,
		arg.Detail,
	)
	var i BackupRun
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.TargetKind,
		&i.ArtifactName,
		&i.Outcome,
		&i.SizeBytes,
		&i.ContentHash,
		&i.Detail,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const latestSucceededBackup = `-- name: LatestSucceededBackup :one
SELECT id, kind, target_kind, artifact_name, outcome, size_bytes, content_hash, detail, started_at, finished_at
FROM backup_runs
WHERE kind = 'backup' AND outcome = 'succeeded'
ORDER BY started_at DESC
LIMIT 1
`

// The most recent successful backup run — what restore-verification restores.
func (q *Queries) LatestSucceededBackup(ctx context.Context) (BackupRun, error) {
	row := q.db.QueryRow(ctx, latestSucceededBackup)
	var i BackupRun
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.TargetKind,
		&i.ArtifactName,
		&i.Outcome,
		&i.SizeBytes,
		&i.ContentHash,
		&i.Detail,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listRecentBackupRuns = `-- name: ListRecentBackupRuns :many
SELECT id, kind, target_kind, artifact_name, outcome, size_bytes, content_hash, detail, started_at, finished_at
FROM backup_runs
WHERE kind = $1
ORDER BY started_at DESC
LIMIT $2
`

type ListRecentBackupRunsParams struct {
	Kind  string `json:"kind"`
	Limit int32  `json:"limit"`
}

// Latest runs of a kind, newest first — backs the deployment status surface.
func (q *Queries) ListRecentBackupRuns(ctx context.Context, arg ListRecentBackupRunsParams) ([]BackupRun, error) {
	rows, err := q.db.Query(ctx, listRecentBackupRuns, arg.Kind, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BackupRun
	for rows.Next() {
		var i BackupRun
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.TargetKind,
			&i.ArtifactName,
			&i.Outcome,
			&i.SizeBytes,
			&i.ContentHash,
			&i.Detail,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startBackupRun = `-- name: StartBackupRun :one

INSERT INTO backup_runs (kind, target_kind, artifact_name)
VALUES ($1, $2, $3)
RETURNING id, kind, target_kind, artifact_name, outcome, size_bytes, content_hash, detail, started_at, finished_at
`

type StartBackupRunParams struct {
	Kind         string  `json:"kind"`
	TargetKind   *string `json:"target_kind"`
	ArtifactName *string `json:"artifact_name"`
}

// backup_runs — slice 510 automated-backup status/audit ledger.
//
// DEPLOYMENT-scope (no tenant_id): a backup is a full cross-tenant operation.
// Granted to atlas_migrate ONLY (P0-510-1 / AC-7) — the in-process backup
// scheduler runs as the BYPASSRLS migrator role; no tenant-facing handler
// (atlas_app) can reach this table. Append-only: INSERT begins a run, the
// narrow Finish* updates transition outcome once; no DELETE query exists.
// Insert a run in the `running` state. kind is 'backup' or 'verify'.
func (q *Queries) StartBackupRun(ctx context.Context, arg StartBackupRunParams) (BackupRun, error) {
	row := q.db.QueryRow(ctx, startBackupRun, arg.Kind, arg.TargetKind, arg.ArtifactName)
	var i BackupRun
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.TargetKind,
		&i.ArtifactName,
		&i.Outcome,
		&i.SizeBytes,
		&i.ContentHash,
		&i.Detail,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}
