// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channel_delivery.sql

package dbx

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimChannelDigest = `-- name: ClaimChannelDigest :one
INSERT INTO channel_delivery_log (
    tenant_id, channel, recipient_user_id, digest_key, outcome, attempts
)
VALUES ($1, $2, $3, $4, 'pending', 0)
ON CONFLICT (tenant_id, channel, recipient_user_id, digest_key) DO NOTHING
RETURNING id
`

type ClaimChannelDigestParams struct {
	TenantID        pgtype.UUID `json:"tenant_id"`
	Channel         string      `json:"channel"`
	RecipientUserID string      `json:"recipient_user_id"`
	DigestKey       string      `json:"digest_key"`
}

// Idempotency claim: insert a pending delivery-log row for
// (tenant, channel, recipient, digest_key). ON CONFLICT DO NOTHING means a
// second claim returns no row — the caller skips the send (no double-send /
// 24h rate-limit). The `channel` column keeps slack + webhook claims
// independent.
func (q *Queries) ClaimChannelDigest(ctx context.Context, arg ClaimChannelDigestParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, claimChannelDigest,
		arg.TenantID,
		arg.Channel,
		arg.RecipientUserID,
		arg.DigestKey,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getChannelDeliveryLog = `-- name: GetChannelDeliveryLog :one
SELECT id, tenant_id, channel, recipient_user_id, digest_key, outcome, attempts, last_error, created_at, sent_at FROM channel_delivery_log
WHERE tenant_id = $1 AND id = $2
`

type GetChannelDeliveryLogParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

// Read a delivery-log row by id (tests + outcome inspection).
func (q *Queries) GetChannelDeliveryLog(ctx context.Context, arg GetChannelDeliveryLogParams) (ChannelDeliveryLog, error) {
	row := q.db.QueryRow(ctx, getChannelDeliveryLog, arg.TenantID, arg.ID)
	var i ChannelDeliveryLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Channel,
		&i.RecipientUserID,
		&i.DigestKey,
		&i.Outcome,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.SentAt,
	)
	return i, err
}

const getSlackOptIn = `-- name: GetSlackOptIn :one

SELECT enabled
FROM slack_channel_optin
WHERE tenant_id = $1 AND user_id = $2
`

type GetSlackOptInParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

// Slice 543 — Slack + generic-webhook notification delivery channel queries.
//
// These back two additional delivery SINKS (NOT producers, P0-543-4),
// generalizing the slice-445 email queries. All queries are tenant-scoped
// via the leading tenant_id; RLS under FORCE keeps the cross-tenant
// boundary safe even on a misconfigured query (defense-in-depth).
// Read a user's Slack-channel master opt-in. A missing row (pgx.ErrNoRows)
// means OPTED-OUT (P0-543-3).
func (q *Queries) GetSlackOptIn(ctx context.Context, arg GetSlackOptInParams) (bool, error) {
	row := q.db.QueryRow(ctx, getSlackOptIn, arg.TenantID, arg.UserID)
	var enabled bool
	err := row.Scan(&enabled)
	return enabled, err
}

const getWebhookOptIn = `-- name: GetWebhookOptIn :one
SELECT enabled
FROM webhook_channel_optin
WHERE tenant_id = $1 AND user_id = $2
`

type GetWebhookOptInParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

// Read a user's webhook-channel master opt-in. Missing row = OPTED-OUT.
func (q *Queries) GetWebhookOptIn(ctx context.Context, arg GetWebhookOptInParams) (bool, error) {
	row := q.db.QueryRow(ctx, getWebhookOptIn, arg.TenantID, arg.UserID)
	var enabled bool
	err := row.Scan(&enabled)
	return enabled, err
}

const listSlackOptInUsers = `-- name: ListSlackOptInUsers :many
SELECT tenant_id, user_id
FROM slack_channel_optin
WHERE enabled = true
ORDER BY tenant_id, user_id
`

type ListSlackOptInUsersRow struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

// Slice 582 — digest-scheduler enumeration for the Slack channel: every
// (tenant, user) pair that has OPTED IN. Walked from the BYPASSRLS migrator
// pool (all tenants in one pass); per-user delivery re-reads under the
// user's own tenant GUC (RLS). enabled = false / no-row excluded (default
// opted-OUT, P0-543-3). Returns only the (tenant, user) keys — no PII.
func (q *Queries) ListSlackOptInUsers(ctx context.Context) ([]ListSlackOptInUsersRow, error) {
	rows, err := q.db.Query(ctx, listSlackOptInUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSlackOptInUsersRow
	for rows.Next() {
		var i ListSlackOptInUsersRow
		if err := rows.Scan(&i.TenantID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookOptInUsers = `-- name: ListWebhookOptInUsers :many
SELECT tenant_id, user_id
FROM webhook_channel_optin
WHERE enabled = true
ORDER BY tenant_id, user_id
`

type ListWebhookOptInUsersRow struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

// Slice 582 — digest-scheduler enumeration for the webhook channel: every
// (tenant, user) pair that has OPTED IN. Same shape + guarantees as
// ListSlackOptInUsers. enabled = false / no-row excluded (default
// opted-OUT). Returns only the (tenant, user) keys — no PII.
func (q *Queries) ListWebhookOptInUsers(ctx context.Context) ([]ListWebhookOptInUsersRow, error) {
	rows, err := q.db.Query(ctx, listWebhookOptInUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWebhookOptInUsersRow
	for rows.Next() {
		var i ListWebhookOptInUsersRow
		if err := rows.Scan(&i.TenantID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markChannelDigestFailed = `-- name: MarkChannelDigestFailed :exec
UPDATE channel_delivery_log
SET outcome = 'failed', attempts = attempts + 1, last_error = $3
WHERE tenant_id = $1 AND id = $2
`

type MarkChannelDigestFailedParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	ID        pgtype.UUID `json:"id"`
	LastError string      `json:"last_error"`
}

// Record a failed delivery. outcome=failed + last_error + attempts++. The
// digest_key is NOT released — the next tick can re-attempt (D8 analog).
func (q *Queries) MarkChannelDigestFailed(ctx context.Context, arg MarkChannelDigestFailedParams) error {
	_, err := q.db.Exec(ctx, markChannelDigestFailed, arg.TenantID, arg.ID, arg.LastError)
	return err
}

const markChannelDigestSent = `-- name: MarkChannelDigestSent :exec
UPDATE channel_delivery_log
SET outcome = 'sent', sent_at = now(), attempts = attempts + 1, last_error = ''
WHERE tenant_id = $1 AND id = $2
`

type MarkChannelDigestSentParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

// Record a successful delivery. outcome=sent + sent_at + attempts++.
func (q *Queries) MarkChannelDigestSent(ctx context.Context, arg MarkChannelDigestSentParams) error {
	_, err := q.db.Exec(ctx, markChannelDigestSent, arg.TenantID, arg.ID)
	return err
}

const upsertSlackOptIn = `-- name: UpsertSlackOptIn :one
INSERT INTO slack_channel_optin (tenant_id, user_id, enabled, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (tenant_id, user_id)
DO UPDATE SET enabled = EXCLUDED.enabled, updated_at = now()
RETURNING enabled
`

type UpsertSlackOptInParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
	Enabled  bool        `json:"enabled"`
}

// Set a user's Slack-channel master opt-in. (tenant_id, user_id) PK is the
// conflict target.
func (q *Queries) UpsertSlackOptIn(ctx context.Context, arg UpsertSlackOptInParams) (bool, error) {
	row := q.db.QueryRow(ctx, upsertSlackOptIn, arg.TenantID, arg.UserID, arg.Enabled)
	var enabled bool
	err := row.Scan(&enabled)
	return enabled, err
}

const upsertWebhookOptIn = `-- name: UpsertWebhookOptIn :one
INSERT INTO webhook_channel_optin (tenant_id, user_id, enabled, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (tenant_id, user_id)
DO UPDATE SET enabled = EXCLUDED.enabled, updated_at = now()
RETURNING enabled
`

type UpsertWebhookOptInParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
	Enabled  bool        `json:"enabled"`
}

// Set a user's webhook-channel master opt-in.
func (q *Queries) UpsertWebhookOptIn(ctx context.Context, arg UpsertWebhookOptInParams) (bool, error) {
	row := q.db.QueryRow(ctx, upsertWebhookOptIn, arg.TenantID, arg.UserID, arg.Enabled)
	var enabled bool
	err := row.Scan(&enabled)
	return enabled, err
}
