// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: changes.sql

package dbx

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveChange = `-- name: ApproveChange :one
UPDATE changes
SET status = 'approved',
    approver_id = $3,
    approved_at = $4,
    updated_at = now()
WHERE tenant_id = $1
  AND id = $2
  AND status = 'proposed'
RETURNING id, tenant_id, title, description, source, source_ref, source_url, status, proposed_by, proposed_at, approver_id, approved_at, implemented_by, implemented_at, verified_by, verified_at, risk_notes, rollback_notes, created_at, updated_at
`

type ApproveChangeParams struct {
	TenantID   pgtype.UUID        `json:"tenant_id"`
	ID         pgtype.UUID        `json:"id"`
	ApproverID pgtype.UUID        `json:"approver_id"`
	ApprovedAt pgtype.Timestamptz `json:"approved_at"`
}

func (q *Queries) ApproveChange(ctx context.Context, arg ApproveChangeParams) (Change, error) {
	row := q.db.QueryRow(ctx, approveChange,
		arg.TenantID,
		arg.ID,
		arg.ApproverID,
		arg.ApprovedAt,
	)
	var i Change
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.Source,
		&i.SourceRef,
		&i.SourceUrl,
		&i.Status,
		&i.ProposedBy,
		&i.ProposedAt,
		&i.ApproverID,
		&i.ApprovedAt,
		&i.ImplementedBy,
		&i.ImplementedAt,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.RiskNotes,
		&i.RollbackNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const changeControlExistsInTenant = `-- name: ChangeControlExistsInTenant :one
SELECT EXISTS (
    SELECT 1 FROM controls WHERE tenant_id = $1 AND id = $2
)
`

type ChangeControlExistsInTenantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) ChangeControlExistsInTenant(ctx context.Context, arg ChangeControlExistsInTenantParams) (bool, error) {
	row := q.db.QueryRow(ctx, changeControlExistsInTenant, arg.TenantID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const changeRollup = `-- name: ChangeRollup :one
SELECT
    count(*)::bigint AS total,
    count(*) FILTER (WHERE status = 'proposed')::bigint AS proposed,
    count(*) FILTER (WHERE status = 'approved')::bigint AS approved,
    count(*) FILTER (WHERE status = 'implemented')::bigint AS implemented,
    count(*) FILTER (WHERE status = 'verified')::bigint AS verified,
    count(*) FILTER (WHERE status <> 'verified')::bigint AS backlog,
    count(*) FILTER (WHERE verified_at >= now() - interval '30 days')::bigint AS verified_last_30_days
FROM changes
WHERE tenant_id = $1
`

type ChangeRollupRow struct {
	Total              int64 `json:"total"`
	Proposed           int64 `json:"proposed"`
	Approved           int64 `json:"approved"`
	Implemented        int64 `json:"implemented"`
	Verified           int64 `json:"verified"`
	Backlog            int64 `json:"backlog"`
	VerifiedLast30Days int64 `json:"verified_last_30_days"`
}

func (q *Queries) ChangeRollup(ctx context.Context, tenantID pgtype.UUID) (ChangeRollupRow, error) {
	row := q.db.QueryRow(ctx, changeRollup, tenantID)
	var i ChangeRollupRow
	err := row.Scan(
		&i.Total,
		&i.Proposed,
		&i.Approved,
		&i.Implemented,
		&i.Verified,
		&i.Backlog,
		&i.VerifiedLast30Days,
	)
	return i, err
}

const changeUserExistsInTenant = `-- name: ChangeUserExistsInTenant :one
SELECT EXISTS (
    SELECT 1 FROM users WHERE tenant_id = $1 AND id = $2
)
`

type ChangeUserExistsInTenantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) ChangeUserExistsInTenant(ctx context.Context, arg ChangeUserExistsInTenantParams) (bool, error) {
	row := q.db.QueryRow(ctx, changeUserExistsInTenant, arg.TenantID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createChange = `-- name: CreateChange :one

INSERT INTO changes (
    id, tenant_id, title, description,
    source, source_ref, source_url,
    proposed_by, risk_notes, rollback_notes
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10
)
RETURNING id, tenant_id, title, description, source, source_ref, source_url, status, proposed_by, proposed_at, approver_id, approved_at, implemented_by, implemented_at, verified_by, verified_at, risk_notes, rollback_notes, created_at, updated_at
`

type CreateChangeParams struct {
	ID            pgtype.UUID `json:"id"`
	TenantID      pgtype.UUID `json:"tenant_id"`
	Title         string      `json:"title"`
	Description   string      `json:"description"`
	Source        string      `json:"source"`
	SourceRef     string      `json:"source_ref"`
	SourceUrl     string      `json:"source_url"`
	ProposedBy    pgtype.UUID `json:"proposed_by"`
	RiskNotes     string      `json:"risk_notes"`
	RollbackNotes string      `json:"rollback_notes"`
}

// Change-management register queries for OE-629.
func (q *Queries) CreateChange(ctx context.Context, arg CreateChangeParams) (Change, error) {
	row := q.db.QueryRow(ctx, createChange,
		arg.ID,
		arg.TenantID,
		arg.Title,
		arg.Description,
		arg.Source,
		arg.SourceRef,
		arg.SourceUrl,
		arg.ProposedBy,
		arg.RiskNotes,
		arg.RollbackNotes,
	)
	var i Change
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.Source,
		&i.SourceRef,
		&i.SourceUrl,
		&i.Status,
		&i.ProposedBy,
		&i.ProposedAt,
		&i.ApproverID,
		&i.ApprovedAt,
		&i.ImplementedBy,
		&i.ImplementedAt,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.RiskNotes,
		&i.RollbackNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChangeByID = `-- name: GetChangeByID :one
SELECT id, tenant_id, title, description, source, source_ref, source_url, status, proposed_by, proposed_at, approver_id, approved_at, implemented_by, implemented_at, verified_by, verified_at, risk_notes, rollback_notes, created_at, updated_at
FROM changes
WHERE tenant_id = $1 AND id = $2
`

type GetChangeByIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetChangeByID(ctx context.Context, arg GetChangeByIDParams) (Change, error) {
	row := q.db.QueryRow(ctx, getChangeByID, arg.TenantID, arg.ID)
	var i Change
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.Source,
		&i.SourceRef,
		&i.SourceUrl,
		&i.Status,
		&i.ProposedBy,
		&i.ProposedAt,
		&i.ApproverID,
		&i.ApprovedAt,
		&i.ImplementedBy,
		&i.ImplementedAt,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.RiskNotes,
		&i.RollbackNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChangeBySourceRef = `-- name: GetChangeBySourceRef :one
SELECT id, tenant_id, title, description, source, source_ref, source_url, status, proposed_by, proposed_at, approver_id, approved_at, implemented_by, implemented_at, verified_by, verified_at, risk_notes, rollback_notes, created_at, updated_at
FROM changes
WHERE tenant_id = $1 AND source = $2 AND source_ref = $3
`

type GetChangeBySourceRefParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	Source    string      `json:"source"`
	SourceRef string      `json:"source_ref"`
}

func (q *Queries) GetChangeBySourceRef(ctx context.Context, arg GetChangeBySourceRefParams) (Change, error) {
	row := q.db.QueryRow(ctx, getChangeBySourceRef, arg.TenantID, arg.Source, arg.SourceRef)
	var i Change
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.Source,
		&i.SourceRef,
		&i.SourceUrl,
		&i.Status,
		&i.ProposedBy,
		&i.ProposedAt,
		&i.ApproverID,
		&i.ApprovedAt,
		&i.ImplementedBy,
		&i.ImplementedAt,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.RiskNotes,
		&i.RollbackNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const implementChange = `-- name: ImplementChange :one
UPDATE changes
SET status = 'implemented',
    implemented_by = $3,
    implemented_at = $4,
    updated_at = now()
WHERE tenant_id = $1
  AND id = $2
  AND status = 'approved'
RETURNING id, tenant_id, title, description, source, source_ref, source_url, status, proposed_by, proposed_at, approver_id, approved_at, implemented_by, implemented_at, verified_by, verified_at, risk_notes, rollback_notes, created_at, updated_at
`

type ImplementChangeParams struct {
	TenantID      pgtype.UUID        `json:"tenant_id"`
	ID            pgtype.UUID        `json:"id"`
	ImplementedBy pgtype.UUID        `json:"implemented_by"`
	ImplementedAt pgtype.Timestamptz `json:"implemented_at"`
}

func (q *Queries) ImplementChange(ctx context.Context, arg ImplementChangeParams) (Change, error) {
	row := q.db.QueryRow(ctx, implementChange,
		arg.TenantID,
		arg.ID,
		arg.ImplementedBy,
		arg.ImplementedAt,
	)
	var i Change
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.Source,
		&i.SourceRef,
		&i.SourceUrl,
		&i.Status,
		&i.ProposedBy,
		&i.ProposedAt,
		&i.ApproverID,
		&i.ApprovedAt,
		&i.ImplementedBy,
		&i.ImplementedAt,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.RiskNotes,
		&i.RollbackNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkChangeControl = `-- name: LinkChangeControl :exec
INSERT INTO change_controls (change_id, control_id, tenant_id, linked_by)
VALUES ($1, $2, $3, $4)
`

type LinkChangeControlParams struct {
	ChangeID  pgtype.UUID `json:"change_id"`
	ControlID pgtype.UUID `json:"control_id"`
	TenantID  pgtype.UUID `json:"tenant_id"`
	LinkedBy  pgtype.UUID `json:"linked_by"`
}

func (q *Queries) LinkChangeControl(ctx context.Context, arg LinkChangeControlParams) error {
	_, err := q.db.Exec(ctx, linkChangeControl,
		arg.ChangeID,
		arg.ControlID,
		arg.TenantID,
		arg.LinkedBy,
	)
	return err
}

const listChangeAuditLog = `-- name: ListChangeAuditLog :many
SELECT id, tenant_id, change_id, actor_id, action_type, before_state, after_state, created_at
FROM change_audit_log
WHERE tenant_id = $1 AND change_id = $2
ORDER BY created_at ASC, id ASC
`

type ListChangeAuditLogParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ChangeID pgtype.UUID `json:"change_id"`
}

func (q *Queries) ListChangeAuditLog(ctx context.Context, arg ListChangeAuditLogParams) ([]ChangeAuditLog, error) {
	rows, err := q.db.Query(ctx, listChangeAuditLog, arg.TenantID, arg.ChangeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChangeAuditLog
	for rows.Next() {
		var i ChangeAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ChangeID,
			&i.ActorID,
			&i.ActionType,
			&i.BeforeState,
			&i.AfterState,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChangeControls = `-- name: ListChangeControls :many
SELECT control_id, linked_at, linked_by
FROM change_controls
WHERE tenant_id = $1 AND change_id = $2
ORDER BY linked_at ASC, control_id ASC
`

type ListChangeControlsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ChangeID pgtype.UUID `json:"change_id"`
}

type ListChangeControlsRow struct {
	ControlID pgtype.UUID        `json:"control_id"`
	LinkedAt  pgtype.Timestamptz `json:"linked_at"`
	LinkedBy  pgtype.UUID        `json:"linked_by"`
}

func (q *Queries) ListChangeControls(ctx context.Context, arg ListChangeControlsParams) ([]ListChangeControlsRow, error) {
	rows, err := q.db.Query(ctx, listChangeControls, arg.TenantID, arg.ChangeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChangeControlsRow
	for rows.Next() {
		var i ListChangeControlsRow
		if err := rows.Scan(&i.ControlID, &i.LinkedAt, &i.LinkedBy); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChanges = `-- name: ListChanges :many
SELECT id, tenant_id, title, description, source, source_ref, source_url, status, proposed_by, proposed_at, approver_id, approved_at, implemented_by, implemented_at, verified_by, verified_at, risk_notes, rollback_notes, created_at, updated_at
FROM changes
WHERE tenant_id = $1
  AND ($2::text IS NULL OR status = $2::text)
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListChangesParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Status   *string     `json:"status"`
	RowLimit int32       `json:"row_limit"`
}

func (q *Queries) ListChanges(ctx context.Context, arg ListChangesParams) ([]Change, error) {
	rows, err := q.db.Query(ctx, listChanges, arg.TenantID, arg.Status, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Change
	for rows.Next() {
		var i Change
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Title,
			&i.Description,
			&i.Source,
			&i.SourceRef,
			&i.SourceUrl,
			&i.Status,
			&i.ProposedBy,
			&i.ProposedAt,
			&i.ApproverID,
			&i.ApprovedAt,
			&i.ImplementedBy,
			&i.ImplementedAt,
			&i.VerifiedBy,
			&i.VerifiedAt,
			&i.RiskNotes,
			&i.RollbackNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const verifyChange = `-- name: VerifyChange :one
UPDATE changes
SET status = 'verified',
    verified_by = $3,
    verified_at = $4,
    updated_at = now()
WHERE tenant_id = $1
  AND id = $2
  AND status = 'implemented'
RETURNING id, tenant_id, title, description, source, source_ref, source_url, status, proposed_by, proposed_at, approver_id, approved_at, implemented_by, implemented_at, verified_by, verified_at, risk_notes, rollback_notes, created_at, updated_at
`

type VerifyChangeParams struct {
	TenantID   pgtype.UUID        `json:"tenant_id"`
	ID         pgtype.UUID        `json:"id"`
	VerifiedBy pgtype.UUID        `json:"verified_by"`
	VerifiedAt pgtype.Timestamptz `json:"verified_at"`
}

func (q *Queries) VerifyChange(ctx context.Context, arg VerifyChangeParams) (Change, error) {
	row := q.db.QueryRow(ctx, verifyChange,
		arg.TenantID,
		arg.ID,
		arg.VerifiedBy,
		arg.VerifiedAt,
	)
	var i Change
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.Source,
		&i.SourceRef,
		&i.SourceUrl,
		&i.Status,
		&i.ProposedBy,
		&i.ProposedAt,
		&i.ApproverID,
		&i.ApprovedAt,
		&i.ImplementedBy,
		&i.ImplementedAt,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.RiskNotes,
		&i.RollbackNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const writeChangeAuditLog = `-- name: WriteChangeAuditLog :one
INSERT INTO change_audit_log (
    id, tenant_id, change_id, actor_id, action_type, before_state, after_state
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, tenant_id, change_id, actor_id, action_type, before_state, after_state, created_at
`

type WriteChangeAuditLogParams struct {
	ID          pgtype.UUID `json:"id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
	ChangeID    pgtype.UUID `json:"change_id"`
	ActorID     pgtype.UUID `json:"actor_id"`
	ActionType  string      `json:"action_type"`
	BeforeState []byte      `json:"before_state"`
	AfterState  []byte      `json:"after_state"`
}

func (q *Queries) WriteChangeAuditLog(ctx context.Context, arg WriteChangeAuditLogParams) (ChangeAuditLog, error) {
	row := q.db.QueryRow(ctx, writeChangeAuditLog,
		arg.ID,
		arg.TenantID,
		arg.ChangeID,
		arg.ActorID,
		arg.ActionType,
		arg.BeforeState,
		arg.AfterState,
	)
	var i ChangeAuditLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChangeID,
		&i.ActorID,
		&i.ActionType,
		&i.BeforeState,
		&i.AfterState,
		&i.CreatedAt,
	)
	return i, err
}
