// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checklist.sql

package dbx

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveChecklistSection = `-- name: ApproveChecklistSection :one
UPDATE checklist_sections
SET human_approved = TRUE,
    human_approver = $2,
    updated_at = now()
WHERE tenant_id = $1
  AND id = $3
  AND ai_assisted = TRUE
  AND human_approved = FALSE
RETURNING id, tenant_id, generation_id, role, ai_assisted, human_approved, human_approver, prompt_version, model_name, model_version, model_provider, created_at, updated_at
`

type ApproveChecklistSectionParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	HumanApprover *string     `json:"human_approver"`
	ID            pgtype.UUID `json:"id"`
}

// One-click per-section approval (AC-10): flip human_approved=TRUE + record the
// approver on an AI-assisted, currently-unapproved section. The
// ai_assisted=TRUE AND human_approver IS NOT NULL guard in the WHERE means an
// attempt to "approve" the unassigned bucket (ai_assisted=FALSE) or supply a
// blank approver matches no row (ErrNoRows) — there is NO auto-approve path.
// The DB CHECK is the authoritative backstop. updated_at is refreshed.
func (q *Queries) ApproveChecklistSection(ctx context.Context, arg ApproveChecklistSectionParams) (ChecklistSection, error) {
	row := q.db.QueryRow(ctx, approveChecklistSection, arg.TenantID, arg.HumanApprover, arg.ID)
	var i ChecklistSection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.GenerationID,
		&i.Role,
		&i.AiAssisted,
		&i.HumanApproved,
		&i.HumanApprover,
		&i.PromptVersion,
		&i.ModelName,
		&i.ModelVersion,
		&i.ModelProvider,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countChecklistSectionsForTenant = `-- name: CountChecklistSectionsForTenant :one
SELECT count(*) AS section_count
FROM checklist_sections
WHERE tenant_id = $1
`

// Count of all checklist sections visible to the caller's tenant. Used by the
// cross-tenant isolation integration test to prove tenant B sees zero of
// tenant A's rows (AC-8).
func (q *Queries) CountChecklistSectionsForTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countChecklistSectionsForTenant, tenantID)
	var section_count int64
	err := row.Scan(&section_count)
	return section_count, err
}

const getChecklistSectionByID = `-- name: GetChecklistSectionByID :one
SELECT id, tenant_id, generation_id, role, ai_assisted, human_approved, human_approver, prompt_version, model_name, model_version, model_provider, created_at, updated_at
FROM checklist_sections
WHERE tenant_id = $1 AND id = $2
`

type GetChecklistSectionByIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

// Fetch one section by id within the caller's tenant. Used by the approval flow
// + tests. A cross-tenant id returns ErrNoRows.
func (q *Queries) GetChecklistSectionByID(ctx context.Context, arg GetChecklistSectionByIDParams) (ChecklistSection, error) {
	row := q.db.QueryRow(ctx, getChecklistSectionByID, arg.TenantID, arg.ID)
	var i ChecklistSection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.GenerationID,
		&i.Role,
		&i.AiAssisted,
		&i.HumanApproved,
		&i.HumanApprover,
		&i.PromptVersion,
		&i.ModelName,
		&i.ModelVersion,
		&i.ModelProvider,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertChecklistItem = `-- name: InsertChecklistItem :one
INSERT INTO checklist_items (
    tenant_id,
    section_id,
    control_id,
    task_text,
    citations,
    no_evidence,
    sort_order
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, section_id, control_id, task_text, citations, no_evidence, sort_order, created_at
`

type InsertChecklistItemParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	SectionID  pgtype.UUID `json:"section_id"`
	ControlID  pgtype.UUID `json:"control_id"`
	TaskText   string      `json:"task_text"`
	Citations  []byte      `json:"citations"`
	NoEvidence bool        `json:"no_evidence"`
	SortOrder  int32       `json:"sort_order"`
}

// Persist one cited task statement in a section. citations is the validated,
// tenant-resolved JSONB array (the service guarantees every cited id resolves
// BEFORE this write — P0-471-2); the CHECK guarantees the array is non-empty.
// no_evidence marks a control with no evidence backing as an explicit gap
// (AC-6). task_text is bound as a parameter (model output never interpolated).
func (q *Queries) InsertChecklistItem(ctx context.Context, arg InsertChecklistItemParams) (ChecklistItem, error) {
	row := q.db.QueryRow(ctx, insertChecklistItem,
		arg.TenantID,
		arg.SectionID,
		arg.ControlID,
		arg.TaskText,
		arg.Citations,
		arg.NoEvidence,
		arg.SortOrder,
	)
	var i ChecklistItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SectionID,
		&i.ControlID,
		&i.TaskText,
		&i.Citations,
		&i.NoEvidence,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const insertChecklistSection = `-- name: InsertChecklistSection :one
INSERT INTO checklist_sections (
    tenant_id,
    generation_id,
    role,
    ai_assisted,
    prompt_version,
    model_name,
    model_version,
    model_provider
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, generation_id, role, ai_assisted, human_approved, human_approver, prompt_version, model_name, model_version, model_provider, created_at, updated_at
`

type InsertChecklistSectionParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	GenerationID  pgtype.UUID `json:"generation_id"`
	Role          string      `json:"role"`
	AiAssisted    bool        `json:"ai_assisted"`
	PromptVersion string      `json:"prompt_version"`
	ModelName     string      `json:"model_name"`
	ModelVersion  string      `json:"model_version"`
	ModelProvider string      `json:"model_provider"`
}

// Persist one approvable role-section of a generation (ai_assisted, UNAPPROVED).
// A real role-section is ai_assisted=TRUE with full model provenance; the
// unassigned bucket is ai_assisted=FALSE with empty provenance. The shared
// ai_assist_human_approver_guard CHECK forbids the approved-without-approver
// shape at INSERT time too.
func (q *Queries) InsertChecklistSection(ctx context.Context, arg InsertChecklistSectionParams) (ChecklistSection, error) {
	row := q.db.QueryRow(ctx, insertChecklistSection,
		arg.TenantID,
		arg.GenerationID,
		arg.Role,
		arg.AiAssisted,
		arg.PromptVersion,
		arg.ModelName,
		arg.ModelVersion,
		arg.ModelProvider,
	)
	var i ChecklistSection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.GenerationID,
		&i.Role,
		&i.AiAssisted,
		&i.HumanApproved,
		&i.HumanApprover,
		&i.PromptVersion,
		&i.ModelName,
		&i.ModelVersion,
		&i.ModelProvider,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChecklistItemsBySection = `-- name: ListChecklistItemsBySection :many
SELECT id, tenant_id, section_id, control_id, task_text, citations, no_evidence, sort_order, created_at
FROM checklist_items
WHERE tenant_id = $1 AND section_id = $2
ORDER BY sort_order ASC, id ASC
`

type ListChecklistItemsBySectionParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	SectionID pgtype.UUID `json:"section_id"`
}

// The cited task items in one section, render order. Tenant-scoped.
func (q *Queries) ListChecklistItemsBySection(ctx context.Context, arg ListChecklistItemsBySectionParams) ([]ChecklistItem, error) {
	rows, err := q.db.Query(ctx, listChecklistItemsBySection, arg.TenantID, arg.SectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChecklistItem
	for rows.Next() {
		var i ChecklistItem
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SectionID,
			&i.ControlID,
			&i.TaskText,
			&i.Citations,
			&i.NoEvidence,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChecklistSectionsByGeneration = `-- name: ListChecklistSectionsByGeneration :many
SELECT id, tenant_id, generation_id, role, ai_assisted, human_approved, human_approver, prompt_version, model_name, model_version, model_provider, created_at, updated_at
FROM checklist_sections
WHERE tenant_id = $1 AND generation_id = $2
ORDER BY
    CASE role
        WHEN 'infra' THEN 0
        WHEN 'engineering' THEN 1
        WHEN 'security' THEN 2
        WHEN 'unassigned' THEN 3
        ELSE 4
    END,
    id ASC
`

type ListChecklistSectionsByGenerationParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	GenerationID pgtype.UUID `json:"generation_id"`
}

// Load all sections of one generation for the caller's tenant, role order
// stable. Powers the role-grouped review view (AC-9).
func (q *Queries) ListChecklistSectionsByGeneration(ctx context.Context, arg ListChecklistSectionsByGenerationParams) ([]ChecklistSection, error) {
	rows, err := q.db.Query(ctx, listChecklistSectionsByGeneration, arg.TenantID, arg.GenerationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChecklistSection
	for rows.Next() {
		var i ChecklistSection
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.GenerationID,
			&i.Role,
			&i.AiAssisted,
			&i.HumanApproved,
			&i.HumanApprover,
			&i.PromptVersion,
			&i.ModelName,
			&i.ModelVersion,
			&i.ModelProvider,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInScopeControlsForChecklist = `-- name: ListInScopeControlsForChecklist :many

SELECT
    c.id,
    c.title,
    c.description,
    c.owner_role,
    c.applicability_expr,
    c.scf_id,
    c.control_family,
    EXISTS (
        SELECT 1 FROM evidence_records e
        WHERE e.tenant_id = c.tenant_id AND e.control_id = c.id
    ) AS has_evidence
FROM controls c
WHERE c.tenant_id = $1
  AND c.superseded_by IS NULL
ORDER BY c.control_family ASC, c.title ASC, c.id ASC
`

type ListInScopeControlsForChecklistRow struct {
	ID                pgtype.UUID `json:"id"`
	Title             string      `json:"title"`
	Description       string      `json:"description"`
	OwnerRole         string      `json:"owner_role"`
	ApplicabilityExpr string      `json:"applicability_expr"`
	ScfID             *string     `json:"scf_id"`
	ControlFamily     string      `json:"control_family"`
	HasEvidence       bool        `json:"has_evidence"`
}

// Slice 471 — role-scoped control-implementation checklist generator v0.
//
// Queries for the deterministic role-split + the cited, non-binding checklist
// draft. Every query is tenant-bound via the leading $1 parameter
// (defense-in-depth behind the four-policy FORCE RLS on checklist_sections /
// checklist_items, invariant #6). Model output (task_text, citations) is bound
// as PARAMETERIZED values only — never interpolated (P0-498-7).
// AC-1/AC-2: the in-scope control set for a generation. Every ACTIVE
// (non-superseded) control for the caller's tenant, with the deterministic
// role-split inputs (owner_role + applicability_expr), its scf linkage (scf_id
// for the SCF-anchor citation), and a `has_evidence` flag (AC-6: a control with
// zero evidence rows is rendered as a "no evidence yet" gap, never as
// satisfied). RLS scopes the read to the tenant; the WHERE tenant_id clause is
// belt-and-suspenders. Ordered for stable rendering.
func (q *Queries) ListInScopeControlsForChecklist(ctx context.Context, tenantID pgtype.UUID) ([]ListInScopeControlsForChecklistRow, error) {
	rows, err := q.db.Query(ctx, listInScopeControlsForChecklist, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInScopeControlsForChecklistRow
	for rows.Next() {
		var i ListInScopeControlsForChecklistRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.OwnerRole,
			&i.ApplicabilityExpr,
			&i.ScfID,
			&i.ControlFamily,
			&i.HasEvidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPolicyIDsLinkedToControl = `-- name: ListPolicyIDsLinkedToControl :many
SELECT p.id
FROM policies p
WHERE p.tenant_id = $1
  AND p.linked_control_ids @> ARRAY[$2::uuid]
ORDER BY p.id ASC
`

type ListPolicyIDsLinkedToControlParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	ControlID pgtype.UUID `json:"control_id"`
}

// The policy ids linked to one control via slice-022's
// policies.linked_control_ids UUID[] array (same predicate as slice-064's
// ListPoliciesLinkedToControl). Lets the generator offer a linked-policy id as
// a citable reference for a control's tasks. Tenant-scoped.
func (q *Queries) ListPolicyIDsLinkedToControl(ctx context.Context, arg ListPolicyIDsLinkedToControlParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listPolicyIDsLinkedToControl, arg.TenantID, arg.ControlID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveChecklistControl = `-- name: ResolveChecklistControl :one
SELECT c.id
FROM controls c
WHERE c.tenant_id = $1 AND c.id = $2 AND c.superseded_by IS NULL
`

type ResolveChecklistControlParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

// Citation-resolution gate (AC-5, P0-471-2): does this id name a tenant-owned
// ACTIVE control? A cross-tenant id is RLS-invisible, so this returns no row
// (the AC-8 mechanism). Returns the control id when it resolves.
func (q *Queries) ResolveChecklistControl(ctx context.Context, arg ResolveChecklistControlParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, resolveChecklistControl, arg.TenantID, arg.ID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const resolveChecklistPolicy = `-- name: ResolveChecklistPolicy :one
SELECT p.id
FROM policies p
WHERE p.tenant_id = $1 AND p.id = $2
`

type ResolveChecklistPolicyParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

// Citation-resolution gate: does this id name a tenant-owned policy? Used when
// a generated item cites a linked policy id. Cross-tenant ids are RLS-invisible.
func (q *Queries) ResolveChecklistPolicy(ctx context.Context, arg ResolveChecklistPolicyParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, resolveChecklistPolicy, arg.TenantID, arg.ID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
