// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: control_detail.sql

package dbx

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listControlEvaluationHistoryPaged = `-- name: ListControlEvaluationHistoryPaged :many
SELECT id, evaluated_at, scope_cell_id, result,
       freshness_status, evidence_count_in_window
FROM control_evaluations
WHERE tenant_id = $1
  AND control_id = $2
  AND (
        evaluated_at < $3
        OR (evaluated_at = $3 AND id < $4)
      )
ORDER BY evaluated_at DESC, id DESC
LIMIT $5
`

type ListControlEvaluationHistoryPagedParams struct {
	TenantID  pgtype.UUID        `json:"tenant_id"`
	ControlID pgtype.UUID        `json:"control_id"`
	CursorTs  pgtype.Timestamptz `json:"cursor_ts"`
	CursorID  pgtype.UUID        `json:"cursor_id"`
	RowLimit  int32              `json:"row_limit"`
}

type ListControlEvaluationHistoryPagedRow struct {
	ID                    pgtype.UUID        `json:"id"`
	EvaluatedAt           pgtype.Timestamptz `json:"evaluated_at"`
	ScopeCellID           pgtype.UUID        `json:"scope_cell_id"`
	Result                EvidenceResult     `json:"result"`
	FreshnessStatus       string             `json:"freshness_status"`
	EvidenceCountInWindow int32              `json:"evidence_count_in_window"`
}

// AC-4: the control's evaluation history from slice 012's control_eval-
// uations append-only ledger, newest-first, keyset-paginated. The keyset
// predicate is decomposed (not a ROW(...) comparison) for the same
// sqlc-type-inference reason as ListEvidenceForControlPaged:
//
//	evaluated_at < cursor_ts OR (evaluated_at = cursor_ts AND id < cursor_id)
//
// ties on evaluated_at fall back to id; a sentinel cursor selects the
// first page. The handler computes the cutoff values in Go. This is a
// pure SELECT over the append-only ledger — no evaluation is triggered
// (constitutional invariant #2).
func (q *Queries) ListControlEvaluationHistoryPaged(ctx context.Context, arg ListControlEvaluationHistoryPagedParams) ([]ListControlEvaluationHistoryPagedRow, error) {
	rows, err := q.db.Query(ctx, listControlEvaluationHistoryPaged,
		arg.TenantID,
		arg.ControlID,
		arg.CursorTs,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListControlEvaluationHistoryPagedRow
	for rows.Next() {
		var i ListControlEvaluationHistoryPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.EvaluatedAt,
			&i.ScopeCellID,
			&i.Result,
			&i.FreshnessStatus,
			&i.EvidenceCountInWindow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvidenceForControlPaged = `-- name: ListEvidenceForControlPaged :many

SELECT id, tenant_id, control_id, control_ref, scope_id,
       observed_at, evidence_kind, provenance, hash, result
FROM evidence_records
WHERE tenant_id = $1
  AND (control_id = $2 OR control_ref = $3)
  AND observed_at >= $4
  AND observed_at <= $5
  AND (
        observed_at < $6
        OR (observed_at = $6 AND id < $7)
      )
ORDER BY observed_at DESC, id DESC
LIMIT $8
`

type ListEvidenceForControlPagedParams struct {
	TenantID     pgtype.UUID        `json:"tenant_id"`
	ControlID    pgtype.UUID        `json:"control_id"`
	ControlRef   string             `json:"control_ref"`
	ObservedAt   pgtype.Timestamptz `json:"observed_at"`
	ObservedAt_2 pgtype.Timestamptz `json:"observed_at_2"`
	CursorTs     pgtype.Timestamptz `json:"cursor_ts"`
	CursorID     pgtype.UUID        `json:"cursor_id"`
	RowLimit     int32              `json:"row_limit"`
}

type ListEvidenceForControlPagedRow struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	ControlID    pgtype.UUID        `json:"control_id"`
	ControlRef   string             `json:"control_ref"`
	ScopeID      pgtype.UUID        `json:"scope_id"`
	ObservedAt   pgtype.Timestamptz `json:"observed_at"`
	EvidenceKind *string            `json:"evidence_kind"`
	Provenance   []byte             `json:"provenance"`
	Hash         string             `json:"hash"`
	Result       EvidenceResult     `json:"result"`
}

// Slice 064 — control-detail backend read endpoints.
//
// Four pure SELECTs that surface existing data behind per-control read
// paths for the slice-041 control-detail view. This slice adds NO migration
// and NO write surface — it reads the evidence ledger, the policy library,
// risk_control_links + risks, and the control_evaluations ledger.
//
// All queries are tenant-scoped via the (tenant_id, ...) prefix; RLS is the
// defense-in-depth layer and the WHERE clauses are the primary correctness
// guarantee (canvas invariant #6). Every pagination cutoff is computed in Go
// and passed as an explicit parameter — never a single-placeholder
// expression that would trip pgx type inference (SQLSTATE 42P08).
//
// Cursor pagination over the two append-only ledgers (evidence_records,
// control_evaluations) is keyset, not OFFSET: a (timestamp, id) keyset is
// stable under concurrent appends, which OFFSET is not. The handler passes
// the decoded cursor's timestamp + id; a zero/sentinel cursor selects the
// first page. Each query fetches limit+1 rows so the handler can tell
// whether a next page exists without a second COUNT round-trip.
// AC-1: paginated evidence-ledger records resolved for one control, bounded
// by the [since, until] observed_at window. Resolution reuses slice 012's
// control->evidence path verbatim: (control_id = $2 OR control_ref = $3),
// where $3 is the UUID's string form (slice 012's loadEvidence passes
// controlRef := ctrlID.String()). The keyset predicate is decomposed
// (not a row-comparison tuple) so sqlc infers each placeholder's type
// correctly — a (observed_at, id) ROW(...) comparison mis-infers the id
// placeholder as timestamptz under sqlc v1.31. The decomposed form
//
//	observed_at < cursor_ts OR (observed_at = cursor_ts AND id < cursor_id)
//
// is the same keyset semantics: ties on observed_at fall back to id. A
// sentinel cursor (cursor_ts = 'infinity', cursor_id = max-uuid) selects
// the first page. The handler computes all cutoff values in Go.
//
// Slice 106: the SELECT projects `result` so the wire shape `evidenceWire`
// can surface it (the column has always been on evidence_records; the slice
// 064 wire shape simply omitted it).
func (q *Queries) ListEvidenceForControlPaged(ctx context.Context, arg ListEvidenceForControlPagedParams) ([]ListEvidenceForControlPagedRow, error) {
	rows, err := q.db.Query(ctx, listEvidenceForControlPaged,
		arg.TenantID,
		arg.ControlID,
		arg.ControlRef,
		arg.ObservedAt,
		arg.ObservedAt_2,
		arg.CursorTs,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEvidenceForControlPagedRow
	for rows.Next() {
		var i ListEvidenceForControlPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ControlID,
			&i.ControlRef,
			&i.ScopeID,
			&i.ObservedAt,
			&i.EvidenceKind,
			&i.Provenance,
			&i.Hash,
			&i.Result,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvidencePaged = `-- name: ListEvidencePaged :many
SELECT id, tenant_id, control_id, control_ref, scope_id,
       observed_at, evidence_kind, provenance, hash, result
FROM evidence_records
WHERE tenant_id = $1
  AND observed_at >= $2
  AND observed_at <= $3
  AND ($4::text IS NULL
       OR evidence_kind = $4::text)
  AND ($5::text IS NULL
       OR result::text = $5::text)
  AND ($6::text IS NULL
       OR source_attribution->>'actor_type' = $6::text)
  AND ($7::text IS NULL
       OR source_attribution->>'actor_id' = $7::text)
  AND ($8::uuid IS NULL
       OR scope_id = $8::uuid)
  AND (
        observed_at < $9
        OR (observed_at = $9 AND id < $10)
      )
ORDER BY observed_at DESC, id DESC
LIMIT $11
`

type ListEvidencePagedParams struct {
	TenantID        pgtype.UUID        `json:"tenant_id"`
	ObservedAt      pgtype.Timestamptz `json:"observed_at"`
	ObservedAt_2    pgtype.Timestamptz `json:"observed_at_2"`
	Kind            *string            `json:"kind"`
	ResultFilter    *string            `json:"result_filter"`
	SourceActorType *string            `json:"source_actor_type"`
	SourceActorID   *string            `json:"source_actor_id"`
	ScopeCellID     pgtype.UUID        `json:"scope_cell_id"`
	CursorTs        pgtype.Timestamptz `json:"cursor_ts"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	RowLimit        int32              `json:"row_limit"`
}

type ListEvidencePagedRow struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	ControlID    pgtype.UUID        `json:"control_id"`
	ControlRef   string             `json:"control_ref"`
	ScopeID      pgtype.UUID        `json:"scope_id"`
	ObservedAt   pgtype.Timestamptz `json:"observed_at"`
	EvidenceKind *string            `json:"evidence_kind"`
	Provenance   []byte             `json:"provenance"`
	Hash         string             `json:"hash"`
	Result       EvidenceResult     `json:"result"`
}

// Slice 106: tenant-wide evidence ledger window with optional filters. Used
// when GET /v1/evidence is called WITHOUT a control_id — returns the
// caller-tenant's whole evidence stream (RLS still scopes it on top of the
// explicit tenant_id predicate, defense-in-depth per canvas invariant #6).
//
// All five filter args are optional. The
//
//	(sqlc.narg('x')::T IS NULL OR col = sqlc.narg('x')::T)
//
// pattern is the established NULL-skip shape — see
// internal/db/queries/vendors.sql:50 — and keeps the query plan stable while
// letting sqlc emit nullable Go parameters. The source-actor filters drill
// into the JSONB source_attribution column (slice 013 enforces the
// {actor_type, actor_id, session_id} shape there).
//
// Slice 234: a fifth optional filter `scope_cell_id` narrows to one
// scope cell. Pattern mirrors slice 224's `scope_cell_id` filter on the
// anchors rollup query (`scf_anchors.sql`). Out-of-tenant cell ids return
// zero rows naturally because the row's `scope_id` is itself tenant-
// scoped — no 404 leak.
//
// Keyset pagination mirrors ListEvidenceForControlPaged exactly: same
// decomposed (observed_at, id) predicate, same +1 probe-row idiom.
// Window default (last 30 days) is still applied by the handler, not the
// query — the handler passes the resolved cutoff timestamps verbatim.
func (q *Queries) ListEvidencePaged(ctx context.Context, arg ListEvidencePagedParams) ([]ListEvidencePagedRow, error) {
	rows, err := q.db.Query(ctx, listEvidencePaged,
		arg.TenantID,
		arg.ObservedAt,
		arg.ObservedAt_2,
		arg.Kind,
		arg.ResultFilter,
		arg.SourceActorType,
		arg.SourceActorID,
		arg.ScopeCellID,
		arg.CursorTs,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEvidencePagedRow
	for rows.Next() {
		var i ListEvidencePagedRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ControlID,
			&i.ControlRef,
			&i.ScopeID,
			&i.ObservedAt,
			&i.EvidenceKind,
			&i.Provenance,
			&i.Hash,
			&i.Result,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPoliciesLinkedToControl = `-- name: ListPoliciesLinkedToControl :many
SELECT id, title, version, status
FROM policies
WHERE tenant_id = $1
  AND linked_control_ids @> ARRAY[$2::uuid]
ORDER BY created_at DESC, id ASC
`

type ListPoliciesLinkedToControlParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	ControlID pgtype.UUID `json:"control_id"`
}

type ListPoliciesLinkedToControlRow struct {
	ID      pgtype.UUID `json:"id"`
	Title   string      `json:"title"`
	Version string      `json:"version"`
	Status  string      `json:"status"`
}

// AC-2: policies linked to one control via slice 022's policies.linked_-
// control_ids UUID[] array. The array-containment predicate
// linked_control_ids @> ARRAY[sqlc.arg(control_id)::uuid] resolves the
// linkage through the existing slice-022 column — no re-derivation. The
// control id is a single named scalar arg cast to uuid inside the array
// literal; sqlc then types it as a plain pgtype.UUID (a bare $2 would be
// typed []pgtype.UUID, which pgx cannot encode as a uuid array element).
// Newest-first so the rail reads naturally; id ASC tiebreaks for stable
// ordering. The policy library is small per the canvas v1 scope, so this
// endpoint is not paginated.
func (q *Queries) ListPoliciesLinkedToControl(ctx context.Context, arg ListPoliciesLinkedToControlParams) ([]ListPoliciesLinkedToControlRow, error) {
	rows, err := q.db.Query(ctx, listPoliciesLinkedToControl, arg.TenantID, arg.ControlID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPoliciesLinkedToControlRow
	for rows.Next() {
		var i ListPoliciesLinkedToControlRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Version,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRisksLinkedToControl = `-- name: ListRisksLinkedToControl :many
SELECT r.id, r.title, r.inherent_score, r.residual_score,
       l.design_score, l.created_at
FROM risk_control_links l
JOIN risks r
  ON r.tenant_id = l.tenant_id
 AND r.id = l.risk_id
WHERE l.tenant_id = $1
  AND l.control_id = $2
ORDER BY l.created_at DESC, r.id ASC
`

type ListRisksLinkedToControlParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	ControlID pgtype.UUID `json:"control_id"`
}

type ListRisksLinkedToControlRow struct {
	ID            pgtype.UUID        `json:"id"`
	Title         string             `json:"title"`
	InherentScore []byte             `json:"inherent_score"`
	ResidualScore []byte             `json:"residual_score"`
	DesignScore   pgtype.Numeric     `json:"design_score"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

// AC-3: risks linked to one control via slice 020's risk_control_links.
// One join from the link table to risks; the per-link design_score is the
// human-set design-quality factor surfaced as link_weight (decisions log
// D7). residual_score + inherent_score are the risk's computed/authored
// JSONB, passed through. The risk register is small per canvas v1 scope,
// so this endpoint is not paginated. Newest-link-first; risk id ASC
// tiebreaks.
func (q *Queries) ListRisksLinkedToControl(ctx context.Context, arg ListRisksLinkedToControlParams) ([]ListRisksLinkedToControlRow, error) {
	rows, err := q.db.Query(ctx, listRisksLinkedToControl, arg.TenantID, arg.ControlID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRisksLinkedToControlRow
	for rows.Next() {
		var i ListRisksLinkedToControlRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.InherentScore,
			&i.ResidualScore,
			&i.DesignScore,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
