// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: decision_links.sql

package dbx

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const linkDecisionControl = `-- name: LinkDecisionControl :exec

INSERT INTO decision_controls (decision_id, target_id, tenant_id)
VALUES ($1, $2, $3)
ON CONFLICT (tenant_id, decision_id, target_id) DO NOTHING
`

type LinkDecisionControlParams struct {
	DecisionID pgtype.UUID `json:"decision_id"`
	TargetID   pgtype.UUID `json:"target_id"`
	TenantID   pgtype.UUID `json:"tenant_id"`
}

// ===== decision_controls =====
func (q *Queries) LinkDecisionControl(ctx context.Context, arg LinkDecisionControlParams) error {
	_, err := q.db.Exec(ctx, linkDecisionControl, arg.DecisionID, arg.TargetID, arg.TenantID)
	return err
}

const linkDecisionException = `-- name: LinkDecisionException :exec

INSERT INTO decision_exceptions (decision_id, target_id, tenant_id)
VALUES ($1, $2, $3)
ON CONFLICT (tenant_id, decision_id, target_id) DO NOTHING
`

type LinkDecisionExceptionParams struct {
	DecisionID pgtype.UUID `json:"decision_id"`
	TargetID   pgtype.UUID `json:"target_id"`
	TenantID   pgtype.UUID `json:"tenant_id"`
}

// ===== decision_exceptions =====
func (q *Queries) LinkDecisionException(ctx context.Context, arg LinkDecisionExceptionParams) error {
	_, err := q.db.Exec(ctx, linkDecisionException, arg.DecisionID, arg.TargetID, arg.TenantID)
	return err
}

const linkDecisionRisk = `-- name: LinkDecisionRisk :exec


INSERT INTO decision_risks (decision_id, target_id, tenant_id)
VALUES ($1, $2, $3)
ON CONFLICT (tenant_id, decision_id, target_id) DO NOTHING
`

type LinkDecisionRiskParams struct {
	DecisionID pgtype.UUID `json:"decision_id"`
	TargetID   pgtype.UUID `json:"target_id"`
	TenantID   pgtype.UUID `json:"tenant_id"`
}

// Decision Log link tables — four separate M:N tables for risks, controls,
// exceptions, and framework scope predicates (canvas §6.7). Each link is
// idempotent (ON CONFLICT DO NOTHING) so re-linking is a no-op.
// ===== decision_risks =====
func (q *Queries) LinkDecisionRisk(ctx context.Context, arg LinkDecisionRiskParams) error {
	_, err := q.db.Exec(ctx, linkDecisionRisk, arg.DecisionID, arg.TargetID, arg.TenantID)
	return err
}

const linkDecisionScopePredicate = `-- name: LinkDecisionScopePredicate :exec

INSERT INTO decision_scope_predicates (decision_id, target_id, tenant_id)
VALUES ($1, $2, $3)
ON CONFLICT (tenant_id, decision_id, target_id) DO NOTHING
`

type LinkDecisionScopePredicateParams struct {
	DecisionID pgtype.UUID `json:"decision_id"`
	TargetID   pgtype.UUID `json:"target_id"`
	TenantID   pgtype.UUID `json:"tenant_id"`
}

// ===== decision_scope_predicates =====
func (q *Queries) LinkDecisionScopePredicate(ctx context.Context, arg LinkDecisionScopePredicateParams) error {
	_, err := q.db.Exec(ctx, linkDecisionScopePredicate, arg.DecisionID, arg.TargetID, arg.TenantID)
	return err
}

const listDecisionControls = `-- name: ListDecisionControls :many
SELECT target_id, created_at
FROM decision_controls
WHERE tenant_id = $1 AND decision_id = $2
ORDER BY created_at ASC, target_id ASC
`

type ListDecisionControlsParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	DecisionID pgtype.UUID `json:"decision_id"`
}

type ListDecisionControlsRow struct {
	TargetID  pgtype.UUID        `json:"target_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListDecisionControls(ctx context.Context, arg ListDecisionControlsParams) ([]ListDecisionControlsRow, error) {
	rows, err := q.db.Query(ctx, listDecisionControls, arg.TenantID, arg.DecisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDecisionControlsRow
	for rows.Next() {
		var i ListDecisionControlsRow
		if err := rows.Scan(&i.TargetID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDecisionExceptions = `-- name: ListDecisionExceptions :many
SELECT target_id, created_at
FROM decision_exceptions
WHERE tenant_id = $1 AND decision_id = $2
ORDER BY created_at ASC, target_id ASC
`

type ListDecisionExceptionsParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	DecisionID pgtype.UUID `json:"decision_id"`
}

type ListDecisionExceptionsRow struct {
	TargetID  pgtype.UUID        `json:"target_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListDecisionExceptions(ctx context.Context, arg ListDecisionExceptionsParams) ([]ListDecisionExceptionsRow, error) {
	rows, err := q.db.Query(ctx, listDecisionExceptions, arg.TenantID, arg.DecisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDecisionExceptionsRow
	for rows.Next() {
		var i ListDecisionExceptionsRow
		if err := rows.Scan(&i.TargetID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDecisionRisks = `-- name: ListDecisionRisks :many
SELECT target_id, created_at
FROM decision_risks
WHERE tenant_id = $1 AND decision_id = $2
ORDER BY created_at ASC, target_id ASC
`

type ListDecisionRisksParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	DecisionID pgtype.UUID `json:"decision_id"`
}

type ListDecisionRisksRow struct {
	TargetID  pgtype.UUID        `json:"target_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListDecisionRisks(ctx context.Context, arg ListDecisionRisksParams) ([]ListDecisionRisksRow, error) {
	rows, err := q.db.Query(ctx, listDecisionRisks, arg.TenantID, arg.DecisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDecisionRisksRow
	for rows.Next() {
		var i ListDecisionRisksRow
		if err := rows.Scan(&i.TargetID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDecisionScopePredicates = `-- name: ListDecisionScopePredicates :many
SELECT target_id, created_at
FROM decision_scope_predicates
WHERE tenant_id = $1 AND decision_id = $2
ORDER BY created_at ASC, target_id ASC
`

type ListDecisionScopePredicatesParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	DecisionID pgtype.UUID `json:"decision_id"`
}

type ListDecisionScopePredicatesRow struct {
	TargetID  pgtype.UUID        `json:"target_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListDecisionScopePredicates(ctx context.Context, arg ListDecisionScopePredicatesParams) ([]ListDecisionScopePredicatesRow, error) {
	rows, err := q.db.Query(ctx, listDecisionScopePredicates, arg.TenantID, arg.DecisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDecisionScopePredicatesRow
	for rows.Next() {
		var i ListDecisionScopePredicatesRow
		if err := rows.Scan(&i.TargetID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDecisionsForControl = `-- name: ListDecisionsForControl :many
SELECT decision_id, created_at
FROM decision_controls
WHERE tenant_id = $1 AND target_id = $2
ORDER BY created_at ASC, decision_id ASC
`

type ListDecisionsForControlParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	TargetID pgtype.UUID `json:"target_id"`
}

type ListDecisionsForControlRow struct {
	DecisionID pgtype.UUID        `json:"decision_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListDecisionsForControl(ctx context.Context, arg ListDecisionsForControlParams) ([]ListDecisionsForControlRow, error) {
	rows, err := q.db.Query(ctx, listDecisionsForControl, arg.TenantID, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDecisionsForControlRow
	for rows.Next() {
		var i ListDecisionsForControlRow
		if err := rows.Scan(&i.DecisionID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDecisionsForException = `-- name: ListDecisionsForException :many
SELECT decision_id, created_at
FROM decision_exceptions
WHERE tenant_id = $1 AND target_id = $2
ORDER BY created_at ASC, decision_id ASC
`

type ListDecisionsForExceptionParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	TargetID pgtype.UUID `json:"target_id"`
}

type ListDecisionsForExceptionRow struct {
	DecisionID pgtype.UUID        `json:"decision_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListDecisionsForException(ctx context.Context, arg ListDecisionsForExceptionParams) ([]ListDecisionsForExceptionRow, error) {
	rows, err := q.db.Query(ctx, listDecisionsForException, arg.TenantID, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDecisionsForExceptionRow
	for rows.Next() {
		var i ListDecisionsForExceptionRow
		if err := rows.Scan(&i.DecisionID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDecisionsForRisk = `-- name: ListDecisionsForRisk :many
SELECT decision_id, created_at
FROM decision_risks
WHERE tenant_id = $1 AND target_id = $2
ORDER BY created_at ASC, decision_id ASC
`

type ListDecisionsForRiskParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	TargetID pgtype.UUID `json:"target_id"`
}

type ListDecisionsForRiskRow struct {
	DecisionID pgtype.UUID        `json:"decision_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListDecisionsForRisk(ctx context.Context, arg ListDecisionsForRiskParams) ([]ListDecisionsForRiskRow, error) {
	rows, err := q.db.Query(ctx, listDecisionsForRisk, arg.TenantID, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDecisionsForRiskRow
	for rows.Next() {
		var i ListDecisionsForRiskRow
		if err := rows.Scan(&i.DecisionID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkDecisionControl = `-- name: UnlinkDecisionControl :exec
DELETE FROM decision_controls
WHERE tenant_id = $1 AND decision_id = $2 AND target_id = $3
`

type UnlinkDecisionControlParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	DecisionID pgtype.UUID `json:"decision_id"`
	TargetID   pgtype.UUID `json:"target_id"`
}

func (q *Queries) UnlinkDecisionControl(ctx context.Context, arg UnlinkDecisionControlParams) error {
	_, err := q.db.Exec(ctx, unlinkDecisionControl, arg.TenantID, arg.DecisionID, arg.TargetID)
	return err
}

const unlinkDecisionException = `-- name: UnlinkDecisionException :exec
DELETE FROM decision_exceptions
WHERE tenant_id = $1 AND decision_id = $2 AND target_id = $3
`

type UnlinkDecisionExceptionParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	DecisionID pgtype.UUID `json:"decision_id"`
	TargetID   pgtype.UUID `json:"target_id"`
}

func (q *Queries) UnlinkDecisionException(ctx context.Context, arg UnlinkDecisionExceptionParams) error {
	_, err := q.db.Exec(ctx, unlinkDecisionException, arg.TenantID, arg.DecisionID, arg.TargetID)
	return err
}

const unlinkDecisionRisk = `-- name: UnlinkDecisionRisk :exec
DELETE FROM decision_risks
WHERE tenant_id = $1 AND decision_id = $2 AND target_id = $3
`

type UnlinkDecisionRiskParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	DecisionID pgtype.UUID `json:"decision_id"`
	TargetID   pgtype.UUID `json:"target_id"`
}

func (q *Queries) UnlinkDecisionRisk(ctx context.Context, arg UnlinkDecisionRiskParams) error {
	_, err := q.db.Exec(ctx, unlinkDecisionRisk, arg.TenantID, arg.DecisionID, arg.TargetID)
	return err
}

const unlinkDecisionScopePredicate = `-- name: UnlinkDecisionScopePredicate :exec
DELETE FROM decision_scope_predicates
WHERE tenant_id = $1 AND decision_id = $2 AND target_id = $3
`

type UnlinkDecisionScopePredicateParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	DecisionID pgtype.UUID `json:"decision_id"`
	TargetID   pgtype.UUID `json:"target_id"`
}

func (q *Queries) UnlinkDecisionScopePredicate(ctx context.Context, arg UnlinkDecisionScopePredicateParams) error {
	_, err := q.db.Exec(ctx, unlinkDecisionScopePredicate, arg.TenantID, arg.DecisionID, arg.TargetID)
	return err
}
