// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: decisions_audit.sql

package dbx

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDecisionOverdueNotifications = `-- name: CountDecisionOverdueNotifications :one
SELECT count(*) AS notified_count
FROM decisions_audit
WHERE tenant_id = $1
  AND decision_id = $2
  AND action = 'overdue_notified'
`

type CountDecisionOverdueNotificationsParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	DecisionID pgtype.UUID `json:"decision_id"`
}

// Slice 055 overdue-job dedup probe: has this decision already had an
// `overdue_notified` audit row written? A non-zero count means the daily
// job already notified the decision_maker -- skip re-emission (P0
// anti-criterion: one notification per overdue decision, never repeated).
// Served index-only by idx_decisions_audit_overdue_notified.
func (q *Queries) CountDecisionOverdueNotifications(ctx context.Context, arg CountDecisionOverdueNotificationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDecisionOverdueNotifications, arg.TenantID, arg.DecisionID)
	var notified_count int64
	err := row.Scan(&notified_count)
	return notified_count, err
}

const listDecisionAudit = `-- name: ListDecisionAudit :many
SELECT id, tenant_id, decision_id, action, actor, detail, occurred_at
FROM decisions_audit
WHERE tenant_id = $1 AND decision_id = $2
ORDER BY occurred_at ASC, id ASC
`

type ListDecisionAuditParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	DecisionID pgtype.UUID `json:"decision_id"`
}

// The audit trail for a single decision, oldest first. Powers the
// decision-detail audit-log rail.
func (q *Queries) ListDecisionAudit(ctx context.Context, arg ListDecisionAuditParams) ([]DecisionsAudit, error) {
	rows, err := q.db.Query(ctx, listDecisionAudit, arg.TenantID, arg.DecisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DecisionsAudit
	for rows.Next() {
		var i DecisionsAudit
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DecisionID,
			&i.Action,
			&i.Actor,
			&i.Detail,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const writeDecisionAudit = `-- name: WriteDecisionAudit :one

INSERT INTO decisions_audit (
    id, tenant_id, decision_id, action, actor, detail
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, decision_id, action, actor, detail, occurred_at
`

type WriteDecisionAuditParams struct {
	ID         pgtype.UUID `json:"id"`
	TenantID   pgtype.UUID `json:"tenant_id"`
	DecisionID pgtype.UUID `json:"decision_id"`
	Action     string      `json:"action"`
	Actor      string      `json:"actor"`
	Detail     string      `json:"detail"`
}

// Decision Log audit log (slice 055, migration _030).
//
// decisions_audit is an append-only mutation log: every PATCH, supersede,
// link add/remove, denied cross-tenant link attempt, and overdue-notification
// emission writes one row. There is no UPDATE or DELETE query -- the table
// has no UPDATE/DELETE RLS policy and atlas_app has no UPDATE/DELETE grant,
// so an UPDATE/DELETE query would fail at runtime anyway. Append-only by
// construction.
//
// All queries are tenant-scoped via the leading (tenant_id, ...); RLS under
// FORCE keeps the cross-tenant boundary safe even on a misconfigured query.
// Append one audit row. `action` is one of the decisions_audit_action_chk
// enum values; `detail` is free-form context (a diff, a link target id, a
// replacement decision id, a notification recipient, etc.).
func (q *Queries) WriteDecisionAudit(ctx context.Context, arg WriteDecisionAuditParams) (DecisionsAudit, error) {
	row := q.db.QueryRow(ctx, writeDecisionAudit,
		arg.ID,
		arg.TenantID,
		arg.DecisionID,
		arg.Action,
		arg.Actor,
		arg.Detail,
	)
	var i DecisionsAudit
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DecisionID,
		&i.Action,
		&i.Actor,
		&i.Detail,
		&i.OccurredAt,
	)
	return i, err
}
