// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: decisions.sql

package dbx

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDecision = `-- name: CreateDecision :one
INSERT INTO decisions (
    id, tenant_id, decision_id, title, narrative, constraints,
    tradeoffs, decision_maker, decided_at, revisit_by, status, superseded_by
)
VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12
)
RETURNING id, tenant_id, decision_id, title, narrative, constraints, tradeoffs, decision_maker, decided_at, revisit_by, status, superseded_by, created_at, updated_at
`

type CreateDecisionParams struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	DecisionID    string             `json:"decision_id"`
	Title         string             `json:"title"`
	Narrative     string             `json:"narrative"`
	Constraints   []string           `json:"constraints"`
	Tradeoffs     string             `json:"tradeoffs"`
	DecisionMaker string             `json:"decision_maker"`
	DecidedAt     pgtype.Timestamptz `json:"decided_at"`
	RevisitBy     pgtype.Date        `json:"revisit_by"`
	Status        DecisionStatus     `json:"status"`
	SupersededBy  pgtype.UUID        `json:"superseded_by"`
}

// Insert a new Decision Log entry (canvas §6.7). Slice 052 ships the table
// + queries; slice 055 adds the HTTP CRUD surface. decision_id is the
// tenant-visible identifier ("DL-2026-04-12"); the application generates it.
func (q *Queries) CreateDecision(ctx context.Context, arg CreateDecisionParams) (Decision, error) {
	row := q.db.QueryRow(ctx, createDecision,
		arg.ID,
		arg.TenantID,
		arg.DecisionID,
		arg.Title,
		arg.Narrative,
		arg.Constraints,
		arg.Tradeoffs,
		arg.DecisionMaker,
		arg.DecidedAt,
		arg.RevisitBy,
		arg.Status,
		arg.SupersededBy,
	)
	var i Decision
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DecisionID,
		&i.Title,
		&i.Narrative,
		&i.Constraints,
		&i.Tradeoffs,
		&i.DecisionMaker,
		&i.DecidedAt,
		&i.RevisitBy,
		&i.Status,
		&i.SupersededBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDecision = `-- name: DeleteDecision :exec
DELETE FROM decisions
WHERE tenant_id = $1 AND id = $2
`

type DeleteDecisionParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteDecision(ctx context.Context, arg DeleteDecisionParams) error {
	_, err := q.db.Exec(ctx, deleteDecision, arg.TenantID, arg.ID)
	return err
}

const getDecisionByDecisionID = `-- name: GetDecisionByDecisionID :one
SELECT id, tenant_id, decision_id, title, narrative, constraints, tradeoffs, decision_maker, decided_at, revisit_by, status, superseded_by, created_at, updated_at
FROM decisions
WHERE tenant_id = $1 AND decision_id = $2
`

type GetDecisionByDecisionIDParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	DecisionID string      `json:"decision_id"`
}

// Lookup by the human-readable decision_id ("DL-2026-04-12"). Unique within
// tenant (UNIQUE (tenant_id, decision_id)).
func (q *Queries) GetDecisionByDecisionID(ctx context.Context, arg GetDecisionByDecisionIDParams) (Decision, error) {
	row := q.db.QueryRow(ctx, getDecisionByDecisionID, arg.TenantID, arg.DecisionID)
	var i Decision
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DecisionID,
		&i.Title,
		&i.Narrative,
		&i.Constraints,
		&i.Tradeoffs,
		&i.DecisionMaker,
		&i.DecidedAt,
		&i.RevisitBy,
		&i.Status,
		&i.SupersededBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDecisionByID = `-- name: GetDecisionByID :one
SELECT id, tenant_id, decision_id, title, narrative, constraints, tradeoffs, decision_maker, decided_at, revisit_by, status, superseded_by, created_at, updated_at
FROM decisions
WHERE tenant_id = $1 AND id = $2
`

type GetDecisionByIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetDecisionByID(ctx context.Context, arg GetDecisionByIDParams) (Decision, error) {
	row := q.db.QueryRow(ctx, getDecisionByID, arg.TenantID, arg.ID)
	var i Decision
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DecisionID,
		&i.Title,
		&i.Narrative,
		&i.Constraints,
		&i.Tradeoffs,
		&i.DecisionMaker,
		&i.DecidedAt,
		&i.RevisitBy,
		&i.Status,
		&i.SupersededBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDecisions = `-- name: ListDecisions :many
SELECT id, tenant_id, decision_id, title, narrative, constraints, tradeoffs, decision_maker, decided_at, revisit_by, status, superseded_by, created_at, updated_at
FROM decisions
WHERE tenant_id = $1
ORDER BY decided_at DESC, id ASC
`

func (q *Queries) ListDecisions(ctx context.Context, tenantID pgtype.UUID) ([]Decision, error) {
	rows, err := q.db.Query(ctx, listDecisions, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Decision
	for rows.Next() {
		var i Decision
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DecisionID,
			&i.Title,
			&i.Narrative,
			&i.Constraints,
			&i.Tradeoffs,
			&i.DecisionMaker,
			&i.DecidedAt,
			&i.RevisitBy,
			&i.Status,
			&i.SupersededBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDecisionsByStatus = `-- name: ListDecisionsByStatus :many
SELECT id, tenant_id, decision_id, title, narrative, constraints, tradeoffs, decision_maker, decided_at, revisit_by, status, superseded_by, created_at, updated_at
FROM decisions
WHERE tenant_id = $1 AND status = $2
ORDER BY decided_at DESC, id ASC
`

type ListDecisionsByStatusParams struct {
	TenantID pgtype.UUID    `json:"tenant_id"`
	Status   DecisionStatus `json:"status"`
}

func (q *Queries) ListDecisionsByStatus(ctx context.Context, arg ListDecisionsByStatusParams) ([]Decision, error) {
	rows, err := q.db.Query(ctx, listDecisionsByStatus, arg.TenantID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Decision
	for rows.Next() {
		var i Decision
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DecisionID,
			&i.Title,
			&i.Narrative,
			&i.Constraints,
			&i.Tradeoffs,
			&i.DecisionMaker,
			&i.DecidedAt,
			&i.RevisitBy,
			&i.Status,
			&i.SupersededBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDecisionsDueForRevisit = `-- name: ListDecisionsDueForRevisit :many
SELECT id, tenant_id, decision_id, title, narrative, constraints, tradeoffs, decision_maker, decided_at, revisit_by, status, superseded_by, created_at, updated_at
FROM decisions
WHERE tenant_id = $1
  AND status = 'active'
  AND revisit_by IS NOT NULL
  AND revisit_by <= $2
ORDER BY revisit_by ASC, id ASC
`

type ListDecisionsDueForRevisitParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	RevisitBy pgtype.Date `json:"revisit_by"`
}

// Decisions with revisit_by ≤ the cutoff. Slice 055's dashboard panel uses
// this to surface "decisions due to revisit in the next N days".
func (q *Queries) ListDecisionsDueForRevisit(ctx context.Context, arg ListDecisionsDueForRevisitParams) ([]Decision, error) {
	rows, err := q.db.Query(ctx, listDecisionsDueForRevisit, arg.TenantID, arg.RevisitBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Decision
	for rows.Next() {
		var i Decision
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DecisionID,
			&i.Title,
			&i.Narrative,
			&i.Constraints,
			&i.Tradeoffs,
			&i.DecisionMaker,
			&i.DecidedAt,
			&i.RevisitBy,
			&i.Status,
			&i.SupersededBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDecision = `-- name: UpdateDecision :one
UPDATE decisions
SET title = $3,
    narrative = $4,
    constraints = $5,
    tradeoffs = $6,
    decision_maker = $7,
    decided_at = $8,
    revisit_by = $9,
    status = $10,
    superseded_by = $11,
    updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, decision_id, title, narrative, constraints, tradeoffs, decision_maker, decided_at, revisit_by, status, superseded_by, created_at, updated_at
`

type UpdateDecisionParams struct {
	TenantID      pgtype.UUID        `json:"tenant_id"`
	ID            pgtype.UUID        `json:"id"`
	Title         string             `json:"title"`
	Narrative     string             `json:"narrative"`
	Constraints   []string           `json:"constraints"`
	Tradeoffs     string             `json:"tradeoffs"`
	DecisionMaker string             `json:"decision_maker"`
	DecidedAt     pgtype.Timestamptz `json:"decided_at"`
	RevisitBy     pgtype.Date        `json:"revisit_by"`
	Status        DecisionStatus     `json:"status"`
	SupersededBy  pgtype.UUID        `json:"superseded_by"`
}

func (q *Queries) UpdateDecision(ctx context.Context, arg UpdateDecisionParams) (Decision, error) {
	row := q.db.QueryRow(ctx, updateDecision,
		arg.TenantID,
		arg.ID,
		arg.Title,
		arg.Narrative,
		arg.Constraints,
		arg.Tradeoffs,
		arg.DecisionMaker,
		arg.DecidedAt,
		arg.RevisitBy,
		arg.Status,
		arg.SupersededBy,
	)
	var i Decision
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DecisionID,
		&i.Title,
		&i.Narrative,
		&i.Constraints,
		&i.Tradeoffs,
		&i.DecisionMaker,
		&i.DecidedAt,
		&i.RevisitBy,
		&i.Status,
		&i.SupersededBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
