// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: evidence_freshness_drift.sql

package dbx

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEvidenceFreshnessByControl = `-- name: GetEvidenceFreshnessByControl :one
SELECT id, tenant_id, control_id, freshness_class, latest_observed_at, valid_until, is_stale, evidence_count, refreshed_at, created_at
FROM evidence_freshness
WHERE tenant_id = $1
  AND control_id = $2
`

type GetEvidenceFreshnessByControlParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	ControlID pgtype.UUID `json:"control_id"`
}

// Single-control freshness lookup — used by tests and by future per-control
// detail surfaces.
func (q *Queries) GetEvidenceFreshnessByControl(ctx context.Context, arg GetEvidenceFreshnessByControlParams) (EvidenceFreshness, error) {
	row := q.db.QueryRow(ctx, getEvidenceFreshnessByControl, arg.TenantID, arg.ControlID)
	var i EvidenceFreshness
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ControlID,
		&i.FreshnessClass,
		&i.LatestObservedAt,
		&i.ValidUntil,
		&i.IsStale,
		&i.EvidenceCount,
		&i.RefreshedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestDriftSnapshotForDay = `-- name: GetLatestDriftSnapshotForDay :one
SELECT id, tenant_id, snapshot_date, controls_passing, passing_control_ids, captured_at, trigger, created_at
FROM control_drift_snapshots
WHERE tenant_id = $1
  AND snapshot_date = $2
ORDER BY captured_at DESC
LIMIT 1
`

type GetLatestDriftSnapshotForDayParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	SnapshotDate pgtype.Date `json:"snapshot_date"`
}

// The latest snapshot for one specific calendar day — used by the on-ingest
// refresh to decide whether today already has a snapshot, and by tests.
func (q *Queries) GetLatestDriftSnapshotForDay(ctx context.Context, arg GetLatestDriftSnapshotForDayParams) (ControlDriftSnapshot, error) {
	row := q.db.QueryRow(ctx, getLatestDriftSnapshotForDay, arg.TenantID, arg.SnapshotDate)
	var i ControlDriftSnapshot
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SnapshotDate,
		&i.ControlsPassing,
		&i.PassingControlIds,
		&i.CapturedAt,
		&i.Trigger,
		&i.CreatedAt,
	)
	return i, err
}

const insertDriftSnapshot = `-- name: InsertDriftSnapshot :one
INSERT INTO control_drift_snapshots (
    id, tenant_id, snapshot_date,
    controls_passing, passing_control_ids, trigger
) VALUES (
    $1, $2, $3,
    $4, $5, $6
)
RETURNING id, tenant_id, snapshot_date, controls_passing, passing_control_ids, captured_at, trigger, created_at
`

type InsertDriftSnapshotParams struct {
	ID                pgtype.UUID   `json:"id"`
	TenantID          pgtype.UUID   `json:"tenant_id"`
	SnapshotDate      pgtype.Date   `json:"snapshot_date"`
	ControlsPassing   int32         `json:"controls_passing"`
	PassingControlIds []pgtype.UUID `json:"passing_control_ids"`
	Trigger           string        `json:"trigger"`
}

// The drift refresh write: APPEND one snapshot row. The table is append-only
// (no UPDATE/DELETE RLS policy) — every refresh, scheduled or on-ingest,
// appends a fresh row; the read path takes the latest row per
// (tenant_id, snapshot_date). controls_passing and passing_control_ids are
// both computed in Go from ListPassingControlsForDay and MUST agree (CHECK
// constraint control_drift_snapshots_count_matches_set).
func (q *Queries) InsertDriftSnapshot(ctx context.Context, arg InsertDriftSnapshotParams) (ControlDriftSnapshot, error) {
	row := q.db.QueryRow(ctx, insertDriftSnapshot,
		arg.ID,
		arg.TenantID,
		arg.SnapshotDate,
		arg.ControlsPassing,
		arg.PassingControlIds,
		arg.Trigger,
	)
	var i ControlDriftSnapshot
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SnapshotDate,
		&i.ControlsPassing,
		&i.PassingControlIds,
		&i.CapturedAt,
		&i.Trigger,
		&i.CreatedAt,
	)
	return i, err
}

const listControlsWithLatestEvidence = `-- name: ListControlsWithLatestEvidence :many


SELECT
    c.id                              AS control_id,
    c.freshness_class                 AS freshness_class,
    max(e.observed_at)::timestamptz   AS latest_observed_at,
    count(e.id)                       AS evidence_count
FROM controls c
LEFT JOIN evidence_records e
    ON e.tenant_id = c.tenant_id
   AND (e.control_id = c.id OR e.control_ref = c.id::text)
WHERE c.tenant_id = $1
  AND c.superseded_by IS NULL
GROUP BY c.id, c.freshness_class
`

type ListControlsWithLatestEvidenceRow struct {
	ControlID        pgtype.UUID        `json:"control_id"`
	FreshnessClass   *string            `json:"freshness_class"`
	LatestObservedAt pgtype.Timestamptz `json:"latest_observed_at"`
	EvidenceCount    int64              `json:"evidence_count"`
}

// Slice 016 — evidence freshness read-model + control drift snapshot queries.
//
// `evidence_freshness` is a materialized current-state read model (one row per
// (tenant_id, control_id), UPSERTed on refresh). `control_drift_snapshots` is
// an append-only daily snapshot ledger (every refresh APPENDS; latest row per
// (tenant_id, snapshot_date) wins). Both are DERIVED purely from the immutable
// ledgers (`evidence_records`, `control_evaluations`) — slice 016 never writes
// the ledgers (constitutional invariant #2).
//
// All queries are tenant-scoped via the (tenant_id, ...) prefix; RLS is the
// defense-in-depth layer and the WHERE clauses are the primary correctness
// guarantee (canvas invariant #6). Every timestamp / date cutoff is computed
// in Go and passed as an explicit parameter — never a single-placeholder
// expression that would trip pgx type inference (SQLSTATE 42P08).
// ===== evidence_freshness =====
// The freshness refresh input: every active (non-superseded) control for the
// tenant, joined to its evidence ledger aggregate (freshest observed_at +
// record count). LEFT JOIN so a control with zero evidence still produces a
// row (latest_observed_at NULL, evidence_count 0). The evidence join matches
// BOTH the UUID control_id path and the free-form control_ref path (slice
// 013), so evidence pushed under an SCF-anchor string is still counted.
func (q *Queries) ListControlsWithLatestEvidence(ctx context.Context, tenantID pgtype.UUID) ([]ListControlsWithLatestEvidenceRow, error) {
	rows, err := q.db.Query(ctx, listControlsWithLatestEvidence, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListControlsWithLatestEvidenceRow
	for rows.Next() {
		var i ListControlsWithLatestEvidenceRow
		if err := rows.Scan(
			&i.ControlID,
			&i.FreshnessClass,
			&i.LatestObservedAt,
			&i.EvidenceCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvidenceFreshness = `-- name: ListEvidenceFreshness :many
SELECT id, tenant_id, control_id, freshness_class, latest_observed_at, valid_until, is_stale, evidence_count, refreshed_at, created_at
FROM evidence_freshness
WHERE tenant_id = $1
ORDER BY freshness_class NULLS LAST, control_id
`

// AC-1 / AC-2 read: every freshness row for the tenant. The handler buckets
// by freshness_class and counts is_stale in Go — a flat list keeps the query
// single-purpose and lets the handler shape both the ?bucket=class
// distribution and the per-class stale counts from one read.
func (q *Queries) ListEvidenceFreshness(ctx context.Context, tenantID pgtype.UUID) ([]EvidenceFreshness, error) {
	rows, err := q.db.Query(ctx, listEvidenceFreshness, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EvidenceFreshness
	for rows.Next() {
		var i EvidenceFreshness
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ControlID,
			&i.FreshnessClass,
			&i.LatestObservedAt,
			&i.ValidUntil,
			&i.IsStale,
			&i.EvidenceCount,
			&i.RefreshedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestDriftSnapshotsSince = `-- name: ListLatestDriftSnapshotsSince :many
SELECT DISTINCT ON (snapshot_date) id, tenant_id, snapshot_date, controls_passing, passing_control_ids, captured_at, trigger, created_at
FROM control_drift_snapshots
WHERE tenant_id = $1
  AND snapshot_date >= $2
ORDER BY snapshot_date DESC, captured_at DESC
`

type ListLatestDriftSnapshotsSinceParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	SnapshotDate pgtype.Date `json:"snapshot_date"`
}

// AC-3 read: the latest snapshot per calendar day for the tenant, for every
// day from `since_date` through today. DISTINCT ON (snapshot_date) collapses
// the append-only intra-day refresh trail to the authoritative latest row per
// day. The handler diffs consecutive days' passing_control_ids to derive the
// signed delta and the flipped-to-fail control set. `since_date` is computed
// in Go (today - N days) and passed explicitly.
func (q *Queries) ListLatestDriftSnapshotsSince(ctx context.Context, arg ListLatestDriftSnapshotsSinceParams) ([]ControlDriftSnapshot, error) {
	rows, err := q.db.Query(ctx, listLatestDriftSnapshotsSince, arg.TenantID, arg.SnapshotDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlDriftSnapshot
	for rows.Next() {
		var i ControlDriftSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SnapshotDate,
			&i.ControlsPassing,
			&i.PassingControlIds,
			&i.CapturedAt,
			&i.Trigger,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPassingControlsForDay = `-- name: ListPassingControlsForDay :many

WITH latest_per_cell AS (
    SELECT DISTINCT ON (control_id, scope_cell_id)
        control_id,
        scope_cell_id,
        result,
        freshness_status
    FROM control_evaluations
    WHERE tenant_id = $1
      AND evaluated_at <= $2
    ORDER BY control_id, scope_cell_id, evaluated_at DESC, created_at DESC
)
SELECT control_id
FROM latest_per_cell
GROUP BY control_id
HAVING bool_and(result = 'pass' AND freshness_status = 'fresh')
`

type ListPassingControlsForDayParams struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	EvaluatedAt pgtype.Timestamptz `json:"evaluated_at"`
}

// ===== control_drift_snapshots =====
// The drift snapshot input: for one tenant, the set of controls "passing" as
// of `as_of` under the worst-cell rollup. A control passes iff EVERY
// applicable (control, scope_cell) tuple's LATEST evaluation at or before
// `as_of` has result='pass' AND freshness_status='fresh'. Stale evidence does
// NOT count as passing (canvas §2.3: stale evidence drives the drift signal).
//
// The inner DISTINCT ON collapses the append-only control_evaluations ledger
// to the latest row per (control_id, scope_cell_id). The outer aggregate
// keeps a control only when NO cell is non-(pass+fresh): bool_and over the
// per-cell pass+fresh predicate.
func (q *Queries) ListPassingControlsForDay(ctx context.Context, arg ListPassingControlsForDayParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listPassingControlsForDay, arg.TenantID, arg.EvaluatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var control_id pgtype.UUID
		if err := rows.Scan(&control_id); err != nil {
			return nil, err
		}
		items = append(items, control_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEvidenceFreshness = `-- name: UpsertEvidenceFreshness :one
INSERT INTO evidence_freshness (
    id, tenant_id, control_id, freshness_class,
    latest_observed_at, valid_until, is_stale, evidence_count, refreshed_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9
)
ON CONFLICT (tenant_id, control_id) DO UPDATE SET
    freshness_class    = EXCLUDED.freshness_class,
    latest_observed_at = EXCLUDED.latest_observed_at,
    valid_until        = EXCLUDED.valid_until,
    is_stale           = EXCLUDED.is_stale,
    evidence_count     = EXCLUDED.evidence_count,
    refreshed_at       = EXCLUDED.refreshed_at
RETURNING id, tenant_id, control_id, freshness_class, latest_observed_at, valid_until, is_stale, evidence_count, refreshed_at, created_at
`

type UpsertEvidenceFreshnessParams struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	ControlID        pgtype.UUID        `json:"control_id"`
	FreshnessClass   *string            `json:"freshness_class"`
	LatestObservedAt pgtype.Timestamptz `json:"latest_observed_at"`
	ValidUntil       pgtype.Timestamptz `json:"valid_until"`
	IsStale          bool               `json:"is_stale"`
	EvidenceCount    int32              `json:"evidence_count"`
	RefreshedAt      pgtype.Timestamptz `json:"refreshed_at"`
}

// The freshness refresh write: UPSERT one control's freshness row onto the
// (tenant_id, control_id) unique key. valid_until and is_stale are computed
// in Go (Go owns the canvas §2.3 class -> max-age mapping via
// internal/eval.FreshnessMaxAge — never re-derived in SQL). On conflict every
// derived column is refreshed.
func (q *Queries) UpsertEvidenceFreshness(ctx context.Context, arg UpsertEvidenceFreshnessParams) (EvidenceFreshness, error) {
	row := q.db.QueryRow(ctx, upsertEvidenceFreshness,
		arg.ID,
		arg.TenantID,
		arg.ControlID,
		arg.FreshnessClass,
		arg.LatestObservedAt,
		arg.ValidUntil,
		arg.IsStale,
		arg.EvidenceCount,
		arg.RefreshedAt,
	)
	var i EvidenceFreshness
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ControlID,
		&i.FreshnessClass,
		&i.LatestObservedAt,
		&i.ValidUntil,
		&i.IsStale,
		&i.EvidenceCount,
		&i.RefreshedAt,
		&i.CreatedAt,
	)
	return i, err
}
