// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: framework_scopes.sql

package dbx

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateFrameworkScope = `-- name: ActivateFrameworkScope :one
UPDATE framework_scopes
SET state = 'activated',
    effective_from = $3,
    updated_at = now()
WHERE tenant_id = $1 AND id = $2 AND state = 'approved'
RETURNING id, tenant_id, framework_version_id, name, created_at, updated_at, state, predicate, predicate_hash, approver_user_id, approved_at, predicate_hash_at_approval, approval_evidence_file_url, approval_evidence_file_hash, effective_from, superseded_by, superseded_at
`

type ActivateFrameworkScopeParams struct {
	TenantID      pgtype.UUID        `json:"tenant_id"`
	ID            pgtype.UUID        `json:"id"`
	EffectiveFrom pgtype.Timestamptz `json:"effective_from"`
}

// AC-8: approved -> activated. The caller must supply effective_from
// (timestamptz). The application supersedes the prior `activated` row in
// the same transaction by calling SupersedePreviousActivated below; both
// statements run inside one tx so the partial unique index never sees
// two `activated` rows at once.
func (q *Queries) ActivateFrameworkScope(ctx context.Context, arg ActivateFrameworkScopeParams) (FrameworkScope, error) {
	row := q.db.QueryRow(ctx, activateFrameworkScope, arg.TenantID, arg.ID, arg.EffectiveFrom)
	var i FrameworkScope
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FrameworkVersionID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.State,
		&i.Predicate,
		&i.PredicateHash,
		&i.ApproverUserID,
		&i.ApprovedAt,
		&i.PredicateHashAtApproval,
		&i.ApprovalEvidenceFileUrl,
		&i.ApprovalEvidenceFileHash,
		&i.EffectiveFrom,
		&i.SupersededBy,
		&i.SupersededAt,
	)
	return i, err
}

const approveFrameworkScope = `-- name: ApproveFrameworkScope :one
UPDATE framework_scopes
SET state = 'approved',
    approver_user_id = $3,
    approved_at = now(),
    predicate_hash_at_approval = predicate_hash,
    approval_evidence_file_url = $4,
    approval_evidence_file_hash = $5,
    updated_at = now()
WHERE tenant_id = $1 AND id = $2 AND state = 'review'
RETURNING id, tenant_id, framework_version_id, name, created_at, updated_at, state, predicate, predicate_hash, approver_user_id, approved_at, predicate_hash_at_approval, approval_evidence_file_url, approval_evidence_file_hash, effective_from, superseded_by, superseded_at
`

type ApproveFrameworkScopeParams struct {
	TenantID                 pgtype.UUID `json:"tenant_id"`
	ID                       pgtype.UUID `json:"id"`
	ApproverUserID           pgtype.UUID `json:"approver_user_id"`
	ApprovalEvidenceFileUrl  *string     `json:"approval_evidence_file_url"`
	ApprovalEvidenceFileHash *string     `json:"approval_evidence_file_hash"`
}

// AC-7: review -> approved. Records approver_user_id, approved_at, and the
// predicate_hash captured at this moment so a later predicate edit can prove
// "the approval was for THIS text, not the current text" (ADR-0001 §positive).
// Optional approval-evidence file URL + hash are passed by the handler.
func (q *Queries) ApproveFrameworkScope(ctx context.Context, arg ApproveFrameworkScopeParams) (FrameworkScope, error) {
	row := q.db.QueryRow(ctx, approveFrameworkScope,
		arg.TenantID,
		arg.ID,
		arg.ApproverUserID,
		arg.ApprovalEvidenceFileUrl,
		arg.ApprovalEvidenceFileHash,
	)
	var i FrameworkScope
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FrameworkVersionID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.State,
		&i.Predicate,
		&i.PredicateHash,
		&i.ApproverUserID,
		&i.ApprovedAt,
		&i.PredicateHashAtApproval,
		&i.ApprovalEvidenceFileUrl,
		&i.ApprovalEvidenceFileHash,
		&i.EffectiveFrom,
		&i.SupersededBy,
		&i.SupersededAt,
	)
	return i, err
}

const createFrameworkScope = `-- name: CreateFrameworkScope :one

INSERT INTO framework_scopes (
    id, tenant_id, framework_version_id, name,
    state, predicate, predicate_hash
)
VALUES (
    $1, $2, $3, $4,
    'draft', $5, $6
)
RETURNING id, tenant_id, framework_version_id, name, created_at, updated_at, state, predicate, predicate_hash, approver_user_id, approved_at, predicate_hash_at_approval, approval_evidence_file_url, approval_evidence_file_hash, effective_from, superseded_by, superseded_at
`

type CreateFrameworkScopeParams struct {
	ID                 pgtype.UUID `json:"id"`
	TenantID           pgtype.UUID `json:"tenant_id"`
	FrameworkVersionID pgtype.UUID `json:"framework_version_id"`
	Name               string      `json:"name"`
	Predicate          []byte      `json:"predicate"`
	PredicateHash      string      `json:"predicate_hash"`
}

// Slice 018: FrameworkScope predicate + four-state workflow queries.
//
// Conventions match slice 014/017/019:
//   - `tenant_id` is always the first parameter (RLS reads it via the GUC,
//     but we additionally pass it explicitly so query plans use the index).
//   - Time-sensitive transitions (`now()`) are issued by the DB so the
//     application doesn't have to choose a clock.
//   - Workflow transition queries use guarded UPDATEs (`AND state = '<from>'`)
//     so concurrent transitions fail loudly with rowcount=0 rather than
//     silently overwriting state.
//
// Insert a new framework_scope row in `draft` state. The predicate is the
// canonicalized JSON the application produced; predicate_hash is sha256 of
// the same JSON (the application computes and passes both to keep the DB
// trigger comparison cheap).
func (q *Queries) CreateFrameworkScope(ctx context.Context, arg CreateFrameworkScopeParams) (FrameworkScope, error) {
	row := q.db.QueryRow(ctx, createFrameworkScope,
		arg.ID,
		arg.TenantID,
		arg.FrameworkVersionID,
		arg.Name,
		arg.Predicate,
		arg.PredicateHash,
	)
	var i FrameworkScope
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FrameworkVersionID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.State,
		&i.Predicate,
		&i.PredicateHash,
		&i.ApproverUserID,
		&i.ApprovedAt,
		&i.PredicateHashAtApproval,
		&i.ApprovalEvidenceFileUrl,
		&i.ApprovalEvidenceFileHash,
		&i.EffectiveFrom,
		&i.SupersededBy,
		&i.SupersededAt,
	)
	return i, err
}

const deleteFrameworkScope = `-- name: DeleteFrameworkScope :exec
DELETE FROM framework_scopes
WHERE tenant_id = $1 AND id = $2
`

type DeleteFrameworkScopeParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

// Used by tests + cleanup paths. Production deployments will rarely delete
// a scope (supersession is the lifecycle exit); the row is preserved as
// audit trail.
func (q *Queries) DeleteFrameworkScope(ctx context.Context, arg DeleteFrameworkScopeParams) error {
	_, err := q.db.Exec(ctx, deleteFrameworkScope, arg.TenantID, arg.ID)
	return err
}

const getActivatedFrameworkScope = `-- name: GetActivatedFrameworkScope :one
SELECT id, tenant_id, framework_version_id, name, created_at, updated_at, state, predicate, predicate_hash, approver_user_id, approved_at, predicate_hash_at_approval, approval_evidence_file_url, approval_evidence_file_hash, effective_from, superseded_by, superseded_at
FROM framework_scopes
WHERE tenant_id = $1
  AND framework_version_id = $2
  AND state = 'activated'
`

type GetActivatedFrameworkScopeParams struct {
	TenantID           pgtype.UUID `json:"tenant_id"`
	FrameworkVersionID pgtype.UUID `json:"framework_version_id"`
}

// Returns the currently-active framework scope for a given framework version,
// i.e. the (at most one) row in state `activated` for that (tenant, fv) pair.
// AC-3: a partial UNIQUE index guarantees at most one row matches.
func (q *Queries) GetActivatedFrameworkScope(ctx context.Context, arg GetActivatedFrameworkScopeParams) (FrameworkScope, error) {
	row := q.db.QueryRow(ctx, getActivatedFrameworkScope, arg.TenantID, arg.FrameworkVersionID)
	var i FrameworkScope
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FrameworkVersionID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.State,
		&i.Predicate,
		&i.PredicateHash,
		&i.ApproverUserID,
		&i.ApprovedAt,
		&i.PredicateHashAtApproval,
		&i.ApprovalEvidenceFileUrl,
		&i.ApprovalEvidenceFileHash,
		&i.EffectiveFrom,
		&i.SupersededBy,
		&i.SupersededAt,
	)
	return i, err
}

const getFrameworkScopeAsOf = `-- name: GetFrameworkScopeAsOf :one
SELECT id, tenant_id, framework_version_id, name, created_at, updated_at, state, predicate, predicate_hash, approver_user_id, approved_at, predicate_hash_at_approval, approval_evidence_file_url, approval_evidence_file_hash, effective_from, superseded_by, superseded_at
FROM framework_scopes
WHERE tenant_id = $1
  AND framework_version_id = $2
  AND effective_from IS NOT NULL
  AND effective_from <= $3
  AND (superseded_at IS NULL OR superseded_at > $3)
ORDER BY effective_from DESC, id ASC
LIMIT 1
`

type GetFrameworkScopeAsOfParams struct {
	TenantID           pgtype.UUID        `json:"tenant_id"`
	FrameworkVersionID pgtype.UUID        `json:"framework_version_id"`
	EffectiveFrom      pgtype.Timestamptz `json:"effective_from"`
}

// AC-13: historical query — return the row that was the active scope at the
// supplied timestamp. The row whose effective_from <= as_of AND (the row was
// not yet superseded at as_of OR was never superseded).
// ORDER BY effective_from DESC LIMIT 1 picks the most-recent applicable row.
func (q *Queries) GetFrameworkScopeAsOf(ctx context.Context, arg GetFrameworkScopeAsOfParams) (FrameworkScope, error) {
	row := q.db.QueryRow(ctx, getFrameworkScopeAsOf, arg.TenantID, arg.FrameworkVersionID, arg.EffectiveFrom)
	var i FrameworkScope
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FrameworkVersionID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.State,
		&i.Predicate,
		&i.PredicateHash,
		&i.ApproverUserID,
		&i.ApprovedAt,
		&i.PredicateHashAtApproval,
		&i.ApprovalEvidenceFileUrl,
		&i.ApprovalEvidenceFileHash,
		&i.EffectiveFrom,
		&i.SupersededBy,
		&i.SupersededAt,
	)
	return i, err
}

const getFrameworkScopeByID = `-- name: GetFrameworkScopeByID :one
SELECT id, tenant_id, framework_version_id, name, created_at, updated_at, state, predicate, predicate_hash, approver_user_id, approved_at, predicate_hash_at_approval, approval_evidence_file_url, approval_evidence_file_hash, effective_from, superseded_by, superseded_at
FROM framework_scopes
WHERE tenant_id = $1 AND id = $2
`

type GetFrameworkScopeByIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetFrameworkScopeByID(ctx context.Context, arg GetFrameworkScopeByIDParams) (FrameworkScope, error) {
	row := q.db.QueryRow(ctx, getFrameworkScopeByID, arg.TenantID, arg.ID)
	var i FrameworkScope
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FrameworkVersionID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.State,
		&i.Predicate,
		&i.PredicateHash,
		&i.ApproverUserID,
		&i.ApprovedAt,
		&i.PredicateHashAtApproval,
		&i.ApprovalEvidenceFileUrl,
		&i.ApprovalEvidenceFileHash,
		&i.EffectiveFrom,
		&i.SupersededBy,
		&i.SupersededAt,
	)
	return i, err
}

const listFrameworkScopes = `-- name: ListFrameworkScopes :many
SELECT id, tenant_id, framework_version_id, name, created_at, updated_at, state, predicate, predicate_hash, approver_user_id, approved_at, predicate_hash_at_approval, approval_evidence_file_url, approval_evidence_file_hash, effective_from, superseded_by, superseded_at
FROM framework_scopes
WHERE tenant_id = $1
ORDER BY created_at DESC, id ASC
`

// Newest first. Caller filters by framework_version + state in the
// application layer because sqlc-static optional WHERE is noisy; the row
// count per tenant is bounded by (#frameworks × scope-versions) which stays
// under a few hundred for any realistic deployment.
func (q *Queries) ListFrameworkScopes(ctx context.Context, tenantID pgtype.UUID) ([]FrameworkScope, error) {
	rows, err := q.db.Query(ctx, listFrameworkScopes, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FrameworkScope
	for rows.Next() {
		var i FrameworkScope
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.FrameworkVersionID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.State,
			&i.Predicate,
			&i.PredicateHash,
			&i.ApproverUserID,
			&i.ApprovedAt,
			&i.PredicateHashAtApproval,
			&i.ApprovalEvidenceFileUrl,
			&i.ApprovalEvidenceFileHash,
			&i.EffectiveFrom,
			&i.SupersededBy,
			&i.SupersededAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFrameworkScopesByFrameworkVersion = `-- name: ListFrameworkScopesByFrameworkVersion :many
SELECT id, tenant_id, framework_version_id, name, created_at, updated_at, state, predicate, predicate_hash, approver_user_id, approved_at, predicate_hash_at_approval, approval_evidence_file_url, approval_evidence_file_hash, effective_from, superseded_by, superseded_at
FROM framework_scopes
WHERE tenant_id = $1 AND framework_version_id = $2
ORDER BY created_at DESC, id ASC
`

type ListFrameworkScopesByFrameworkVersionParams struct {
	TenantID           pgtype.UUID `json:"tenant_id"`
	FrameworkVersionID pgtype.UUID `json:"framework_version_id"`
}

func (q *Queries) ListFrameworkScopesByFrameworkVersion(ctx context.Context, arg ListFrameworkScopesByFrameworkVersionParams) ([]FrameworkScope, error) {
	rows, err := q.db.Query(ctx, listFrameworkScopesByFrameworkVersion, arg.TenantID, arg.FrameworkVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FrameworkScope
	for rows.Next() {
		var i FrameworkScope
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.FrameworkVersionID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.State,
			&i.Predicate,
			&i.PredicateHash,
			&i.ApproverUserID,
			&i.ApprovedAt,
			&i.PredicateHashAtApproval,
			&i.ApprovalEvidenceFileUrl,
			&i.ApprovalEvidenceFileHash,
			&i.EffectiveFrom,
			&i.SupersededBy,
			&i.SupersededAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const submitFrameworkScope = `-- name: SubmitFrameworkScope :one
UPDATE framework_scopes
SET state = 'review',
    updated_at = now()
WHERE tenant_id = $1 AND id = $2 AND state = 'draft'
RETURNING id, tenant_id, framework_version_id, name, created_at, updated_at, state, predicate, predicate_hash, approver_user_id, approved_at, predicate_hash_at_approval, approval_evidence_file_url, approval_evidence_file_hash, effective_from, superseded_by, superseded_at
`

type SubmitFrameworkScopeParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

// AC-6: draft -> review. Guarded so callers can never re-submit an already
// under-review row by accident (would still be valid but masks bugs).
func (q *Queries) SubmitFrameworkScope(ctx context.Context, arg SubmitFrameworkScopeParams) (FrameworkScope, error) {
	row := q.db.QueryRow(ctx, submitFrameworkScope, arg.TenantID, arg.ID)
	var i FrameworkScope
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FrameworkVersionID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.State,
		&i.Predicate,
		&i.PredicateHash,
		&i.ApproverUserID,
		&i.ApprovedAt,
		&i.PredicateHashAtApproval,
		&i.ApprovalEvidenceFileUrl,
		&i.ApprovalEvidenceFileHash,
		&i.EffectiveFrom,
		&i.SupersededBy,
		&i.SupersededAt,
	)
	return i, err
}

const supersedePreviousActivated = `-- name: SupersedePreviousActivated :exec
UPDATE framework_scopes
SET state = 'superseded',
    superseded_by = $3,
    superseded_at = now(),
    updated_at = now()
WHERE tenant_id = $1
  AND framework_version_id = $2
  AND id <> $3
  AND state = 'activated'
`

type SupersedePreviousActivatedParams struct {
	TenantID           pgtype.UUID `json:"tenant_id"`
	FrameworkVersionID pgtype.UUID `json:"framework_version_id"`
	SupersededBy       pgtype.UUID `json:"superseded_by"`
}

// AC-8: in the same transaction as ActivateFrameworkScope, transition the
// previously-activated row (if any) to `superseded`, point its
// superseded_by at the new row, stamp superseded_at = now(). Skips the
// new row itself (id <> @new_id) so a re-running activation is idempotent.
func (q *Queries) SupersedePreviousActivated(ctx context.Context, arg SupersedePreviousActivatedParams) error {
	_, err := q.db.Exec(ctx, supersedePreviousActivated, arg.TenantID, arg.FrameworkVersionID, arg.SupersededBy)
	return err
}

const updateFrameworkScopePredicate = `-- name: UpdateFrameworkScopePredicate :one
UPDATE framework_scopes
SET predicate = $3,
    predicate_hash = $4,
    updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, framework_version_id, name, created_at, updated_at, state, predicate, predicate_hash, approver_user_id, approved_at, predicate_hash_at_approval, approval_evidence_file_url, approval_evidence_file_hash, effective_from, superseded_by, superseded_at
`

type UpdateFrameworkScopePredicateParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	ID            pgtype.UUID `json:"id"`
	Predicate     []byte      `json:"predicate"`
	PredicateHash string      `json:"predicate_hash"`
}

// Patch the predicate. The BEFORE UPDATE trigger
// (framework_scopes_bounce_on_predicate_change_trg) ensures that if this row
// was in `review` or `approved`, NEW.state falls back to `draft` and the
// approval columns are nulled. Application code reads back the row state to
// surface the `approval_invalidated` banner per AC-9.
func (q *Queries) UpdateFrameworkScopePredicate(ctx context.Context, arg UpdateFrameworkScopePredicateParams) (FrameworkScope, error) {
	row := q.db.QueryRow(ctx, updateFrameworkScopePredicate,
		arg.TenantID,
		arg.ID,
		arg.Predicate,
		arg.PredicateHash,
	)
	var i FrameworkScope
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FrameworkVersionID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.State,
		&i.Predicate,
		&i.PredicateHash,
		&i.ApproverUserID,
		&i.ApprovedAt,
		&i.PredicateHashAtApproval,
		&i.ApprovalEvidenceFileUrl,
		&i.ApprovalEvidenceFileHash,
		&i.EffectiveFrom,
		&i.SupersededBy,
		&i.SupersededAt,
	)
	return i, err
}
