// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: framework_crosswalk.sql

package dbx

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFrameworkRequirementsForVersion = `-- name: CountFrameworkRequirementsForVersion :one
SELECT count(*) FROM framework_requirements WHERE framework_version_id = $1
`

func (q *Queries) CountFrameworkRequirementsForVersion(ctx context.Context, frameworkVersionID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFrameworkRequirementsForVersion, frameworkVersionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFwToScfEdgesBySourceAttribution = `-- name: CountFwToScfEdgesBySourceAttribution :one
SELECT count(*) FROM fw_to_scf_edges WHERE source_attribution = $1
`

// Audit query — exposed for integration tests + the audit log.
func (q *Queries) CountFwToScfEdgesBySourceAttribution(ctx context.Context, sourceAttribution CrosswalkSourceAttribution) (int64, error) {
	row := q.db.QueryRow(ctx, countFwToScfEdgesBySourceAttribution, sourceAttribution)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFrameworkRequirementByCurrentVersion = `-- name: GetFrameworkRequirementByCurrentVersion :one
SELECT fr.id, fr.framework_version_id, fr.code, fr.title, fr.body, fr.created_at, fr.updated_at
FROM framework_requirements fr
JOIN framework_versions fv ON fv.id = fr.framework_version_id
JOIN frameworks f ON f.id = fv.framework_id
WHERE f.slug = $1 AND fv.status = 'current' AND fr.code = $2 AND f.tenant_id IS NULL
`

type GetFrameworkRequirementByCurrentVersionParams struct {
	Slug string `json:"slug"`
	Code string `json:"code"`
}

// Same as above but uses the framework's "current" version. Convenience
// query so callers can omit the version (e.g., "soc2::CC6.6").
func (q *Queries) GetFrameworkRequirementByCurrentVersion(ctx context.Context, arg GetFrameworkRequirementByCurrentVersionParams) (FrameworkRequirement, error) {
	row := q.db.QueryRow(ctx, getFrameworkRequirementByCurrentVersion, arg.Slug, arg.Code)
	var i FrameworkRequirement
	err := row.Scan(
		&i.ID,
		&i.FrameworkVersionID,
		&i.Code,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFrameworkRequirementByFrameworkSlugVersionCode = `-- name: GetFrameworkRequirementByFrameworkSlugVersionCode :one
SELECT fr.id, fr.framework_version_id, fr.code, fr.title, fr.body, fr.created_at, fr.updated_at
FROM framework_requirements fr
JOIN framework_versions fv ON fv.id = fr.framework_version_id
JOIN frameworks f ON f.id = fv.framework_id
WHERE f.slug = $1 AND fv.version = $2 AND fr.code = $3 AND f.tenant_id IS NULL
`

type GetFrameworkRequirementByFrameworkSlugVersionCodeParams struct {
	Slug    string `json:"slug"`
	Version string `json:"version"`
	Code    string `json:"code"`
}

// Resolve a colon-delimited requirement id like "soc2:2017:CC6.6" by
// joining the framework + framework_version. tenant_id IS NULL constraint
// restricts to the global catalog.
func (q *Queries) GetFrameworkRequirementByFrameworkSlugVersionCode(ctx context.Context, arg GetFrameworkRequirementByFrameworkSlugVersionCodeParams) (FrameworkRequirement, error) {
	row := q.db.QueryRow(ctx, getFrameworkRequirementByFrameworkSlugVersionCode, arg.Slug, arg.Version, arg.Code)
	var i FrameworkRequirement
	err := row.Scan(
		&i.ID,
		&i.FrameworkVersionID,
		&i.Code,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFrameworkRequirementByID = `-- name: GetFrameworkRequirementByID :one
SELECT id, framework_version_id, code, title, body, created_at, updated_at FROM framework_requirements WHERE id = $1
`

func (q *Queries) GetFrameworkRequirementByID(ctx context.Context, id pgtype.UUID) (FrameworkRequirement, error) {
	row := q.db.QueryRow(ctx, getFrameworkRequirementByID, id)
	var i FrameworkRequirement
	err := row.Scan(
		&i.ID,
		&i.FrameworkVersionID,
		&i.Code,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFrameworkRequirementByVersionAndCode = `-- name: GetFrameworkRequirementByVersionAndCode :one
SELECT id, framework_version_id, code, title, body, created_at, updated_at FROM framework_requirements
WHERE framework_version_id = $1 AND code = $2
`

type GetFrameworkRequirementByVersionAndCodeParams struct {
	FrameworkVersionID pgtype.UUID `json:"framework_version_id"`
	Code               string      `json:"code"`
}

// Lookup by natural key. Used by the importer to classify
// Created/Updated/Unchanged and by the traversal handler for the
// code-form path (e.g., resolve "CC6.6" against the current SOC 2 version).
func (q *Queries) GetFrameworkRequirementByVersionAndCode(ctx context.Context, arg GetFrameworkRequirementByVersionAndCodeParams) (FrameworkRequirement, error) {
	row := q.db.QueryRow(ctx, getFrameworkRequirementByVersionAndCode, arg.FrameworkVersionID, arg.Code)
	var i FrameworkRequirement
	err := row.Scan(
		&i.ID,
		&i.FrameworkVersionID,
		&i.Code,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFwToScfEdge = `-- name: GetFwToScfEdge :one
SELECT id, framework_requirement_id, scf_anchor_id, relationship_type, strength, source_attribution, rationale, created_at, updated_at FROM fw_to_scf_edges
WHERE framework_requirement_id = $1 AND scf_anchor_id = $2
`

type GetFwToScfEdgeParams struct {
	FrameworkRequirementID pgtype.UUID `json:"framework_requirement_id"`
	ScfAnchorID            pgtype.UUID `json:"scf_anchor_id"`
}

// Look up one edge by (requirement, anchor). Returns ErrNoRows when the
// edge doesn't exist yet. Importer calls this first to classify
// Created/Updated/Unchanged.
func (q *Queries) GetFwToScfEdge(ctx context.Context, arg GetFwToScfEdgeParams) (FwToScfEdge, error) {
	row := q.db.QueryRow(ctx, getFwToScfEdge, arg.FrameworkRequirementID, arg.ScfAnchorID)
	var i FwToScfEdge
	err := row.Scan(
		&i.ID,
		&i.FrameworkRequirementID,
		&i.ScfAnchorID,
		&i.RelationshipType,
		&i.Strength,
		&i.SourceAttribution,
		&i.Rationale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertFwToScfEdge = `-- name: InsertFwToScfEdge :one
INSERT INTO fw_to_scf_edges (
    id, framework_requirement_id, scf_anchor_id,
    relationship_type, strength, source_attribution, rationale
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, framework_requirement_id, scf_anchor_id, relationship_type, strength, source_attribution, rationale, created_at, updated_at
`

type InsertFwToScfEdgeParams struct {
	ID                     pgtype.UUID                `json:"id"`
	FrameworkRequirementID pgtype.UUID                `json:"framework_requirement_id"`
	ScfAnchorID            pgtype.UUID                `json:"scf_anchor_id"`
	RelationshipType       StrmRelationshipType       `json:"relationship_type"`
	Strength               float64                    `json:"strength"`
	SourceAttribution      CrosswalkSourceAttribution `json:"source_attribution"`
	Rationale              string                     `json:"rationale"`
}

func (q *Queries) InsertFwToScfEdge(ctx context.Context, arg InsertFwToScfEdgeParams) (FwToScfEdge, error) {
	row := q.db.QueryRow(ctx, insertFwToScfEdge,
		arg.ID,
		arg.FrameworkRequirementID,
		arg.ScfAnchorID,
		arg.RelationshipType,
		arg.Strength,
		arg.SourceAttribution,
		arg.Rationale,
	)
	var i FwToScfEdge
	err := row.Scan(
		&i.ID,
		&i.FrameworkRequirementID,
		&i.ScfAnchorID,
		&i.RelationshipType,
		&i.Strength,
		&i.SourceAttribution,
		&i.Rationale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFrameworkRequirementsForVersion = `-- name: ListFrameworkRequirementsForVersion :many
SELECT id, framework_version_id, code, title, body, created_at, updated_at
FROM framework_requirements
WHERE framework_version_id = $1
ORDER BY code
`

func (q *Queries) ListFrameworkRequirementsForVersion(ctx context.Context, frameworkVersionID pgtype.UUID) ([]FrameworkRequirement, error) {
	rows, err := q.db.Query(ctx, listFrameworkRequirementsForVersion, frameworkVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FrameworkRequirement
	for rows.Next() {
		var i FrameworkRequirement
		if err := rows.Scan(
			&i.ID,
			&i.FrameworkVersionID,
			&i.Code,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFwToScfEdgesForRequirement = `-- name: ListFwToScfEdgesForRequirement :many
SELECT
    e.id,
    e.framework_requirement_id,
    e.scf_anchor_id,
    e.relationship_type,
    e.strength,
    e.source_attribution,
    e.rationale,
    a.scf_id,
    a.family,
    a.title AS anchor_title
FROM fw_to_scf_edges e
JOIN scf_anchors a ON a.id = e.scf_anchor_id
WHERE e.framework_requirement_id = $1
ORDER BY e.strength DESC, a.scf_id
`

type ListFwToScfEdgesForRequirementRow struct {
	ID                     pgtype.UUID                `json:"id"`
	FrameworkRequirementID pgtype.UUID                `json:"framework_requirement_id"`
	ScfAnchorID            pgtype.UUID                `json:"scf_anchor_id"`
	RelationshipType       StrmRelationshipType       `json:"relationship_type"`
	Strength               float64                    `json:"strength"`
	SourceAttribution      CrosswalkSourceAttribution `json:"source_attribution"`
	Rationale              string                     `json:"rationale"`
	ScfID                  string                     `json:"scf_id"`
	Family                 string                     `json:"family"`
	AnchorTitle            string                     `json:"anchor_title"`
}

// Reverse traversal — given a requirement, return all SCF anchors it maps
// to with relationship type and strength. Joins through scf_anchors so the
// caller gets the scf_id + family + title in one round trip.
func (q *Queries) ListFwToScfEdgesForRequirement(ctx context.Context, frameworkRequirementID pgtype.UUID) ([]ListFwToScfEdgesForRequirementRow, error) {
	rows, err := q.db.Query(ctx, listFwToScfEdgesForRequirement, frameworkRequirementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFwToScfEdgesForRequirementRow
	for rows.Next() {
		var i ListFwToScfEdgesForRequirementRow
		if err := rows.Scan(
			&i.ID,
			&i.FrameworkRequirementID,
			&i.ScfAnchorID,
			&i.RelationshipType,
			&i.Strength,
			&i.SourceAttribution,
			&i.Rationale,
			&i.ScfID,
			&i.Family,
			&i.AnchorTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFrameworkVersionRequirementCount = `-- name: UpdateFrameworkVersionRequirementCount :exec
UPDATE framework_versions
SET requirement_count = $2
WHERE id = $1
`

type UpdateFrameworkVersionRequirementCountParams struct {
	ID               pgtype.UUID `json:"id"`
	RequirementCount int32       `json:"requirement_count"`
}

// Tally — the importer keeps framework_versions.requirement_count in sync
// so dashboards can show "60 controls" without a count(*).
func (q *Queries) UpdateFrameworkVersionRequirementCount(ctx context.Context, arg UpdateFrameworkVersionRequirementCountParams) error {
	_, err := q.db.Exec(ctx, updateFrameworkVersionRequirementCount, arg.ID, arg.RequirementCount)
	return err
}

const updateFwToScfEdge = `-- name: UpdateFwToScfEdge :one
UPDATE fw_to_scf_edges
SET relationship_type    = $2,
    strength             = $3,
    source_attribution   = $4,
    rationale            = $5,
    updated_at           = now()
WHERE id = $1
RETURNING id, framework_requirement_id, scf_anchor_id, relationship_type, strength, source_attribution, rationale, created_at, updated_at
`

type UpdateFwToScfEdgeParams struct {
	ID                pgtype.UUID                `json:"id"`
	RelationshipType  StrmRelationshipType       `json:"relationship_type"`
	Strength          float64                    `json:"strength"`
	SourceAttribution CrosswalkSourceAttribution `json:"source_attribution"`
	Rationale         string                     `json:"rationale"`
}

// Update an existing edge in place. Importer decides whether to call this
// based on a content-equality check.
func (q *Queries) UpdateFwToScfEdge(ctx context.Context, arg UpdateFwToScfEdgeParams) (FwToScfEdge, error) {
	row := q.db.QueryRow(ctx, updateFwToScfEdge,
		arg.ID,
		arg.RelationshipType,
		arg.Strength,
		arg.SourceAttribution,
		arg.Rationale,
	)
	var i FwToScfEdge
	err := row.Scan(
		&i.ID,
		&i.FrameworkRequirementID,
		&i.ScfAnchorID,
		&i.RelationshipType,
		&i.Strength,
		&i.SourceAttribution,
		&i.Rationale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertFrameworkRequirement = `-- name: UpsertFrameworkRequirement :one
INSERT INTO framework_requirements (id, framework_version_id, code, title, body)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE
SET title       = EXCLUDED.title,
    body        = EXCLUDED.body,
    updated_at  = now()
RETURNING id, framework_version_id, code, title, body, created_at, updated_at
`

type UpsertFrameworkRequirementParams struct {
	ID                 pgtype.UUID `json:"id"`
	FrameworkVersionID pgtype.UUID `json:"framework_version_id"`
	Code               string      `json:"code"`
	Title              string      `json:"title"`
	Body               string      `json:"body"`
}

// Insert or update a framework_requirements row. Deterministic id derived
// from (framework_version_id, code) so re-imports are idempotent without
// relying on NULLs-distinct gotchas on the UNIQUE constraint.
func (q *Queries) UpsertFrameworkRequirement(ctx context.Context, arg UpsertFrameworkRequirementParams) (FrameworkRequirement, error) {
	row := q.db.QueryRow(ctx, upsertFrameworkRequirement,
		arg.ID,
		arg.FrameworkVersionID,
		arg.Code,
		arg.Title,
		arg.Body,
	)
	var i FrameworkRequirement
	err := row.Scan(
		&i.ID,
		&i.FrameworkVersionID,
		&i.Code,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
