// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: framework_crosswalk.sql

package dbx

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFrameworkRequirementsForVersion = `-- name: CountFrameworkRequirementsForVersion :one
SELECT count(*) FROM framework_requirements WHERE framework_version_id = $1
`

func (q *Queries) CountFrameworkRequirementsForVersion(ctx context.Context, frameworkVersionID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFrameworkRequirementsForVersion, frameworkVersionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFwToScfEdgesBySourceAttribution = `-- name: CountFwToScfEdgesBySourceAttribution :one
SELECT count(*) FROM fw_to_scf_edges WHERE source_attribution = $1
`

// Audit query — exposed for integration tests + the audit log.
func (q *Queries) CountFwToScfEdgesBySourceAttribution(ctx context.Context, sourceAttribution CrosswalkSourceAttribution) (int64, error) {
	row := q.db.QueryRow(ctx, countFwToScfEdgesBySourceAttribution, sourceAttribution)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFrameworkRequirementByCurrentVersion = `-- name: GetFrameworkRequirementByCurrentVersion :one
SELECT fr.id, fr.framework_version_id, fr.code, fr.title, fr.body, fr.created_at, fr.updated_at
FROM framework_requirements fr
JOIN framework_versions fv ON fv.id = fr.framework_version_id
JOIN frameworks f ON f.id = fv.framework_id
WHERE f.slug = $1 AND fv.status = 'current' AND fr.code = $2 AND f.tenant_id IS NULL
`

type GetFrameworkRequirementByCurrentVersionParams struct {
	Slug string `json:"slug"`
	Code string `json:"code"`
}

// Same as above but uses the framework's "current" version. Convenience
// query so callers can omit the version (e.g., "soc2::CC6.6").
func (q *Queries) GetFrameworkRequirementByCurrentVersion(ctx context.Context, arg GetFrameworkRequirementByCurrentVersionParams) (FrameworkRequirement, error) {
	row := q.db.QueryRow(ctx, getFrameworkRequirementByCurrentVersion, arg.Slug, arg.Code)
	var i FrameworkRequirement
	err := row.Scan(
		&i.ID,
		&i.FrameworkVersionID,
		&i.Code,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFrameworkRequirementByFrameworkSlugVersionCode = `-- name: GetFrameworkRequirementByFrameworkSlugVersionCode :one
SELECT fr.id, fr.framework_version_id, fr.code, fr.title, fr.body, fr.created_at, fr.updated_at
FROM framework_requirements fr
JOIN framework_versions fv ON fv.id = fr.framework_version_id
JOIN frameworks f ON f.id = fv.framework_id
WHERE f.slug = $1 AND fv.version = $2 AND fr.code = $3 AND f.tenant_id IS NULL
`

type GetFrameworkRequirementByFrameworkSlugVersionCodeParams struct {
	Slug    string `json:"slug"`
	Version string `json:"version"`
	Code    string `json:"code"`
}

// Resolve a colon-delimited requirement id like "soc2:2017:CC6.6" by
// joining the framework + framework_version. tenant_id IS NULL constraint
// restricts to the global catalog.
func (q *Queries) GetFrameworkRequirementByFrameworkSlugVersionCode(ctx context.Context, arg GetFrameworkRequirementByFrameworkSlugVersionCodeParams) (FrameworkRequirement, error) {
	row := q.db.QueryRow(ctx, getFrameworkRequirementByFrameworkSlugVersionCode, arg.Slug, arg.Version, arg.Code)
	var i FrameworkRequirement
	err := row.Scan(
		&i.ID,
		&i.FrameworkVersionID,
		&i.Code,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFrameworkRequirementByID = `-- name: GetFrameworkRequirementByID :one
SELECT id, framework_version_id, code, title, body, created_at, updated_at FROM framework_requirements WHERE id = $1
`

func (q *Queries) GetFrameworkRequirementByID(ctx context.Context, id pgtype.UUID) (FrameworkRequirement, error) {
	row := q.db.QueryRow(ctx, getFrameworkRequirementByID, id)
	var i FrameworkRequirement
	err := row.Scan(
		&i.ID,
		&i.FrameworkVersionID,
		&i.Code,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFrameworkRequirementByVersionAndCode = `-- name: GetFrameworkRequirementByVersionAndCode :one
SELECT id, framework_version_id, code, title, body, created_at, updated_at FROM framework_requirements
WHERE framework_version_id = $1 AND code = $2
`

type GetFrameworkRequirementByVersionAndCodeParams struct {
	FrameworkVersionID pgtype.UUID `json:"framework_version_id"`
	Code               string      `json:"code"`
}

// Lookup by natural key. Used by the importer to classify
// Created/Updated/Unchanged and by the traversal handler for the
// code-form path (e.g., resolve "CC6.6" against the current SOC 2 version).
func (q *Queries) GetFrameworkRequirementByVersionAndCode(ctx context.Context, arg GetFrameworkRequirementByVersionAndCodeParams) (FrameworkRequirement, error) {
	row := q.db.QueryRow(ctx, getFrameworkRequirementByVersionAndCode, arg.FrameworkVersionID, arg.Code)
	var i FrameworkRequirement
	err := row.Scan(
		&i.ID,
		&i.FrameworkVersionID,
		&i.Code,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFwToScfEdge = `-- name: GetFwToScfEdge :one
SELECT id, framework_requirement_id, scf_anchor_id, relationship_type, strength, source_attribution, rationale, created_at, updated_at, mapping_tier FROM fw_to_scf_edges
WHERE framework_requirement_id = $1 AND scf_anchor_id = $2
`

type GetFwToScfEdgeParams struct {
	FrameworkRequirementID pgtype.UUID `json:"framework_requirement_id"`
	ScfAnchorID            pgtype.UUID `json:"scf_anchor_id"`
}

// Look up one edge by (requirement, anchor). Returns ErrNoRows when the
// edge doesn't exist yet. Importer calls this first to classify
// Created/Updated/Unchanged.
func (q *Queries) GetFwToScfEdge(ctx context.Context, arg GetFwToScfEdgeParams) (FwToScfEdge, error) {
	row := q.db.QueryRow(ctx, getFwToScfEdge, arg.FrameworkRequirementID, arg.ScfAnchorID)
	var i FwToScfEdge
	err := row.Scan(
		&i.ID,
		&i.FrameworkRequirementID,
		&i.ScfAnchorID,
		&i.RelationshipType,
		&i.Strength,
		&i.SourceAttribution,
		&i.Rationale,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MappingTier,
	)
	return i, err
}

const getFwToScfEdgeContentForUpdate = `-- name: GetFwToScfEdgeContentForUpdate :one
SELECT id, framework_requirement_id, scf_anchor_id,
       relationship_type, strength, rationale, mapping_tier
FROM fw_to_scf_edges
WHERE id = $1
FOR UPDATE
`

type GetFwToScfEdgeContentForUpdateRow struct {
	ID                     pgtype.UUID          `json:"id"`
	FrameworkRequirementID pgtype.UUID          `json:"framework_requirement_id"`
	ScfAnchorID            pgtype.UUID          `json:"scf_anchor_id"`
	RelationshipType       StrmRelationshipType `json:"relationship_type"`
	Strength               float64              `json:"strength"`
	Rationale              string               `json:"rationale"`
	MappingTier            CrosswalkMappingTier `json:"mapping_tier"`
}

// Row-lock the edge's editable content inside the edit transaction so a
// concurrent edit cannot race the read-validate-write window (the same shape
// GetFwToScfEdgeTierForUpdate uses for the tier path). mapping_tier comes back
// with it because a content edit on a `verified` edge demotes it in the same tx
// (slice 536b D-536b-1). Returns ErrNoRows for an unknown edge.
func (q *Queries) GetFwToScfEdgeContentForUpdate(ctx context.Context, id pgtype.UUID) (GetFwToScfEdgeContentForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getFwToScfEdgeContentForUpdate, id)
	var i GetFwToScfEdgeContentForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.FrameworkRequirementID,
		&i.ScfAnchorID,
		&i.RelationshipType,
		&i.Strength,
		&i.Rationale,
		&i.MappingTier,
	)
	return i, err
}

const getFwToScfEdgeTier = `-- name: GetFwToScfEdgeTier :one

SELECT id, mapping_tier, source_attribution
FROM fw_to_scf_edges
WHERE id = $1
`

type GetFwToScfEdgeTierRow struct {
	ID                pgtype.UUID                `json:"id"`
	MappingTier       CrosswalkMappingTier       `json:"mapping_tier"`
	SourceAttribution CrosswalkSourceAttribution `json:"source_attribution"`
}

// ===== slice 483: crosswalk mapping-tier governance =====
// Read the current trust tier of one edge by id. The transition store calls
// this FOR UPDATE (see GetFwToScfEdgeTierForUpdate) inside the tx; this plain
// variant is for read-only callers. Returns ErrNoRows for an unknown edge.
func (q *Queries) GetFwToScfEdgeTier(ctx context.Context, id pgtype.UUID) (GetFwToScfEdgeTierRow, error) {
	row := q.db.QueryRow(ctx, getFwToScfEdgeTier, id)
	var i GetFwToScfEdgeTierRow
	err := row.Scan(&i.ID, &i.MappingTier, &i.SourceAttribution)
	return i, err
}

const getFwToScfEdgeTierForUpdate = `-- name: GetFwToScfEdgeTierForUpdate :one
SELECT id, mapping_tier, source_attribution
FROM fw_to_scf_edges
WHERE id = $1
FOR UPDATE
`

type GetFwToScfEdgeTierForUpdateRow struct {
	ID                pgtype.UUID                `json:"id"`
	MappingTier       CrosswalkMappingTier       `json:"mapping_tier"`
	SourceAttribution CrosswalkSourceAttribution `json:"source_attribution"`
}

// Row-lock the edge's tier inside the transition transaction so a concurrent
// transition cannot race the read-validate-write window. Returns ErrNoRows for
// an unknown edge (the handler maps that to 404).
func (q *Queries) GetFwToScfEdgeTierForUpdate(ctx context.Context, id pgtype.UUID) (GetFwToScfEdgeTierForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getFwToScfEdgeTierForUpdate, id)
	var i GetFwToScfEdgeTierForUpdateRow
	err := row.Scan(&i.ID, &i.MappingTier, &i.SourceAttribution)
	return i, err
}

const insertFwToScfEdge = `-- name: InsertFwToScfEdge :one
INSERT INTO fw_to_scf_edges (
    id, framework_requirement_id, scf_anchor_id,
    relationship_type, strength, source_attribution, rationale
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, framework_requirement_id, scf_anchor_id, relationship_type, strength, source_attribution, rationale, created_at, updated_at, mapping_tier
`

type InsertFwToScfEdgeParams struct {
	ID                     pgtype.UUID                `json:"id"`
	FrameworkRequirementID pgtype.UUID                `json:"framework_requirement_id"`
	ScfAnchorID            pgtype.UUID                `json:"scf_anchor_id"`
	RelationshipType       StrmRelationshipType       `json:"relationship_type"`
	Strength               float64                    `json:"strength"`
	SourceAttribution      CrosswalkSourceAttribution `json:"source_attribution"`
	Rationale              string                     `json:"rationale"`
}

func (q *Queries) InsertFwToScfEdge(ctx context.Context, arg InsertFwToScfEdgeParams) (FwToScfEdge, error) {
	row := q.db.QueryRow(ctx, insertFwToScfEdge,
		arg.ID,
		arg.FrameworkRequirementID,
		arg.ScfAnchorID,
		arg.RelationshipType,
		arg.Strength,
		arg.SourceAttribution,
		arg.Rationale,
	)
	var i FwToScfEdge
	err := row.Scan(
		&i.ID,
		&i.FrameworkRequirementID,
		&i.ScfAnchorID,
		&i.RelationshipType,
		&i.Strength,
		&i.SourceAttribution,
		&i.Rationale,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MappingTier,
	)
	return i, err
}

const insertFwToScfEdgeContentEdit = `-- name: InsertFwToScfEdgeContentEdit :one
INSERT INTO fw_to_scf_edge_content_edits (
    edge_id, editor_id,
    from_relationship_type, to_relationship_type,
    from_strength, to_strength,
    from_rationale, to_rationale,
    note
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, edge_id, editor_id, from_relationship_type, to_relationship_type, from_strength, to_strength, from_rationale, to_rationale, note, created_at
`

type InsertFwToScfEdgeContentEditParams struct {
	EdgeID               pgtype.UUID          `json:"edge_id"`
	EditorID             pgtype.UUID          `json:"editor_id"`
	FromRelationshipType StrmRelationshipType `json:"from_relationship_type"`
	ToRelationshipType   StrmRelationshipType `json:"to_relationship_type"`
	FromStrength         float64              `json:"from_strength"`
	ToStrength           float64              `json:"to_strength"`
	FromRationale        string               `json:"from_rationale"`
	ToRationale          string               `json:"to_rationale"`
	Note                 string               `json:"note"`
}

// Append the immutable audit row for a content edit (threat-model R). Written
// in the SAME transaction as SetFwToScfEdgeContent — there is no code path that
// changes edge content without also inserting here.
func (q *Queries) InsertFwToScfEdgeContentEdit(ctx context.Context, arg InsertFwToScfEdgeContentEditParams) (FwToScfEdgeContentEdit, error) {
	row := q.db.QueryRow(ctx, insertFwToScfEdgeContentEdit,
		arg.EdgeID,
		arg.EditorID,
		arg.FromRelationshipType,
		arg.ToRelationshipType,
		arg.FromStrength,
		arg.ToStrength,
		arg.FromRationale,
		arg.ToRationale,
		arg.Note,
	)
	var i FwToScfEdgeContentEdit
	err := row.Scan(
		&i.ID,
		&i.EdgeID,
		&i.EditorID,
		&i.FromRelationshipType,
		&i.ToRelationshipType,
		&i.FromStrength,
		&i.ToStrength,
		&i.FromRationale,
		&i.ToRationale,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const insertFwToScfEdgeTierTransition = `-- name: InsertFwToScfEdgeTierTransition :one
INSERT INTO fw_to_scf_edge_tier_transitions (
    edge_id, reviewer_id, from_tier, to_tier, note
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, edge_id, reviewer_id, from_tier, to_tier, note, created_at
`

type InsertFwToScfEdgeTierTransitionParams struct {
	EdgeID     pgtype.UUID          `json:"edge_id"`
	ReviewerID pgtype.UUID          `json:"reviewer_id"`
	FromTier   CrosswalkMappingTier `json:"from_tier"`
	ToTier     CrosswalkMappingTier `json:"to_tier"`
	Note       string               `json:"note"`
}

// Append the immutable audit row for a tier transition (threat-model R /
// P0-483-4). Written in the SAME transaction as SetFwToScfEdgeTier.
func (q *Queries) InsertFwToScfEdgeTierTransition(ctx context.Context, arg InsertFwToScfEdgeTierTransitionParams) (FwToScfEdgeTierTransition, error) {
	row := q.db.QueryRow(ctx, insertFwToScfEdgeTierTransition,
		arg.EdgeID,
		arg.ReviewerID,
		arg.FromTier,
		arg.ToTier,
		arg.Note,
	)
	var i FwToScfEdgeTierTransition
	err := row.Scan(
		&i.ID,
		&i.EdgeID,
		&i.ReviewerID,
		&i.FromTier,
		&i.ToTier,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const listFrameworkRequirementsForVersion = `-- name: ListFrameworkRequirementsForVersion :many
SELECT id, framework_version_id, code, title, body, created_at, updated_at
FROM framework_requirements
WHERE framework_version_id = $1
ORDER BY code
`

func (q *Queries) ListFrameworkRequirementsForVersion(ctx context.Context, frameworkVersionID pgtype.UUID) ([]FrameworkRequirement, error) {
	rows, err := q.db.Query(ctx, listFrameworkRequirementsForVersion, frameworkVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FrameworkRequirement
	for rows.Next() {
		var i FrameworkRequirement
		if err := rows.Scan(
			&i.ID,
			&i.FrameworkVersionID,
			&i.Code,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFrameworkRequirementsForVersionPaged = `-- name: ListFrameworkRequirementsForVersionPaged :many

SELECT id, framework_version_id, code, title, body, created_at, updated_at
FROM framework_requirements
WHERE framework_version_id = $1
ORDER BY code
LIMIT $2 OFFSET $3
`

type ListFrameworkRequirementsForVersionPagedParams struct {
	FrameworkVersionID pgtype.UUID `json:"framework_version_id"`
	Limit              int32       `json:"limit"`
	Offset             int32       `json:"offset"`
}

// ===== slice 536b: crosswalk review queue + content editing =====
// The review queue's page of requirements, ordered by code so the operator's
// position is stable across refreshes. Paginated because slice 536's
// threat-model D asks for a bounded scan per framework_version rather than the
// whole catalog in one response.
func (q *Queries) ListFrameworkRequirementsForVersionPaged(ctx context.Context, arg ListFrameworkRequirementsForVersionPagedParams) ([]FrameworkRequirement, error) {
	rows, err := q.db.Query(ctx, listFrameworkRequirementsForVersionPaged, arg.FrameworkVersionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FrameworkRequirement
	for rows.Next() {
		var i FrameworkRequirement
		if err := rows.Scan(
			&i.ID,
			&i.FrameworkVersionID,
			&i.Code,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFwToScfEdgeContentEdits = `-- name: ListFwToScfEdgeContentEdits :many
SELECT id, edge_id, editor_id, from_relationship_type, to_relationship_type, from_strength, to_strength, from_rationale, to_rationale, note, created_at
FROM fw_to_scf_edge_content_edits
WHERE edge_id = $1
ORDER BY created_at DESC
`

// Admin/maintainer-scoped read of an edge's content-edit history (newest
// first). Editor identity stays behind the admin boundary, never on the public
// /anchors payload (the slice-483 P0-483-6 line, held for this trail too).
func (q *Queries) ListFwToScfEdgeContentEdits(ctx context.Context, edgeID pgtype.UUID) ([]FwToScfEdgeContentEdit, error) {
	rows, err := q.db.Query(ctx, listFwToScfEdgeContentEdits, edgeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FwToScfEdgeContentEdit
	for rows.Next() {
		var i FwToScfEdgeContentEdit
		if err := rows.Scan(
			&i.ID,
			&i.EdgeID,
			&i.EditorID,
			&i.FromRelationshipType,
			&i.ToRelationshipType,
			&i.FromStrength,
			&i.ToStrength,
			&i.FromRationale,
			&i.ToRationale,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFwToScfEdgeTierTransitions = `-- name: ListFwToScfEdgeTierTransitions :many
SELECT id, edge_id, reviewer_id, from_tier, to_tier, note, created_at
FROM fw_to_scf_edge_tier_transitions
WHERE edge_id = $1
ORDER BY created_at DESC
`

// Admin/maintainer-scoped read of an edge's transition history (newest first).
// NOT on the public /anchors payload — reviewer identity stays behind the admin
// boundary (threat-model I / P0-483-6).
func (q *Queries) ListFwToScfEdgeTierTransitions(ctx context.Context, edgeID pgtype.UUID) ([]FwToScfEdgeTierTransition, error) {
	rows, err := q.db.Query(ctx, listFwToScfEdgeTierTransitions, edgeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FwToScfEdgeTierTransition
	for rows.Next() {
		var i FwToScfEdgeTierTransition
		if err := rows.Scan(
			&i.ID,
			&i.EdgeID,
			&i.ReviewerID,
			&i.FromTier,
			&i.ToTier,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFwToScfEdgesForRequirement = `-- name: ListFwToScfEdgesForRequirement :many
SELECT
    e.id,
    e.framework_requirement_id,
    e.scf_anchor_id,
    e.relationship_type,
    e.strength,
    e.source_attribution,
    e.mapping_tier,
    e.rationale,
    a.scf_id,
    a.family,
    a.title AS anchor_title
FROM fw_to_scf_edges e
JOIN scf_anchors a ON a.id = e.scf_anchor_id
WHERE e.framework_requirement_id = $1
ORDER BY e.strength DESC, a.scf_id
`

type ListFwToScfEdgesForRequirementRow struct {
	ID                     pgtype.UUID                `json:"id"`
	FrameworkRequirementID pgtype.UUID                `json:"framework_requirement_id"`
	ScfAnchorID            pgtype.UUID                `json:"scf_anchor_id"`
	RelationshipType       StrmRelationshipType       `json:"relationship_type"`
	Strength               float64                    `json:"strength"`
	SourceAttribution      CrosswalkSourceAttribution `json:"source_attribution"`
	MappingTier            CrosswalkMappingTier       `json:"mapping_tier"`
	Rationale              string                     `json:"rationale"`
	ScfID                  string                     `json:"scf_id"`
	Family                 string                     `json:"family"`
	AnchorTitle            string                     `json:"anchor_title"`
}

// Reverse traversal — given a requirement, return all SCF anchors it maps
// to with relationship type and strength. Joins through scf_anchors so the
// caller gets the scf_id + family + title in one round trip.
func (q *Queries) ListFwToScfEdgesForRequirement(ctx context.Context, frameworkRequirementID pgtype.UUID) ([]ListFwToScfEdgesForRequirementRow, error) {
	rows, err := q.db.Query(ctx, listFwToScfEdgesForRequirement, frameworkRequirementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFwToScfEdgesForRequirementRow
	for rows.Next() {
		var i ListFwToScfEdgesForRequirementRow
		if err := rows.Scan(
			&i.ID,
			&i.FrameworkRequirementID,
			&i.ScfAnchorID,
			&i.RelationshipType,
			&i.Strength,
			&i.SourceAttribution,
			&i.MappingTier,
			&i.Rationale,
			&i.ScfID,
			&i.Family,
			&i.AnchorTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFwToScfEdgesForRequirementIDs = `-- name: ListFwToScfEdgesForRequirementIDs :many
SELECT
    e.id,
    e.framework_requirement_id,
    r.code AS requirement_code,
    e.scf_anchor_id,
    e.relationship_type,
    e.strength,
    e.source_attribution,
    e.mapping_tier,
    e.rationale,
    e.updated_at,
    a.scf_id,
    a.family,
    a.title AS anchor_title
FROM fw_to_scf_edges e
JOIN scf_anchors a ON a.id = e.scf_anchor_id
JOIN framework_requirements r ON r.id = e.framework_requirement_id
WHERE e.framework_requirement_id = ANY($1::uuid[])
ORDER BY r.code, a.scf_id
`

type ListFwToScfEdgesForRequirementIDsRow struct {
	ID                     pgtype.UUID                `json:"id"`
	FrameworkRequirementID pgtype.UUID                `json:"framework_requirement_id"`
	RequirementCode        string                     `json:"requirement_code"`
	ScfAnchorID            pgtype.UUID                `json:"scf_anchor_id"`
	RelationshipType       StrmRelationshipType       `json:"relationship_type"`
	Strength               float64                    `json:"strength"`
	SourceAttribution      CrosswalkSourceAttribution `json:"source_attribution"`
	MappingTier            CrosswalkMappingTier       `json:"mapping_tier"`
	Rationale              string                     `json:"rationale"`
	UpdatedAt              pgtype.Timestamptz         `json:"updated_at"`
	ScfID                  string                     `json:"scf_id"`
	Family                 string                     `json:"family"`
	AnchorTitle            string                     `json:"anchor_title"`
}

// One round trip for a whole page of requirements' edges, instead of N calls to
// ListFwToScfEdgesForRequirement. Same projection as that query plus the
// requirement code, which the conflict adapter needs to label a finding and
// which the per-requirement variant cannot supply (it joins scf_anchors, not
// framework_requirements).
func (q *Queries) ListFwToScfEdgesForRequirementIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListFwToScfEdgesForRequirementIDsRow, error) {
	rows, err := q.db.Query(ctx, listFwToScfEdgesForRequirementIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFwToScfEdgesForRequirementIDsRow
	for rows.Next() {
		var i ListFwToScfEdgesForRequirementIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.FrameworkRequirementID,
			&i.RequirementCode,
			&i.ScfAnchorID,
			&i.RelationshipType,
			&i.Strength,
			&i.SourceAttribution,
			&i.MappingTier,
			&i.Rationale,
			&i.UpdatedAt,
			&i.ScfID,
			&i.Family,
			&i.AnchorTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFwToScfEdgeContent = `-- name: SetFwToScfEdgeContent :exec
UPDATE fw_to_scf_edges
SET relationship_type = $2,
    strength          = $3,
    rationale         = $4,
    updated_at        = now()
WHERE id = $1
`

type SetFwToScfEdgeContentParams struct {
	ID               pgtype.UUID          `json:"id"`
	RelationshipType StrmRelationshipType `json:"relationship_type"`
	Strength         float64              `json:"strength"`
	Rationale        string               `json:"rationale"`
}

// Apply a reviewer's content edit. The statement writes ONLY the three STRM
// content columns the slice-536b grant widened to, plus updated_at. It never
// names framework_requirement_id, scf_anchor_id or source_attribution — and
// atlas_app is not granted UPDATE on those columns either, so invariant #7 (an
// edit can never re-point an edge) and the provenance axis are enforced at the
// database as well as here. Validation runs in Go BEFORE this executes; the
// audit row is inserted in the same tx.
func (q *Queries) SetFwToScfEdgeContent(ctx context.Context, arg SetFwToScfEdgeContentParams) error {
	_, err := q.db.Exec(ctx, setFwToScfEdgeContent,
		arg.ID,
		arg.RelationshipType,
		arg.Strength,
		arg.Rationale,
	)
	return err
}

const setFwToScfEdgeTier = `-- name: SetFwToScfEdgeTier :exec
UPDATE fw_to_scf_edges
SET mapping_tier = $2,
    updated_at   = now()
WHERE id = $1
`

type SetFwToScfEdgeTierParams struct {
	ID          pgtype.UUID          `json:"id"`
	MappingTier CrosswalkMappingTier `json:"mapping_tier"`
}

// Flip ONLY the trust tier (the narrow column-level UPDATE grant — slice 483
// D1). Legality of the move is enforced in Go (internal/crosswalktier state
// machine) BEFORE this runs; this query is the unconditional write inside the
// same tx that also inserts the audit row.
func (q *Queries) SetFwToScfEdgeTier(ctx context.Context, arg SetFwToScfEdgeTierParams) error {
	_, err := q.db.Exec(ctx, setFwToScfEdgeTier, arg.ID, arg.MappingTier)
	return err
}

const updateFrameworkVersionRequirementCount = `-- name: UpdateFrameworkVersionRequirementCount :exec
UPDATE framework_versions
SET requirement_count = $2
WHERE id = $1
`

type UpdateFrameworkVersionRequirementCountParams struct {
	ID               pgtype.UUID `json:"id"`
	RequirementCount int32       `json:"requirement_count"`
}

// Tally — the importer keeps framework_versions.requirement_count in sync
// so dashboards can show "60 controls" without a count(*).
func (q *Queries) UpdateFrameworkVersionRequirementCount(ctx context.Context, arg UpdateFrameworkVersionRequirementCountParams) error {
	_, err := q.db.Exec(ctx, updateFrameworkVersionRequirementCount, arg.ID, arg.RequirementCount)
	return err
}

const updateFwToScfEdge = `-- name: UpdateFwToScfEdge :one
UPDATE fw_to_scf_edges
SET relationship_type    = $2,
    strength             = $3,
    source_attribution   = $4,
    rationale            = $5,
    updated_at           = now()
WHERE id = $1
RETURNING id, framework_requirement_id, scf_anchor_id, relationship_type, strength, source_attribution, rationale, created_at, updated_at, mapping_tier
`

type UpdateFwToScfEdgeParams struct {
	ID                pgtype.UUID                `json:"id"`
	RelationshipType  StrmRelationshipType       `json:"relationship_type"`
	Strength          float64                    `json:"strength"`
	SourceAttribution CrosswalkSourceAttribution `json:"source_attribution"`
	Rationale         string                     `json:"rationale"`
}

// Update an existing edge in place. Importer decides whether to call this
// based on a content-equality check.
func (q *Queries) UpdateFwToScfEdge(ctx context.Context, arg UpdateFwToScfEdgeParams) (FwToScfEdge, error) {
	row := q.db.QueryRow(ctx, updateFwToScfEdge,
		arg.ID,
		arg.RelationshipType,
		arg.Strength,
		arg.SourceAttribution,
		arg.Rationale,
	)
	var i FwToScfEdge
	err := row.Scan(
		&i.ID,
		&i.FrameworkRequirementID,
		&i.ScfAnchorID,
		&i.RelationshipType,
		&i.Strength,
		&i.SourceAttribution,
		&i.Rationale,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MappingTier,
	)
	return i, err
}

const upsertFrameworkRequirement = `-- name: UpsertFrameworkRequirement :one
INSERT INTO framework_requirements (id, framework_version_id, code, title, body)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE
SET title       = EXCLUDED.title,
    body        = EXCLUDED.body,
    updated_at  = now()
RETURNING id, framework_version_id, code, title, body, created_at, updated_at
`

type UpsertFrameworkRequirementParams struct {
	ID                 pgtype.UUID `json:"id"`
	FrameworkVersionID pgtype.UUID `json:"framework_version_id"`
	Code               string      `json:"code"`
	Title              string      `json:"title"`
	Body               string      `json:"body"`
}

// Insert or update a framework_requirements row. Deterministic id derived
// from (framework_version_id, code) so re-imports are idempotent without
// relying on NULLs-distinct gotchas on the UNIQUE constraint.
func (q *Queries) UpsertFrameworkRequirement(ctx context.Context, arg UpsertFrameworkRequirementParams) (FrameworkRequirement, error) {
	row := q.db.QueryRow(ctx, upsertFrameworkRequirement,
		arg.ID,
		arg.FrameworkVersionID,
		arg.Code,
		arg.Title,
		arg.Body,
	)
	var i FrameworkRequirement
	err := row.Scan(
		&i.ID,
		&i.FrameworkVersionID,
		&i.Code,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
