// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: imported_catalogs.sql

package dbx

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const dispositionImportedComponentClaim = `-- name: DispositionImportedComponentClaim :one
UPDATE imported_component_claims
SET claim_status      = $3,
    dispositioned_by  = $4,
    dispositioned_at  = now(),
    disposition_note  = $5
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, imported_component_id, control_id, statement, requirement_uuid, scf_anchor_id, is_vendor_claim, claim_status, created_at, dispositioned_by, dispositioned_at, disposition_note
`

type DispositionImportedComponentClaimParams struct {
	TenantID        pgtype.UUID `json:"tenant_id"`
	ID              pgtype.UUID `json:"id"`
	ClaimStatus     string      `json:"claim_status"`
	DispositionedBy *string     `json:"dispositioned_by"`
	DispositionNote string      `json:"disposition_note"`
}

// Record an operator disposition on one vendor claim: set claim_status to one
// of 'accepted' / 'rejected' / 'needs_info', the disposing actor, the time,
// and an optional note. is_vendor_claim is NOT touched (a claim is always a
// claim — P0-512-1 / P0-589). This NEVER writes to control_evaluations: the
// disposition is metadata on the claim, not a control satisfaction
// (invariant #2). RLS rides the slice-512 tenant_update policy.
func (q *Queries) DispositionImportedComponentClaim(ctx context.Context, arg DispositionImportedComponentClaimParams) (ImportedComponentClaim, error) {
	row := q.db.QueryRow(ctx, dispositionImportedComponentClaim,
		arg.TenantID,
		arg.ID,
		arg.ClaimStatus,
		arg.DispositionedBy,
		arg.DispositionNote,
	)
	var i ImportedComponentClaim
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ImportedComponentID,
		&i.ControlID,
		&i.Statement,
		&i.RequirementUuid,
		&i.ScfAnchorID,
		&i.IsVendorClaim,
		&i.ClaimStatus,
		&i.CreatedAt,
		&i.DispositionedBy,
		&i.DispositionedAt,
		&i.DispositionNote,
	)
	return i, err
}

const getImportedCatalogByID = `-- name: GetImportedCatalogByID :one
SELECT id, tenant_id, source, imported_by, source_sha256, source_label, oscal_version, catalog_title, control_count, imported_at, kind, profile_title FROM imported_catalogs
WHERE tenant_id = $1 AND id = $2
`

type GetImportedCatalogByIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

// Fetch one imported catalog by id. RLS scopes to the caller's tenant; a
// cross-tenant id returns ErrNoRows.
func (q *Queries) GetImportedCatalogByID(ctx context.Context, arg GetImportedCatalogByIDParams) (ImportedCatalog, error) {
	row := q.db.QueryRow(ctx, getImportedCatalogByID, arg.TenantID, arg.ID)
	var i ImportedCatalog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Source,
		&i.ImportedBy,
		&i.SourceSha256,
		&i.SourceLabel,
		&i.OscalVersion,
		&i.CatalogTitle,
		&i.ControlCount,
		&i.ImportedAt,
		&i.Kind,
		&i.ProfileTitle,
	)
	return i, err
}

const getImportedComponentClaimByID = `-- name: GetImportedComponentClaimByID :one
SELECT id, tenant_id, imported_component_id, control_id, statement, requirement_uuid, scf_anchor_id, is_vendor_claim, claim_status, created_at, dispositioned_by, dispositioned_at, disposition_note FROM imported_component_claims
WHERE tenant_id = $1 AND id = $2
`

type GetImportedComponentClaimByIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

// Fetch one vendor claim by id (for disposition pre-read: existence + the
// current claim_status drives the from_status audit field). RLS scopes to the
// caller's tenant; a cross-tenant id returns ErrNoRows.
func (q *Queries) GetImportedComponentClaimByID(ctx context.Context, arg GetImportedComponentClaimByIDParams) (ImportedComponentClaim, error) {
	row := q.db.QueryRow(ctx, getImportedComponentClaimByID, arg.TenantID, arg.ID)
	var i ImportedComponentClaim
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ImportedComponentID,
		&i.ControlID,
		&i.Statement,
		&i.RequirementUuid,
		&i.ScfAnchorID,
		&i.IsVendorClaim,
		&i.ClaimStatus,
		&i.CreatedAt,
		&i.DispositionedBy,
		&i.DispositionedAt,
		&i.DispositionNote,
	)
	return i, err
}

const getImportedComponentDefinitionByID = `-- name: GetImportedComponentDefinitionByID :one

SELECT id, tenant_id, source, imported_by, source_sha256, source_label, oscal_version, catalog_title, control_count, imported_at, kind, profile_title FROM imported_catalogs
WHERE tenant_id = $1 AND id = $2 AND kind = 'component_definition'
`

type GetImportedComponentDefinitionByIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

// ===== slice 589: vendor-claim read + operator disposition =====
// Fetch one imported component-definition provenance row by id, confirming it
// is a component-definition (kind = 'component_definition'). RLS scopes to the
// caller's tenant; a cross-tenant or non-component-definition id returns
// ErrNoRows.
func (q *Queries) GetImportedComponentDefinitionByID(ctx context.Context, arg GetImportedComponentDefinitionByIDParams) (ImportedCatalog, error) {
	row := q.db.QueryRow(ctx, getImportedComponentDefinitionByID, arg.TenantID, arg.ID)
	var i ImportedCatalog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Source,
		&i.ImportedBy,
		&i.SourceSha256,
		&i.SourceLabel,
		&i.OscalVersion,
		&i.CatalogTitle,
		&i.ControlCount,
		&i.ImportedAt,
		&i.Kind,
		&i.ProfileTitle,
	)
	return i, err
}

const getProfileImportProvenance = `-- name: GetProfileImportProvenance :one

SELECT
    ic.id              AS baseline_id,
    ic.profile_title   AS profile_title,
    ic.source_label    AS source_label,
    ic.oscal_version   AS oscal_version,
    ic.imported_at     AS imported_at,
    al.source_sha256   AS source_sha256,
    al.occurred_at     AS occurred_at,
    al.detail          AS detail
FROM imported_catalogs ic
JOIN imported_catalog_audit_log al
    ON al.tenant_id = ic.tenant_id
   AND al.catalog_id = ic.id
   AND al.action = 'profile_imported'
WHERE ic.tenant_id = $1
  AND ic.id = $2
  AND ic.kind = 'profile'
ORDER BY al.occurred_at DESC
LIMIT 1
`

type GetProfileImportProvenanceParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

type GetProfileImportProvenanceRow struct {
	BaselineID   pgtype.UUID        `json:"baseline_id"`
	ProfileTitle string             `json:"profile_title"`
	SourceLabel  string             `json:"source_label"`
	OscalVersion string             `json:"oscal_version"`
	ImportedAt   pgtype.Timestamptz `json:"imported_at"`
	SourceSha256 string             `json:"source_sha256"`
	OccurredAt   pgtype.Timestamptz `json:"occurred_at"`
	Detail       []byte             `json:"detail"`
}

// ===== slice 599: resolved-chain provenance read =====
// Read the resolved-chain provenance for one imported PROFILE baseline. The
// chain (the ordered {role, sha256, bytes} array slice 578 records) plus
// chain_depth live in the `profile_imported` success-audit row's detail JSONB,
// keyed by catalog_id = the baseline's imported_catalogs.id. The join to
// imported_catalogs both confirms the id is a PROFILE baseline (kind =
// 'profile') and carries the baseline's display metadata for the read surface.
// RLS scopes both tables to the caller's tenant; the leading $1 tenant_id
// predicate is defense-in-depth behind RLS. A cross-tenant or non-profile id,
// or a baseline with no success-audit row, returns ErrNoRows.
func (q *Queries) GetProfileImportProvenance(ctx context.Context, arg GetProfileImportProvenanceParams) (GetProfileImportProvenanceRow, error) {
	row := q.db.QueryRow(ctx, getProfileImportProvenance, arg.TenantID, arg.ID)
	var i GetProfileImportProvenanceRow
	err := row.Scan(
		&i.BaselineID,
		&i.ProfileTitle,
		&i.SourceLabel,
		&i.OscalVersion,
		&i.ImportedAt,
		&i.SourceSha256,
		&i.OccurredAt,
		&i.Detail,
	)
	return i, err
}

const insertImportedCatalog = `-- name: InsertImportedCatalog :one

INSERT INTO imported_catalogs
    (id, tenant_id, imported_by, source_sha256, source_label, oscal_version, catalog_title, control_count)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, source, imported_by, source_sha256, source_label, oscal_version, catalog_title, control_count, imported_at, kind, profile_title
`

type InsertImportedCatalogParams struct {
	ID           pgtype.UUID `json:"id"`
	TenantID     pgtype.UUID `json:"tenant_id"`
	ImportedBy   string      `json:"imported_by"`
	SourceSha256 string      `json:"source_sha256"`
	SourceLabel  string      `json:"source_label"`
	OscalVersion string      `json:"oscal_version"`
	CatalogTitle string      `json:"catalog_title"`
	ControlCount int32       `json:"control_count"`
}

// Slice 492: OSCAL catalog-import queries.
//
// CRUD against the three new tables (imported_catalogs,
// imported_catalog_controls, imported_catalog_audit_log). Every query is
// tenant-bound via the leading $1 parameter (defense-in-depth behind RLS).
// The importer (internal/oscal/catalogimport) runs these inside ONE
// transaction under app.current_tenant so the import is atomic (AC-5).
// Create one imported-catalog provenance row. source defaults to
// 'oscal-import' (the table default) and is not set here.
func (q *Queries) InsertImportedCatalog(ctx context.Context, arg InsertImportedCatalogParams) (ImportedCatalog, error) {
	row := q.db.QueryRow(ctx, insertImportedCatalog,
		arg.ID,
		arg.TenantID,
		arg.ImportedBy,
		arg.SourceSha256,
		arg.SourceLabel,
		arg.OscalVersion,
		arg.CatalogTitle,
		arg.ControlCount,
	)
	var i ImportedCatalog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Source,
		&i.ImportedBy,
		&i.SourceSha256,
		&i.SourceLabel,
		&i.OscalVersion,
		&i.CatalogTitle,
		&i.ControlCount,
		&i.ImportedAt,
		&i.Kind,
		&i.ProfileTitle,
	)
	return i, err
}

const insertImportedCatalogAuditLog = `-- name: InsertImportedCatalogAuditLog :one
INSERT INTO imported_catalog_audit_log
    (id, tenant_id, catalog_id, action, actor, source_sha256, source_label, control_count, detail)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, catalog_id, action, actor, source_sha256, source_label, control_count, detail, occurred_at
`

type InsertImportedCatalogAuditLogParams struct {
	ID           pgtype.UUID `json:"id"`
	TenantID     pgtype.UUID `json:"tenant_id"`
	CatalogID    pgtype.UUID `json:"catalog_id"`
	Action       string      `json:"action"`
	Actor        string      `json:"actor"`
	SourceSha256 string      `json:"source_sha256"`
	SourceLabel  string      `json:"source_label"`
	ControlCount int32       `json:"control_count"`
	Detail       []byte      `json:"detail"`
}

// Append one append-only import audit row (AC-7). Written on success
// ('catalog_imported' / 'profile_imported') and on rejection
// ('import_rejected' / 'profile_import_rejected').
func (q *Queries) InsertImportedCatalogAuditLog(ctx context.Context, arg InsertImportedCatalogAuditLogParams) (ImportedCatalogAuditLog, error) {
	row := q.db.QueryRow(ctx, insertImportedCatalogAuditLog,
		arg.ID,
		arg.TenantID,
		arg.CatalogID,
		arg.Action,
		arg.Actor,
		arg.SourceSha256,
		arg.SourceLabel,
		arg.ControlCount,
		arg.Detail,
	)
	var i ImportedCatalogAuditLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CatalogID,
		&i.Action,
		&i.Actor,
		&i.SourceSha256,
		&i.SourceLabel,
		&i.ControlCount,
		&i.Detail,
		&i.OccurredAt,
	)
	return i, err
}

const insertImportedCatalogControl = `-- name: InsertImportedCatalogControl :one
INSERT INTO imported_catalog_controls
    (id, tenant_id, imported_catalog_id, source_control_id, title, statement, group_path, scf_anchor_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, imported_catalog_id, source_control_id, title, statement, group_path, scf_anchor_id, created_at
`

type InsertImportedCatalogControlParams struct {
	ID                pgtype.UUID `json:"id"`
	TenantID          pgtype.UUID `json:"tenant_id"`
	ImportedCatalogID pgtype.UUID `json:"imported_catalog_id"`
	SourceControlID   string      `json:"source_control_id"`
	Title             string      `json:"title"`
	Statement         string      `json:"statement"`
	GroupPath         string      `json:"group_path"`
	ScfAnchorID       *string     `json:"scf_anchor_id"`
}

// Append one imported control mapped (or flagged NULL for mapping) to an
// SCF anchor. The (imported_catalog_id, source_control_id) UNIQUE
// constraint rejects a duplicate control within one catalog.
func (q *Queries) InsertImportedCatalogControl(ctx context.Context, arg InsertImportedCatalogControlParams) (ImportedCatalogControl, error) {
	row := q.db.QueryRow(ctx, insertImportedCatalogControl,
		arg.ID,
		arg.TenantID,
		arg.ImportedCatalogID,
		arg.SourceControlID,
		arg.Title,
		arg.Statement,
		arg.GroupPath,
		arg.ScfAnchorID,
	)
	var i ImportedCatalogControl
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ImportedCatalogID,
		&i.SourceControlID,
		&i.Title,
		&i.Statement,
		&i.GroupPath,
		&i.ScfAnchorID,
		&i.CreatedAt,
	)
	return i, err
}

const insertImportedComponent = `-- name: InsertImportedComponent :one
INSERT INTO imported_components
    (id, tenant_id, imported_catalog_id, component_uuid, component_type, title, description)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, imported_catalog_id, component_uuid, component_type, title, description, created_at
`

type InsertImportedComponentParams struct {
	ID                pgtype.UUID `json:"id"`
	TenantID          pgtype.UUID `json:"tenant_id"`
	ImportedCatalogID pgtype.UUID `json:"imported_catalog_id"`
	ComponentUuid     string      `json:"component_uuid"`
	ComponentType     string      `json:"component_type"`
	Title             string      `json:"title"`
	Description       string      `json:"description"`
}

// Append one defined-component for an imported component-definition. The
// (imported_catalog_id, component_uuid) UNIQUE constraint rejects a duplicate
// component within one import.
func (q *Queries) InsertImportedComponent(ctx context.Context, arg InsertImportedComponentParams) (ImportedComponent, error) {
	row := q.db.QueryRow(ctx, insertImportedComponent,
		arg.ID,
		arg.TenantID,
		arg.ImportedCatalogID,
		arg.ComponentUuid,
		arg.ComponentType,
		arg.Title,
		arg.Description,
	)
	var i ImportedComponent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ImportedCatalogID,
		&i.ComponentUuid,
		&i.ComponentType,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const insertImportedComponentClaim = `-- name: InsertImportedComponentClaim :one
INSERT INTO imported_component_claims
    (id, tenant_id, imported_component_id, control_id, statement, requirement_uuid, scf_anchor_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, imported_component_id, control_id, statement, requirement_uuid, scf_anchor_id, is_vendor_claim, claim_status, created_at, dispositioned_by, dispositioned_at, disposition_note
`

type InsertImportedComponentClaimParams struct {
	ID                  pgtype.UUID `json:"id"`
	TenantID            pgtype.UUID `json:"tenant_id"`
	ImportedComponentID pgtype.UUID `json:"imported_component_id"`
	ControlID           string      `json:"control_id"`
	Statement           string      `json:"statement"`
	RequirementUuid     string      `json:"requirement_uuid"`
	ScfAnchorID         *string     `json:"scf_anchor_id"`
}

// Append one vendor-attributed CLAIM (an implemented-requirement) mapped (or
// flagged NULL for mapping) to an SCF anchor. is_vendor_claim defaults TRUE
// and claim_status defaults 'asserted' (the table defaults) — the import never
// writes anything else (P0-512-1).
func (q *Queries) InsertImportedComponentClaim(ctx context.Context, arg InsertImportedComponentClaimParams) (ImportedComponentClaim, error) {
	row := q.db.QueryRow(ctx, insertImportedComponentClaim,
		arg.ID,
		arg.TenantID,
		arg.ImportedComponentID,
		arg.ControlID,
		arg.Statement,
		arg.RequirementUuid,
		arg.ScfAnchorID,
	)
	var i ImportedComponentClaim
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ImportedComponentID,
		&i.ControlID,
		&i.Statement,
		&i.RequirementUuid,
		&i.ScfAnchorID,
		&i.IsVendorClaim,
		&i.ClaimStatus,
		&i.CreatedAt,
		&i.DispositionedBy,
		&i.DispositionedAt,
		&i.DispositionNote,
	)
	return i, err
}

const insertImportedComponentClaimDisposition = `-- name: InsertImportedComponentClaimDisposition :one
INSERT INTO imported_component_claim_dispositions
    (id, tenant_id, claim_id, from_status, to_status, actor, note)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, claim_id, from_status, to_status, actor, note, occurred_at, event_kind, from_scf_anchor_id, to_scf_anchor_id
`

type InsertImportedComponentClaimDispositionParams struct {
	ID         pgtype.UUID `json:"id"`
	TenantID   pgtype.UUID `json:"tenant_id"`
	ClaimID    pgtype.UUID `json:"claim_id"`
	FromStatus string      `json:"from_status"`
	ToStatus   string      `json:"to_status"`
	Actor      string      `json:"actor"`
	Note       string      `json:"note"`
}

// Append one append-only disposition-audit row recording the
// from_status -> to_status transition, the actor, and an optional note.
func (q *Queries) InsertImportedComponentClaimDisposition(ctx context.Context, arg InsertImportedComponentClaimDispositionParams) (ImportedComponentClaimDisposition, error) {
	row := q.db.QueryRow(ctx, insertImportedComponentClaimDisposition,
		arg.ID,
		arg.TenantID,
		arg.ClaimID,
		arg.FromStatus,
		arg.ToStatus,
		arg.Actor,
		arg.Note,
	)
	var i ImportedComponentClaimDisposition
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClaimID,
		&i.FromStatus,
		&i.ToStatus,
		&i.Actor,
		&i.Note,
		&i.OccurredAt,
		&i.EventKind,
		&i.FromScfAnchorID,
		&i.ToScfAnchorID,
	)
	return i, err
}

const insertImportedComponentClaimScfMapping = `-- name: InsertImportedComponentClaimScfMapping :one
INSERT INTO imported_component_claim_dispositions
    (id, tenant_id, claim_id, event_kind, from_status, to_status,
     from_scf_anchor_id, to_scf_anchor_id, actor, note)
VALUES ($1, $2, $3, 'scf_mapping', '', '', $4, $5, $6, $7)
RETURNING id, tenant_id, claim_id, from_status, to_status, actor, note, occurred_at, event_kind, from_scf_anchor_id, to_scf_anchor_id
`

type InsertImportedComponentClaimScfMappingParams struct {
	ID              pgtype.UUID `json:"id"`
	TenantID        pgtype.UUID `json:"tenant_id"`
	ClaimID         pgtype.UUID `json:"claim_id"`
	FromScfAnchorID *string     `json:"from_scf_anchor_id"`
	ToScfAnchorID   *string     `json:"to_scf_anchor_id"`
	Actor           string      `json:"actor"`
	Note            string      `json:"note"`
}

// Append one append-only mapping-audit row recording the
// from_scf_anchor_id -> to_scf_anchor_id transition, the actor, and an
// optional note. REUSES the slice-589 imported_component_claim_dispositions
// table generalized into a claim EVENT log (event_kind='scf_mapping'); the
// status columns are ” sentinels for a mapping event (the slice-620
// iccd_to_status_chk only constrains them for 'disposition' events).
func (q *Queries) InsertImportedComponentClaimScfMapping(ctx context.Context, arg InsertImportedComponentClaimScfMappingParams) (ImportedComponentClaimDisposition, error) {
	row := q.db.QueryRow(ctx, insertImportedComponentClaimScfMapping,
		arg.ID,
		arg.TenantID,
		arg.ClaimID,
		arg.FromScfAnchorID,
		arg.ToScfAnchorID,
		arg.Actor,
		arg.Note,
	)
	var i ImportedComponentClaimDisposition
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClaimID,
		&i.FromStatus,
		&i.ToStatus,
		&i.Actor,
		&i.Note,
		&i.OccurredAt,
		&i.EventKind,
		&i.FromScfAnchorID,
		&i.ToScfAnchorID,
	)
	return i, err
}

const insertImportedComponentDefinition = `-- name: InsertImportedComponentDefinition :one

INSERT INTO imported_catalogs
    (id, tenant_id, source, kind, imported_by, source_sha256, source_label,
     oscal_version, catalog_title, control_count)
VALUES ($1, $2, 'oscal-component-import', 'component_definition', $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, source, imported_by, source_sha256, source_label, oscal_version, catalog_title, control_count, imported_at, kind, profile_title
`

type InsertImportedComponentDefinitionParams struct {
	ID           pgtype.UUID `json:"id"`
	TenantID     pgtype.UUID `json:"tenant_id"`
	ImportedBy   string      `json:"imported_by"`
	SourceSha256 string      `json:"source_sha256"`
	SourceLabel  string      `json:"source_label"`
	OscalVersion string      `json:"oscal_version"`
	CatalogTitle string      `json:"catalog_title"`
	ControlCount int32       `json:"control_count"`
}

// ===== slice 512: component-definition import (vendor-claim ingest) =====
// Create one imported-COMPONENT-DEFINITION provenance row: source
// 'oscal-component-import', kind 'component_definition'. The vendor/product
// label rides in source_label and the document title in catalog_title; the
// per-component + per-claim rows live in imported_components +
// imported_component_claims (slice-512 D1/D2). control_count carries the
// TOTAL vendor-claim count across all components (for provenance display).
func (q *Queries) InsertImportedComponentDefinition(ctx context.Context, arg InsertImportedComponentDefinitionParams) (ImportedCatalog, error) {
	row := q.db.QueryRow(ctx, insertImportedComponentDefinition,
		arg.ID,
		arg.TenantID,
		arg.ImportedBy,
		arg.SourceSha256,
		arg.SourceLabel,
		arg.OscalVersion,
		arg.CatalogTitle,
		arg.ControlCount,
	)
	var i ImportedCatalog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Source,
		&i.ImportedBy,
		&i.SourceSha256,
		&i.SourceLabel,
		&i.OscalVersion,
		&i.CatalogTitle,
		&i.ControlCount,
		&i.ImportedAt,
		&i.Kind,
		&i.ProfileTitle,
	)
	return i, err
}

const insertImportedProfile = `-- name: InsertImportedProfile :one

INSERT INTO imported_catalogs
    (id, tenant_id, source, kind, imported_by, source_sha256, source_label,
     oscal_version, catalog_title, profile_title, control_count)
VALUES ($1, $2, 'oscal-profile-import', 'profile', $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, source, imported_by, source_sha256, source_label, oscal_version, catalog_title, control_count, imported_at, kind, profile_title
`

type InsertImportedProfileParams struct {
	ID           pgtype.UUID `json:"id"`
	TenantID     pgtype.UUID `json:"tenant_id"`
	ImportedBy   string      `json:"imported_by"`
	SourceSha256 string      `json:"source_sha256"`
	SourceLabel  string      `json:"source_label"`
	OscalVersion string      `json:"oscal_version"`
	CatalogTitle string      `json:"catalog_title"`
	ProfileTitle string      `json:"profile_title"`
	ControlCount int32       `json:"control_count"`
}

// ===== slice 511: profile import (resolve direction) =====
// Create one imported-PROFILE provenance row: source 'oscal-profile-import',
// kind 'profile', carrying the resolved profile's declared title. The
// resolved baseline is, structurally, an imported control set distinguished
// from a catalog import by (source, kind) — slice-511 D4.
func (q *Queries) InsertImportedProfile(ctx context.Context, arg InsertImportedProfileParams) (ImportedCatalog, error) {
	row := q.db.QueryRow(ctx, insertImportedProfile,
		arg.ID,
		arg.TenantID,
		arg.ImportedBy,
		arg.SourceSha256,
		arg.SourceLabel,
		arg.OscalVersion,
		arg.CatalogTitle,
		arg.ProfileTitle,
		arg.ControlCount,
	)
	var i ImportedCatalog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Source,
		&i.ImportedBy,
		&i.SourceSha256,
		&i.SourceLabel,
		&i.OscalVersion,
		&i.CatalogTitle,
		&i.ControlCount,
		&i.ImportedAt,
		&i.Kind,
		&i.ProfileTitle,
	)
	return i, err
}

const listImportedCatalogControls = `-- name: ListImportedCatalogControls :many
SELECT id, tenant_id, imported_catalog_id, source_control_id, title, statement, group_path, scf_anchor_id, created_at FROM imported_catalog_controls
WHERE tenant_id = $1 AND imported_catalog_id = $2
ORDER BY group_path ASC, source_control_id ASC
`

type ListImportedCatalogControlsParams struct {
	TenantID          pgtype.UUID `json:"tenant_id"`
	ImportedCatalogID pgtype.UUID `json:"imported_catalog_id"`
}

// Every control for one imported catalog, ordered for stable rendering.
func (q *Queries) ListImportedCatalogControls(ctx context.Context, arg ListImportedCatalogControlsParams) ([]ImportedCatalogControl, error) {
	rows, err := q.db.Query(ctx, listImportedCatalogControls, arg.TenantID, arg.ImportedCatalogID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportedCatalogControl
	for rows.Next() {
		var i ImportedCatalogControl
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ImportedCatalogID,
			&i.SourceControlID,
			&i.Title,
			&i.Statement,
			&i.GroupPath,
			&i.ScfAnchorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportedCatalogs = `-- name: ListImportedCatalogs :many
SELECT id, tenant_id, source, imported_by, source_sha256, source_label, oscal_version, catalog_title, control_count, imported_at, kind, profile_title FROM imported_catalogs
WHERE tenant_id = $1
ORDER BY imported_at DESC, id ASC
`

// Enumerate every imported catalog for the tenant, most recent first.
func (q *Queries) ListImportedCatalogs(ctx context.Context, tenantID pgtype.UUID) ([]ImportedCatalog, error) {
	rows, err := q.db.Query(ctx, listImportedCatalogs, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportedCatalog
	for rows.Next() {
		var i ImportedCatalog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Source,
			&i.ImportedBy,
			&i.SourceSha256,
			&i.SourceLabel,
			&i.OscalVersion,
			&i.CatalogTitle,
			&i.ControlCount,
			&i.ImportedAt,
			&i.Kind,
			&i.ProfileTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportedComponentClaimDispositions = `-- name: ListImportedComponentClaimDispositions :many
SELECT id, tenant_id, claim_id, from_status, to_status, actor, note, occurred_at, event_kind, from_scf_anchor_id, to_scf_anchor_id FROM imported_component_claim_dispositions
WHERE tenant_id = $1 AND claim_id = $2
ORDER BY occurred_at DESC, id ASC
`

type ListImportedComponentClaimDispositionsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ClaimID  pgtype.UUID `json:"claim_id"`
}

// The append-only disposition history for one vendor claim, most recent
// first.
func (q *Queries) ListImportedComponentClaimDispositions(ctx context.Context, arg ListImportedComponentClaimDispositionsParams) ([]ImportedComponentClaimDisposition, error) {
	rows, err := q.db.Query(ctx, listImportedComponentClaimDispositions, arg.TenantID, arg.ClaimID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportedComponentClaimDisposition
	for rows.Next() {
		var i ImportedComponentClaimDisposition
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ClaimID,
			&i.FromStatus,
			&i.ToStatus,
			&i.Actor,
			&i.Note,
			&i.OccurredAt,
			&i.EventKind,
			&i.FromScfAnchorID,
			&i.ToScfAnchorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportedComponentClaims = `-- name: ListImportedComponentClaims :many
SELECT id, tenant_id, imported_component_id, control_id, statement, requirement_uuid, scf_anchor_id, is_vendor_claim, claim_status, created_at, dispositioned_by, dispositioned_at, disposition_note FROM imported_component_claims
WHERE tenant_id = $1 AND imported_component_id = $2
ORDER BY control_id ASC, requirement_uuid ASC
`

type ListImportedComponentClaimsParams struct {
	TenantID            pgtype.UUID `json:"tenant_id"`
	ImportedComponentID pgtype.UUID `json:"imported_component_id"`
}

// Every vendor claim for one imported component, ordered for stable
// rendering.
func (q *Queries) ListImportedComponentClaims(ctx context.Context, arg ListImportedComponentClaimsParams) ([]ImportedComponentClaim, error) {
	rows, err := q.db.Query(ctx, listImportedComponentClaims, arg.TenantID, arg.ImportedComponentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportedComponentClaim
	for rows.Next() {
		var i ImportedComponentClaim
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ImportedComponentID,
			&i.ControlID,
			&i.Statement,
			&i.RequirementUuid,
			&i.ScfAnchorID,
			&i.IsVendorClaim,
			&i.ClaimStatus,
			&i.CreatedAt,
			&i.DispositionedBy,
			&i.DispositionedAt,
			&i.DispositionNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportedComponentClaimsForDefinition = `-- name: ListImportedComponentClaimsForDefinition :many
SELECT
    cc.id                    AS claim_id,
    cc.imported_component_id AS imported_component_id,
    cmp.component_uuid       AS component_uuid,
    cmp.title                AS component_title,
    cmp.component_type       AS component_type,
    cc.control_id            AS control_id,
    cc.statement             AS statement,
    cc.requirement_uuid      AS requirement_uuid,
    cc.scf_anchor_id         AS scf_anchor_id,
    cc.is_vendor_claim       AS is_vendor_claim,
    cc.claim_status          AS claim_status,
    cc.dispositioned_by      AS dispositioned_by,
    cc.dispositioned_at      AS dispositioned_at,
    cc.disposition_note      AS disposition_note,
    cc.created_at            AS created_at
FROM imported_component_claims cc
JOIN imported_components cmp
    ON cmp.id = cc.imported_component_id
   AND cmp.tenant_id = cc.tenant_id
WHERE cc.tenant_id = $1
  AND cmp.imported_catalog_id = $2
ORDER BY cmp.title ASC, cmp.component_uuid ASC, cc.control_id ASC, cc.requirement_uuid ASC
`

type ListImportedComponentClaimsForDefinitionParams struct {
	TenantID          pgtype.UUID `json:"tenant_id"`
	ImportedCatalogID pgtype.UUID `json:"imported_catalog_id"`
}

type ListImportedComponentClaimsForDefinitionRow struct {
	ClaimID             pgtype.UUID        `json:"claim_id"`
	ImportedComponentID pgtype.UUID        `json:"imported_component_id"`
	ComponentUuid       string             `json:"component_uuid"`
	ComponentTitle      string             `json:"component_title"`
	ComponentType       string             `json:"component_type"`
	ControlID           string             `json:"control_id"`
	Statement           string             `json:"statement"`
	RequirementUuid     string             `json:"requirement_uuid"`
	ScfAnchorID         *string            `json:"scf_anchor_id"`
	IsVendorClaim       bool               `json:"is_vendor_claim"`
	ClaimStatus         string             `json:"claim_status"`
	DispositionedBy     *string            `json:"dispositioned_by"`
	DispositionedAt     pgtype.Timestamptz `json:"dispositioned_at"`
	DispositionNote     string             `json:"disposition_note"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

// Every vendor claim across every component of one imported
// component-definition, joined to the component for display. Ordered for
// stable rendering. RLS scopes both tables to the caller's tenant; the
// leading $1 tenant_id predicate is defense-in-depth behind RLS.
func (q *Queries) ListImportedComponentClaimsForDefinition(ctx context.Context, arg ListImportedComponentClaimsForDefinitionParams) ([]ListImportedComponentClaimsForDefinitionRow, error) {
	rows, err := q.db.Query(ctx, listImportedComponentClaimsForDefinition, arg.TenantID, arg.ImportedCatalogID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListImportedComponentClaimsForDefinitionRow
	for rows.Next() {
		var i ListImportedComponentClaimsForDefinitionRow
		if err := rows.Scan(
			&i.ClaimID,
			&i.ImportedComponentID,
			&i.ComponentUuid,
			&i.ComponentTitle,
			&i.ComponentType,
			&i.ControlID,
			&i.Statement,
			&i.RequirementUuid,
			&i.ScfAnchorID,
			&i.IsVendorClaim,
			&i.ClaimStatus,
			&i.DispositionedBy,
			&i.DispositionedAt,
			&i.DispositionNote,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportedComponentDefinitions = `-- name: ListImportedComponentDefinitions :many
SELECT id, tenant_id, source, imported_by, source_sha256, source_label, oscal_version, catalog_title, control_count, imported_at, kind, profile_title FROM imported_catalogs
WHERE tenant_id = $1 AND kind = 'component_definition'
ORDER BY imported_at DESC, id ASC
`

// Enumerate every imported component-definition for the tenant, most recent
// first (index-served by idx_imported_catalogs_tenant_components).
func (q *Queries) ListImportedComponentDefinitions(ctx context.Context, tenantID pgtype.UUID) ([]ImportedCatalog, error) {
	rows, err := q.db.Query(ctx, listImportedComponentDefinitions, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportedCatalog
	for rows.Next() {
		var i ImportedCatalog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Source,
			&i.ImportedBy,
			&i.SourceSha256,
			&i.SourceLabel,
			&i.OscalVersion,
			&i.CatalogTitle,
			&i.ControlCount,
			&i.ImportedAt,
			&i.Kind,
			&i.ProfileTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportedComponentsForDefinition = `-- name: ListImportedComponentsForDefinition :many
SELECT id, tenant_id, imported_catalog_id, component_uuid, component_type, title, description, created_at FROM imported_components
WHERE tenant_id = $1 AND imported_catalog_id = $2
ORDER BY title ASC, component_uuid ASC
`

type ListImportedComponentsForDefinitionParams struct {
	TenantID          pgtype.UUID `json:"tenant_id"`
	ImportedCatalogID pgtype.UUID `json:"imported_catalog_id"`
}

// Every defined-component for one imported component-definition, ordered for
// stable rendering.
func (q *Queries) ListImportedComponentsForDefinition(ctx context.Context, arg ListImportedComponentsForDefinitionParams) ([]ImportedComponent, error) {
	rows, err := q.db.Query(ctx, listImportedComponentsForDefinition, arg.TenantID, arg.ImportedCatalogID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportedComponent
	for rows.Next() {
		var i ImportedComponent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ImportedCatalogID,
			&i.ComponentUuid,
			&i.ComponentType,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportedProfiles = `-- name: ListImportedProfiles :many
SELECT id, tenant_id, source, imported_by, source_sha256, source_label, oscal_version, catalog_title, control_count, imported_at, kind, profile_title FROM imported_catalogs
WHERE tenant_id = $1 AND kind = 'profile'
ORDER BY imported_at DESC, id ASC
`

// Enumerate every resolved profile baseline for the tenant, most recent
// first (index-served by idx_imported_catalogs_tenant_profiles).
func (q *Queries) ListImportedProfiles(ctx context.Context, tenantID pgtype.UUID) ([]ImportedCatalog, error) {
	rows, err := q.db.Query(ctx, listImportedProfiles, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportedCatalog
	for rows.Next() {
		var i ImportedCatalog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Source,
			&i.ImportedBy,
			&i.SourceSha256,
			&i.SourceLabel,
			&i.OscalVersion,
			&i.CatalogTitle,
			&i.ControlCount,
			&i.ImportedAt,
			&i.Kind,
			&i.ProfileTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mapImportedComponentClaimScfAnchor = `-- name: MapImportedComponentClaimScfAnchor :one

UPDATE imported_component_claims
SET scf_anchor_id = $3
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, imported_component_id, control_id, statement, requirement_uuid, scf_anchor_id, is_vendor_claim, claim_status, created_at, dispositioned_by, dispositioned_at, disposition_note
`

type MapImportedComponentClaimScfAnchorParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	ID          pgtype.UUID `json:"id"`
	ScfAnchorID *string     `json:"scf_anchor_id"`
}

// ===== slice 620: operator maps an unmapped claim to an SCF anchor =====
// Set one vendor claim's scf_anchor_id (the human-approved crosswalk). This
// maps a claim's target requirement TO an SCF anchor's scf_id (requirement ->
// SCF anchor only, invariant #7) — it is NOT a claim -> claim mapping and does
// NOT touch control_evaluations or the evidence ledger (the claim stays a
// claim; mapping only sets the crosswalk — invariant #2 / P0-512-1).
// is_vendor_claim + claim_status are NOT touched. RLS rides the slice-512
// tenant_update policy.
func (q *Queries) MapImportedComponentClaimScfAnchor(ctx context.Context, arg MapImportedComponentClaimScfAnchorParams) (ImportedComponentClaim, error) {
	row := q.db.QueryRow(ctx, mapImportedComponentClaimScfAnchor, arg.TenantID, arg.ID, arg.ScfAnchorID)
	var i ImportedComponentClaim
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ImportedComponentID,
		&i.ControlID,
		&i.Statement,
		&i.RequirementUuid,
		&i.ScfAnchorID,
		&i.IsVendorClaim,
		&i.ClaimStatus,
		&i.CreatedAt,
		&i.DispositionedBy,
		&i.DispositionedAt,
		&i.DispositionNote,
	)
	return i, err
}
