// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: imported_catalogs.sql

package dbx

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getImportedCatalogByID = `-- name: GetImportedCatalogByID :one
SELECT id, tenant_id, source, imported_by, source_sha256, source_label, oscal_version, catalog_title, control_count, imported_at, kind, profile_title FROM imported_catalogs
WHERE tenant_id = $1 AND id = $2
`

type GetImportedCatalogByIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

// Fetch one imported catalog by id. RLS scopes to the caller's tenant; a
// cross-tenant id returns ErrNoRows.
func (q *Queries) GetImportedCatalogByID(ctx context.Context, arg GetImportedCatalogByIDParams) (ImportedCatalog, error) {
	row := q.db.QueryRow(ctx, getImportedCatalogByID, arg.TenantID, arg.ID)
	var i ImportedCatalog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Source,
		&i.ImportedBy,
		&i.SourceSha256,
		&i.SourceLabel,
		&i.OscalVersion,
		&i.CatalogTitle,
		&i.ControlCount,
		&i.ImportedAt,
		&i.Kind,
		&i.ProfileTitle,
	)
	return i, err
}

const insertImportedCatalog = `-- name: InsertImportedCatalog :one

INSERT INTO imported_catalogs
    (id, tenant_id, imported_by, source_sha256, source_label, oscal_version, catalog_title, control_count)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, source, imported_by, source_sha256, source_label, oscal_version, catalog_title, control_count, imported_at, kind, profile_title
`

type InsertImportedCatalogParams struct {
	ID           pgtype.UUID `json:"id"`
	TenantID     pgtype.UUID `json:"tenant_id"`
	ImportedBy   string      `json:"imported_by"`
	SourceSha256 string      `json:"source_sha256"`
	SourceLabel  string      `json:"source_label"`
	OscalVersion string      `json:"oscal_version"`
	CatalogTitle string      `json:"catalog_title"`
	ControlCount int32       `json:"control_count"`
}

// Slice 492: OSCAL catalog-import queries.
//
// CRUD against the three new tables (imported_catalogs,
// imported_catalog_controls, imported_catalog_audit_log). Every query is
// tenant-bound via the leading $1 parameter (defense-in-depth behind RLS).
// The importer (internal/oscal/catalogimport) runs these inside ONE
// transaction under app.current_tenant so the import is atomic (AC-5).
// Create one imported-catalog provenance row. source defaults to
// 'oscal-import' (the table default) and is not set here.
func (q *Queries) InsertImportedCatalog(ctx context.Context, arg InsertImportedCatalogParams) (ImportedCatalog, error) {
	row := q.db.QueryRow(ctx, insertImportedCatalog,
		arg.ID,
		arg.TenantID,
		arg.ImportedBy,
		arg.SourceSha256,
		arg.SourceLabel,
		arg.OscalVersion,
		arg.CatalogTitle,
		arg.ControlCount,
	)
	var i ImportedCatalog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Source,
		&i.ImportedBy,
		&i.SourceSha256,
		&i.SourceLabel,
		&i.OscalVersion,
		&i.CatalogTitle,
		&i.ControlCount,
		&i.ImportedAt,
		&i.Kind,
		&i.ProfileTitle,
	)
	return i, err
}

const insertImportedCatalogAuditLog = `-- name: InsertImportedCatalogAuditLog :one
INSERT INTO imported_catalog_audit_log
    (id, tenant_id, catalog_id, action, actor, source_sha256, source_label, control_count, detail)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, catalog_id, action, actor, source_sha256, source_label, control_count, detail, occurred_at
`

type InsertImportedCatalogAuditLogParams struct {
	ID           pgtype.UUID `json:"id"`
	TenantID     pgtype.UUID `json:"tenant_id"`
	CatalogID    pgtype.UUID `json:"catalog_id"`
	Action       string      `json:"action"`
	Actor        string      `json:"actor"`
	SourceSha256 string      `json:"source_sha256"`
	SourceLabel  string      `json:"source_label"`
	ControlCount int32       `json:"control_count"`
	Detail       []byte      `json:"detail"`
}

// Append one append-only import audit row (AC-7). Written on success
// ('catalog_imported' / 'profile_imported') and on rejection
// ('import_rejected' / 'profile_import_rejected').
func (q *Queries) InsertImportedCatalogAuditLog(ctx context.Context, arg InsertImportedCatalogAuditLogParams) (ImportedCatalogAuditLog, error) {
	row := q.db.QueryRow(ctx, insertImportedCatalogAuditLog,
		arg.ID,
		arg.TenantID,
		arg.CatalogID,
		arg.Action,
		arg.Actor,
		arg.SourceSha256,
		arg.SourceLabel,
		arg.ControlCount,
		arg.Detail,
	)
	var i ImportedCatalogAuditLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CatalogID,
		&i.Action,
		&i.Actor,
		&i.SourceSha256,
		&i.SourceLabel,
		&i.ControlCount,
		&i.Detail,
		&i.OccurredAt,
	)
	return i, err
}

const insertImportedCatalogControl = `-- name: InsertImportedCatalogControl :one
INSERT INTO imported_catalog_controls
    (id, tenant_id, imported_catalog_id, source_control_id, title, statement, group_path, scf_anchor_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, imported_catalog_id, source_control_id, title, statement, group_path, scf_anchor_id, created_at
`

type InsertImportedCatalogControlParams struct {
	ID                pgtype.UUID `json:"id"`
	TenantID          pgtype.UUID `json:"tenant_id"`
	ImportedCatalogID pgtype.UUID `json:"imported_catalog_id"`
	SourceControlID   string      `json:"source_control_id"`
	Title             string      `json:"title"`
	Statement         string      `json:"statement"`
	GroupPath         string      `json:"group_path"`
	ScfAnchorID       *string     `json:"scf_anchor_id"`
}

// Append one imported control mapped (or flagged NULL for mapping) to an
// SCF anchor. The (imported_catalog_id, source_control_id) UNIQUE
// constraint rejects a duplicate control within one catalog.
func (q *Queries) InsertImportedCatalogControl(ctx context.Context, arg InsertImportedCatalogControlParams) (ImportedCatalogControl, error) {
	row := q.db.QueryRow(ctx, insertImportedCatalogControl,
		arg.ID,
		arg.TenantID,
		arg.ImportedCatalogID,
		arg.SourceControlID,
		arg.Title,
		arg.Statement,
		arg.GroupPath,
		arg.ScfAnchorID,
	)
	var i ImportedCatalogControl
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ImportedCatalogID,
		&i.SourceControlID,
		&i.Title,
		&i.Statement,
		&i.GroupPath,
		&i.ScfAnchorID,
		&i.CreatedAt,
	)
	return i, err
}

const insertImportedProfile = `-- name: InsertImportedProfile :one

INSERT INTO imported_catalogs
    (id, tenant_id, source, kind, imported_by, source_sha256, source_label,
     oscal_version, catalog_title, profile_title, control_count)
VALUES ($1, $2, 'oscal-profile-import', 'profile', $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, source, imported_by, source_sha256, source_label, oscal_version, catalog_title, control_count, imported_at, kind, profile_title
`

type InsertImportedProfileParams struct {
	ID           pgtype.UUID `json:"id"`
	TenantID     pgtype.UUID `json:"tenant_id"`
	ImportedBy   string      `json:"imported_by"`
	SourceSha256 string      `json:"source_sha256"`
	SourceLabel  string      `json:"source_label"`
	OscalVersion string      `json:"oscal_version"`
	CatalogTitle string      `json:"catalog_title"`
	ProfileTitle string      `json:"profile_title"`
	ControlCount int32       `json:"control_count"`
}

// ===== slice 511: profile import (resolve direction) =====
// Create one imported-PROFILE provenance row: source 'oscal-profile-import',
// kind 'profile', carrying the resolved profile's declared title. The
// resolved baseline is, structurally, an imported control set distinguished
// from a catalog import by (source, kind) — slice-511 D4.
func (q *Queries) InsertImportedProfile(ctx context.Context, arg InsertImportedProfileParams) (ImportedCatalog, error) {
	row := q.db.QueryRow(ctx, insertImportedProfile,
		arg.ID,
		arg.TenantID,
		arg.ImportedBy,
		arg.SourceSha256,
		arg.SourceLabel,
		arg.OscalVersion,
		arg.CatalogTitle,
		arg.ProfileTitle,
		arg.ControlCount,
	)
	var i ImportedCatalog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Source,
		&i.ImportedBy,
		&i.SourceSha256,
		&i.SourceLabel,
		&i.OscalVersion,
		&i.CatalogTitle,
		&i.ControlCount,
		&i.ImportedAt,
		&i.Kind,
		&i.ProfileTitle,
	)
	return i, err
}

const listImportedCatalogControls = `-- name: ListImportedCatalogControls :many
SELECT id, tenant_id, imported_catalog_id, source_control_id, title, statement, group_path, scf_anchor_id, created_at FROM imported_catalog_controls
WHERE tenant_id = $1 AND imported_catalog_id = $2
ORDER BY group_path ASC, source_control_id ASC
`

type ListImportedCatalogControlsParams struct {
	TenantID          pgtype.UUID `json:"tenant_id"`
	ImportedCatalogID pgtype.UUID `json:"imported_catalog_id"`
}

// Every control for one imported catalog, ordered for stable rendering.
func (q *Queries) ListImportedCatalogControls(ctx context.Context, arg ListImportedCatalogControlsParams) ([]ImportedCatalogControl, error) {
	rows, err := q.db.Query(ctx, listImportedCatalogControls, arg.TenantID, arg.ImportedCatalogID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportedCatalogControl
	for rows.Next() {
		var i ImportedCatalogControl
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ImportedCatalogID,
			&i.SourceControlID,
			&i.Title,
			&i.Statement,
			&i.GroupPath,
			&i.ScfAnchorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportedCatalogs = `-- name: ListImportedCatalogs :many
SELECT id, tenant_id, source, imported_by, source_sha256, source_label, oscal_version, catalog_title, control_count, imported_at, kind, profile_title FROM imported_catalogs
WHERE tenant_id = $1
ORDER BY imported_at DESC, id ASC
`

// Enumerate every imported catalog for the tenant, most recent first.
func (q *Queries) ListImportedCatalogs(ctx context.Context, tenantID pgtype.UUID) ([]ImportedCatalog, error) {
	rows, err := q.db.Query(ctx, listImportedCatalogs, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportedCatalog
	for rows.Next() {
		var i ImportedCatalog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Source,
			&i.ImportedBy,
			&i.SourceSha256,
			&i.SourceLabel,
			&i.OscalVersion,
			&i.CatalogTitle,
			&i.ControlCount,
			&i.ImportedAt,
			&i.Kind,
			&i.ProfileTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportedProfiles = `-- name: ListImportedProfiles :many
SELECT id, tenant_id, source, imported_by, source_sha256, source_label, oscal_version, catalog_title, control_count, imported_at, kind, profile_title FROM imported_catalogs
WHERE tenant_id = $1 AND kind = 'profile'
ORDER BY imported_at DESC, id ASC
`

// Enumerate every resolved profile baseline for the tenant, most recent
// first (index-served by idx_imported_catalogs_tenant_profiles).
func (q *Queries) ListImportedProfiles(ctx context.Context, tenantID pgtype.UUID) ([]ImportedCatalog, error) {
	rows, err := q.db.Query(ctx, listImportedProfiles, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportedCatalog
	for rows.Next() {
		var i ImportedCatalog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Source,
			&i.ImportedBy,
			&i.SourceSha256,
			&i.SourceLabel,
			&i.OscalVersion,
			&i.CatalogTitle,
			&i.ControlCount,
			&i.ImportedAt,
			&i.Kind,
			&i.ProfileTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
