// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: incidents.sql

package dbx

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addIncidentControlLink = `-- name: AddIncidentControlLink :one
INSERT INTO incident_controls (tenant_id, incident_id, control_id, linked_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, incident_id, control_id) DO NOTHING
RETURNING incident_id, control_id, tenant_id, linked_at, linked_by
`

type AddIncidentControlLinkParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	IncidentID pgtype.UUID `json:"incident_id"`
	ControlID  pgtype.UUID `json:"control_id"`
	LinkedBy   string      `json:"linked_by"`
}

func (q *Queries) AddIncidentControlLink(ctx context.Context, arg AddIncidentControlLinkParams) (IncidentControl, error) {
	row := q.db.QueryRow(ctx, addIncidentControlLink,
		arg.TenantID,
		arg.IncidentID,
		arg.ControlID,
		arg.LinkedBy,
	)
	var i IncidentControl
	err := row.Scan(
		&i.IncidentID,
		&i.ControlID,
		&i.TenantID,
		&i.LinkedAt,
		&i.LinkedBy,
	)
	return i, err
}

const addIncidentEvidenceLink = `-- name: AddIncidentEvidenceLink :one
INSERT INTO incident_evidence_links (tenant_id, incident_id, evidence_id, linked_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, incident_id, evidence_id) DO NOTHING
RETURNING incident_id, evidence_id, tenant_id, linked_at, linked_by
`

type AddIncidentEvidenceLinkParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	IncidentID pgtype.UUID `json:"incident_id"`
	EvidenceID pgtype.UUID `json:"evidence_id"`
	LinkedBy   string      `json:"linked_by"`
}

func (q *Queries) AddIncidentEvidenceLink(ctx context.Context, arg AddIncidentEvidenceLinkParams) (IncidentEvidenceLink, error) {
	row := q.db.QueryRow(ctx, addIncidentEvidenceLink,
		arg.TenantID,
		arg.IncidentID,
		arg.EvidenceID,
		arg.LinkedBy,
	)
	var i IncidentEvidenceLink
	err := row.Scan(
		&i.IncidentID,
		&i.EvidenceID,
		&i.TenantID,
		&i.LinkedAt,
		&i.LinkedBy,
	)
	return i, err
}

const addIncidentRiskLink = `-- name: AddIncidentRiskLink :one
INSERT INTO incident_risks (tenant_id, incident_id, risk_id, linked_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, incident_id, risk_id) DO NOTHING
RETURNING incident_id, risk_id, tenant_id, linked_at, linked_by
`

type AddIncidentRiskLinkParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	IncidentID pgtype.UUID `json:"incident_id"`
	RiskID     pgtype.UUID `json:"risk_id"`
	LinkedBy   string      `json:"linked_by"`
}

func (q *Queries) AddIncidentRiskLink(ctx context.Context, arg AddIncidentRiskLinkParams) (IncidentRisk, error) {
	row := q.db.QueryRow(ctx, addIncidentRiskLink,
		arg.TenantID,
		arg.IncidentID,
		arg.RiskID,
		arg.LinkedBy,
	)
	var i IncidentRisk
	err := row.Scan(
		&i.IncidentID,
		&i.RiskID,
		&i.TenantID,
		&i.LinkedAt,
		&i.LinkedBy,
	)
	return i, err
}

const addIncidentVendorLink = `-- name: AddIncidentVendorLink :one
INSERT INTO incident_vendors (tenant_id, incident_id, vendor_id, linked_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, incident_id, vendor_id) DO NOTHING
RETURNING incident_id, vendor_id, tenant_id, linked_at, linked_by
`

type AddIncidentVendorLinkParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	IncidentID pgtype.UUID `json:"incident_id"`
	VendorID   pgtype.UUID `json:"vendor_id"`
	LinkedBy   string      `json:"linked_by"`
}

func (q *Queries) AddIncidentVendorLink(ctx context.Context, arg AddIncidentVendorLinkParams) (IncidentVendor, error) {
	row := q.db.QueryRow(ctx, addIncidentVendorLink,
		arg.TenantID,
		arg.IncidentID,
		arg.VendorID,
		arg.LinkedBy,
	)
	var i IncidentVendor
	err := row.Scan(
		&i.IncidentID,
		&i.VendorID,
		&i.TenantID,
		&i.LinkedAt,
		&i.LinkedBy,
	)
	return i, err
}

const closeIncident = `-- name: CloseIncident :one
UPDATE incidents
SET status = 'closed',
    closed_by = $3,
    closed_at = now(),
    postmortem_summary = $4,
    updated_at = now()
WHERE tenant_id = $1
  AND id = $2
  AND status = 'resolved'
RETURNING id, tenant_id, title, description, status, operator_severity, severity, affected_system_tier, affected_systems, detected_by, detected_at, triaged_by, triaged_at, contained_by, contained_at, resolved_by, resolved_at, closed_by, closed_at, postmortem_summary, created_at, updated_at
`

type CloseIncidentParams struct {
	TenantID          pgtype.UUID `json:"tenant_id"`
	ID                pgtype.UUID `json:"id"`
	ClosedBy          *string     `json:"closed_by"`
	PostmortemSummary *string     `json:"postmortem_summary"`
}

func (q *Queries) CloseIncident(ctx context.Context, arg CloseIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, closeIncident,
		arg.TenantID,
		arg.ID,
		arg.ClosedBy,
		arg.PostmortemSummary,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.OperatorSeverity,
		&i.Severity,
		&i.AffectedSystemTier,
		&i.AffectedSystems,
		&i.DetectedBy,
		&i.DetectedAt,
		&i.TriagedBy,
		&i.TriagedAt,
		&i.ContainedBy,
		&i.ContainedAt,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.PostmortemSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createIncident = `-- name: CreateIncident :one

INSERT INTO incidents (
    id, tenant_id, title, description,
    operator_severity, severity, affected_system_tier,
    affected_systems, detected_by, detected_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10
)
RETURNING id, tenant_id, title, description, status, operator_severity, severity, affected_system_tier, affected_systems, detected_by, detected_at, triaged_by, triaged_at, contained_by, contained_at, resolved_by, resolved_at, closed_by, closed_at, postmortem_summary, created_at, updated_at
`

type CreateIncidentParams struct {
	ID                 pgtype.UUID        `json:"id"`
	TenantID           pgtype.UUID        `json:"tenant_id"`
	Title              string             `json:"title"`
	Description        string             `json:"description"`
	OperatorSeverity   string             `json:"operator_severity"`
	Severity           string             `json:"severity"`
	AffectedSystemTier *string            `json:"affected_system_tier"`
	AffectedSystems    []byte             `json:"affected_systems"`
	DetectedBy         string             `json:"detected_by"`
	DetectedAt         pgtype.Timestamptz `json:"detected_at"`
}

// OE-631 incident register queries.
func (q *Queries) CreateIncident(ctx context.Context, arg CreateIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, createIncident,
		arg.ID,
		arg.TenantID,
		arg.Title,
		arg.Description,
		arg.OperatorSeverity,
		arg.Severity,
		arg.AffectedSystemTier,
		arg.AffectedSystems,
		arg.DetectedBy,
		arg.DetectedAt,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.OperatorSeverity,
		&i.Severity,
		&i.AffectedSystemTier,
		&i.AffectedSystems,
		&i.DetectedBy,
		&i.DetectedAt,
		&i.TriagedBy,
		&i.TriagedAt,
		&i.ContainedBy,
		&i.ContainedAt,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.PostmortemSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIncidentByID = `-- name: GetIncidentByID :one
SELECT id, tenant_id, title, description, status, operator_severity, severity, affected_system_tier, affected_systems, detected_by, detected_at, triaged_by, triaged_at, contained_by, contained_at, resolved_by, resolved_at, closed_by, closed_at, postmortem_summary, created_at, updated_at
FROM incidents
WHERE tenant_id = $1 AND id = $2
`

type GetIncidentByIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetIncidentByID(ctx context.Context, arg GetIncidentByIDParams) (Incident, error) {
	row := q.db.QueryRow(ctx, getIncidentByID, arg.TenantID, arg.ID)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.OperatorSeverity,
		&i.Severity,
		&i.AffectedSystemTier,
		&i.AffectedSystems,
		&i.DetectedBy,
		&i.DetectedAt,
		&i.TriagedBy,
		&i.TriagedAt,
		&i.ContainedBy,
		&i.ContainedAt,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.PostmortemSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIncidentControlLinks = `-- name: ListIncidentControlLinks :many
SELECT incident_id, control_id, tenant_id, linked_at, linked_by
FROM incident_controls
WHERE tenant_id = $1 AND incident_id = $2
ORDER BY linked_at ASC, control_id ASC
`

type ListIncidentControlLinksParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	IncidentID pgtype.UUID `json:"incident_id"`
}

func (q *Queries) ListIncidentControlLinks(ctx context.Context, arg ListIncidentControlLinksParams) ([]IncidentControl, error) {
	rows, err := q.db.Query(ctx, listIncidentControlLinks, arg.TenantID, arg.IncidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IncidentControl
	for rows.Next() {
		var i IncidentControl
		if err := rows.Scan(
			&i.IncidentID,
			&i.ControlID,
			&i.TenantID,
			&i.LinkedAt,
			&i.LinkedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidentEvidenceLinks = `-- name: ListIncidentEvidenceLinks :many
SELECT incident_id, evidence_id, tenant_id, linked_at, linked_by
FROM incident_evidence_links
WHERE tenant_id = $1 AND incident_id = $2
ORDER BY linked_at ASC, evidence_id ASC
`

type ListIncidentEvidenceLinksParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	IncidentID pgtype.UUID `json:"incident_id"`
}

func (q *Queries) ListIncidentEvidenceLinks(ctx context.Context, arg ListIncidentEvidenceLinksParams) ([]IncidentEvidenceLink, error) {
	rows, err := q.db.Query(ctx, listIncidentEvidenceLinks, arg.TenantID, arg.IncidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IncidentEvidenceLink
	for rows.Next() {
		var i IncidentEvidenceLink
		if err := rows.Scan(
			&i.IncidentID,
			&i.EvidenceID,
			&i.TenantID,
			&i.LinkedAt,
			&i.LinkedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidentRiskLinks = `-- name: ListIncidentRiskLinks :many
SELECT incident_id, risk_id, tenant_id, linked_at, linked_by
FROM incident_risks
WHERE tenant_id = $1 AND incident_id = $2
ORDER BY linked_at ASC, risk_id ASC
`

type ListIncidentRiskLinksParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	IncidentID pgtype.UUID `json:"incident_id"`
}

func (q *Queries) ListIncidentRiskLinks(ctx context.Context, arg ListIncidentRiskLinksParams) ([]IncidentRisk, error) {
	rows, err := q.db.Query(ctx, listIncidentRiskLinks, arg.TenantID, arg.IncidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IncidentRisk
	for rows.Next() {
		var i IncidentRisk
		if err := rows.Scan(
			&i.IncidentID,
			&i.RiskID,
			&i.TenantID,
			&i.LinkedAt,
			&i.LinkedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidentTimeline = `-- name: ListIncidentTimeline :many
SELECT id, tenant_id, incident_id, action, actor, from_state, to_state, summary, detail, occurred_at, subject_module
FROM incident_timeline
WHERE tenant_id = $1 AND incident_id = $2
ORDER BY occurred_at ASC, id ASC
`

type ListIncidentTimelineParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	IncidentID pgtype.UUID `json:"incident_id"`
}

func (q *Queries) ListIncidentTimeline(ctx context.Context, arg ListIncidentTimelineParams) ([]IncidentTimeline, error) {
	rows, err := q.db.Query(ctx, listIncidentTimeline, arg.TenantID, arg.IncidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IncidentTimeline
	for rows.Next() {
		var i IncidentTimeline
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.IncidentID,
			&i.Action,
			&i.Actor,
			&i.FromState,
			&i.ToState,
			&i.Summary,
			&i.Detail,
			&i.OccurredAt,
			&i.SubjectModule,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidentVendorLinks = `-- name: ListIncidentVendorLinks :many
SELECT incident_id, vendor_id, tenant_id, linked_at, linked_by
FROM incident_vendors
WHERE tenant_id = $1 AND incident_id = $2
ORDER BY linked_at ASC, vendor_id ASC
`

type ListIncidentVendorLinksParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	IncidentID pgtype.UUID `json:"incident_id"`
}

func (q *Queries) ListIncidentVendorLinks(ctx context.Context, arg ListIncidentVendorLinksParams) ([]IncidentVendor, error) {
	rows, err := q.db.Query(ctx, listIncidentVendorLinks, arg.TenantID, arg.IncidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IncidentVendor
	for rows.Next() {
		var i IncidentVendor
		if err := rows.Scan(
			&i.IncidentID,
			&i.VendorID,
			&i.TenantID,
			&i.LinkedAt,
			&i.LinkedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidents = `-- name: ListIncidents :many
SELECT id, tenant_id, title, description, status, operator_severity, severity, affected_system_tier, affected_systems, detected_by, detected_at, triaged_by, triaged_at, contained_by, contained_at, resolved_by, resolved_at, closed_by, closed_at, postmortem_summary, created_at, updated_at
FROM incidents
WHERE tenant_id = $1
ORDER BY created_at DESC, id ASC
`

func (q *Queries) ListIncidents(ctx context.Context, tenantID pgtype.UUID) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listIncidents, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Incident
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.OperatorSeverity,
			&i.Severity,
			&i.AffectedSystemTier,
			&i.AffectedSystems,
			&i.DetectedBy,
			&i.DetectedAt,
			&i.TriagedBy,
			&i.TriagedAt,
			&i.ContainedBy,
			&i.ContainedAt,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.ClosedBy,
			&i.ClosedAt,
			&i.PostmortemSummary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionIncident = `-- name: TransitionIncident :one
UPDATE incidents
SET status = $3,
    triaged_by = CASE WHEN $3 = 'triaged' THEN $4 ELSE triaged_by END,
    triaged_at = CASE WHEN $3 = 'triaged' THEN now() ELSE triaged_at END,
    contained_by = CASE WHEN $3 = 'contained' THEN $4 ELSE contained_by END,
    contained_at = CASE WHEN $3 = 'contained' THEN now() ELSE contained_at END,
    resolved_by = CASE WHEN $3 = 'resolved' THEN $4 ELSE resolved_by END,
    resolved_at = CASE WHEN $3 = 'resolved' THEN now() ELSE resolved_at END,
    updated_at = now()
WHERE tenant_id = $1
  AND id = $2
  AND status = $5
RETURNING id, tenant_id, title, description, status, operator_severity, severity, affected_system_tier, affected_systems, detected_by, detected_at, triaged_by, triaged_at, contained_by, contained_at, resolved_by, resolved_at, closed_by, closed_at, postmortem_summary, created_at, updated_at
`

type TransitionIncidentParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	ID        pgtype.UUID `json:"id"`
	Status    string      `json:"status"`
	TriagedBy *string     `json:"triaged_by"`
	Status_2  string      `json:"status_2"`
}

func (q *Queries) TransitionIncident(ctx context.Context, arg TransitionIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, transitionIncident,
		arg.TenantID,
		arg.ID,
		arg.Status,
		arg.TriagedBy,
		arg.Status_2,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.OperatorSeverity,
		&i.Severity,
		&i.AffectedSystemTier,
		&i.AffectedSystems,
		&i.DetectedBy,
		&i.DetectedAt,
		&i.TriagedBy,
		&i.TriagedAt,
		&i.ContainedBy,
		&i.ContainedAt,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.PostmortemSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const writeIncidentTimeline = `-- name: WriteIncidentTimeline :one
INSERT INTO incident_timeline (
    id, tenant_id, incident_id,
    action, actor, from_state, to_state, summary, detail, subject_module
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7, $8, $9, 'core'
)
RETURNING id, tenant_id, incident_id, action, actor, from_state, to_state, summary, detail, occurred_at, subject_module
`

type WriteIncidentTimelineParams struct {
	ID         pgtype.UUID `json:"id"`
	TenantID   pgtype.UUID `json:"tenant_id"`
	IncidentID pgtype.UUID `json:"incident_id"`
	Action     string      `json:"action"`
	Actor      string      `json:"actor"`
	FromState  *string     `json:"from_state"`
	ToState    string      `json:"to_state"`
	Summary    string      `json:"summary"`
	Detail     []byte      `json:"detail"`
}

func (q *Queries) WriteIncidentTimeline(ctx context.Context, arg WriteIncidentTimelineParams) (IncidentTimeline, error) {
	row := q.db.QueryRow(ctx, writeIncidentTimeline,
		arg.ID,
		arg.TenantID,
		arg.IncidentID,
		arg.Action,
		arg.Actor,
		arg.FromState,
		arg.ToState,
		arg.Summary,
		arg.Detail,
	)
	var i IncidentTimeline
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.IncidentID,
		&i.Action,
		&i.Actor,
		&i.FromState,
		&i.ToState,
		&i.Summary,
		&i.Detail,
		&i.OccurredAt,
		&i.SubjectModule,
	)
	return i, err
}
