// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbx

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ControlImplementationType string

const (
	ControlImplementationTypeAutomated      ControlImplementationType = "automated"
	ControlImplementationTypeSemiAutomated  ControlImplementationType = "semi_automated"
	ControlImplementationTypeManualAttested ControlImplementationType = "manual_attested"
	ControlImplementationTypeManualPeriodic ControlImplementationType = "manual_periodic"
)

func (e *ControlImplementationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ControlImplementationType(s)
	case string:
		*e = ControlImplementationType(s)
	default:
		return fmt.Errorf("unsupported scan type for ControlImplementationType: %T", src)
	}
	return nil
}

type NullControlImplementationType struct {
	ControlImplementationType ControlImplementationType `json:"control_implementation_type"`
	Valid                     bool                      `json:"valid"` // Valid is true if ControlImplementationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullControlImplementationType) Scan(value interface{}) error {
	if value == nil {
		ns.ControlImplementationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ControlImplementationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullControlImplementationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ControlImplementationType), nil
}

type ControlLifecycleState string

const (
	ControlLifecycleStateDraft      ControlLifecycleState = "draft"
	ControlLifecycleStateProposed   ControlLifecycleState = "proposed"
	ControlLifecycleStateActive     ControlLifecycleState = "active"
	ControlLifecycleStateDeprecated ControlLifecycleState = "deprecated"
	ControlLifecycleStateRetired    ControlLifecycleState = "retired"
)

func (e *ControlLifecycleState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ControlLifecycleState(s)
	case string:
		*e = ControlLifecycleState(s)
	default:
		return fmt.Errorf("unsupported scan type for ControlLifecycleState: %T", src)
	}
	return nil
}

type NullControlLifecycleState struct {
	ControlLifecycleState ControlLifecycleState `json:"control_lifecycle_state"`
	Valid                 bool                  `json:"valid"` // Valid is true if ControlLifecycleState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullControlLifecycleState) Scan(value interface{}) error {
	if value == nil {
		ns.ControlLifecycleState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ControlLifecycleState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullControlLifecycleState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ControlLifecycleState), nil
}

type EvidenceFreshnessClass string

const (
	EvidenceFreshnessClassRealtime  EvidenceFreshnessClass = "realtime"
	EvidenceFreshnessClassDaily     EvidenceFreshnessClass = "daily"
	EvidenceFreshnessClassWeekly    EvidenceFreshnessClass = "weekly"
	EvidenceFreshnessClassMonthly   EvidenceFreshnessClass = "monthly"
	EvidenceFreshnessClassQuarterly EvidenceFreshnessClass = "quarterly"
	EvidenceFreshnessClassAnnual    EvidenceFreshnessClass = "annual"
)

func (e *EvidenceFreshnessClass) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EvidenceFreshnessClass(s)
	case string:
		*e = EvidenceFreshnessClass(s)
	default:
		return fmt.Errorf("unsupported scan type for EvidenceFreshnessClass: %T", src)
	}
	return nil
}

type NullEvidenceFreshnessClass struct {
	EvidenceFreshnessClass EvidenceFreshnessClass `json:"evidence_freshness_class"`
	Valid                  bool                   `json:"valid"` // Valid is true if EvidenceFreshnessClass is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEvidenceFreshnessClass) Scan(value interface{}) error {
	if value == nil {
		ns.EvidenceFreshnessClass, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EvidenceFreshnessClass.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEvidenceFreshnessClass) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EvidenceFreshnessClass), nil
}

type EvidenceResult string

const (
	EvidenceResultPass         EvidenceResult = "pass"
	EvidenceResultFail         EvidenceResult = "fail"
	EvidenceResultNa           EvidenceResult = "na"
	EvidenceResultInconclusive EvidenceResult = "inconclusive"
)

func (e *EvidenceResult) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EvidenceResult(s)
	case string:
		*e = EvidenceResult(s)
	default:
		return fmt.Errorf("unsupported scan type for EvidenceResult: %T", src)
	}
	return nil
}

type NullEvidenceResult struct {
	EvidenceResult EvidenceResult `json:"evidence_result"`
	Valid          bool           `json:"valid"` // Valid is true if EvidenceResult is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEvidenceResult) Scan(value interface{}) error {
	if value == nil {
		ns.EvidenceResult, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EvidenceResult.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEvidenceResult) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EvidenceResult), nil
}

type FrameworkScopeStatus string

const (
	FrameworkScopeStatusDraft    FrameworkScopeStatus = "draft"
	FrameworkScopeStatusApproved FrameworkScopeStatus = "approved"
	FrameworkScopeStatusActive   FrameworkScopeStatus = "active"
	FrameworkScopeStatusRetired  FrameworkScopeStatus = "retired"
)

func (e *FrameworkScopeStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FrameworkScopeStatus(s)
	case string:
		*e = FrameworkScopeStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FrameworkScopeStatus: %T", src)
	}
	return nil
}

type NullFrameworkScopeStatus struct {
	FrameworkScopeStatus FrameworkScopeStatus `json:"framework_scope_status"`
	Valid                bool                 `json:"valid"` // Valid is true if FrameworkScopeStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFrameworkScopeStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FrameworkScopeStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FrameworkScopeStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFrameworkScopeStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FrameworkScopeStatus), nil
}

type FrameworkVersionStatus string

const (
	FrameworkVersionStatusCurrent   FrameworkVersionStatus = "current"
	FrameworkVersionStatusLegacy    FrameworkVersionStatus = "legacy"
	FrameworkVersionStatusWithdrawn FrameworkVersionStatus = "withdrawn"
)

func (e *FrameworkVersionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FrameworkVersionStatus(s)
	case string:
		*e = FrameworkVersionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FrameworkVersionStatus: %T", src)
	}
	return nil
}

type NullFrameworkVersionStatus struct {
	FrameworkVersionStatus FrameworkVersionStatus `json:"framework_version_status"`
	Valid                  bool                   `json:"valid"` // Valid is true if FrameworkVersionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFrameworkVersionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FrameworkVersionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FrameworkVersionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFrameworkVersionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FrameworkVersionStatus), nil
}

type PolicyStatus string

const (
	PolicyStatusDraft       PolicyStatus = "draft"
	PolicyStatusUnderReview PolicyStatus = "under_review"
	PolicyStatusApproved    PolicyStatus = "approved"
	PolicyStatusPublished   PolicyStatus = "published"
	PolicyStatusSuperseded  PolicyStatus = "superseded"
)

func (e *PolicyStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PolicyStatus(s)
	case string:
		*e = PolicyStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PolicyStatus: %T", src)
	}
	return nil
}

type NullPolicyStatus struct {
	PolicyStatus PolicyStatus `json:"policy_status"`
	Valid        bool         `json:"valid"` // Valid is true if PolicyStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPolicyStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PolicyStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PolicyStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPolicyStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PolicyStatus), nil
}

type RiskCategory string

const (
	RiskCategoryConfidentiality RiskCategory = "confidentiality"
	RiskCategoryIntegrity       RiskCategory = "integrity"
	RiskCategoryAvailability    RiskCategory = "availability"
	RiskCategoryPrivacy         RiskCategory = "privacy"
	RiskCategoryRegulatory      RiskCategory = "regulatory"
	RiskCategoryOperational     RiskCategory = "operational"
	RiskCategoryFinancial       RiskCategory = "financial"
)

func (e *RiskCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiskCategory(s)
	case string:
		*e = RiskCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for RiskCategory: %T", src)
	}
	return nil
}

type NullRiskCategory struct {
	RiskCategory RiskCategory `json:"risk_category"`
	Valid        bool         `json:"valid"` // Valid is true if RiskCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiskCategory) Scan(value interface{}) error {
	if value == nil {
		ns.RiskCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiskCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiskCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiskCategory), nil
}

type RiskMethodology string

const (
	RiskMethodologyNist80030      RiskMethodology = "nist_800_30"
	RiskMethodologyFair           RiskMethodology = "fair"
	RiskMethodologyCisRam         RiskMethodology = "cis_ram"
	RiskMethodologyIso27005       RiskMethodology = "iso_27005"
	RiskMethodologyQualitative5x5 RiskMethodology = "qualitative_5x5"
)

func (e *RiskMethodology) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiskMethodology(s)
	case string:
		*e = RiskMethodology(s)
	default:
		return fmt.Errorf("unsupported scan type for RiskMethodology: %T", src)
	}
	return nil
}

type NullRiskMethodology struct {
	RiskMethodology RiskMethodology `json:"risk_methodology"`
	Valid           bool            `json:"valid"` // Valid is true if RiskMethodology is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiskMethodology) Scan(value interface{}) error {
	if value == nil {
		ns.RiskMethodology, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiskMethodology.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiskMethodology) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiskMethodology), nil
}

type RiskTreatment string

const (
	RiskTreatmentAccept   RiskTreatment = "accept"
	RiskTreatmentMitigate RiskTreatment = "mitigate"
	RiskTreatmentTransfer RiskTreatment = "transfer"
	RiskTreatmentAvoid    RiskTreatment = "avoid"
)

func (e *RiskTreatment) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiskTreatment(s)
	case string:
		*e = RiskTreatment(s)
	default:
		return fmt.Errorf("unsupported scan type for RiskTreatment: %T", src)
	}
	return nil
}

type NullRiskTreatment struct {
	RiskTreatment RiskTreatment `json:"risk_treatment"`
	Valid         bool          `json:"valid"` // Valid is true if RiskTreatment is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiskTreatment) Scan(value interface{}) error {
	if value == nil {
		ns.RiskTreatment, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiskTreatment.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiskTreatment) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiskTreatment), nil
}

type ScopeDataClassification string

const (
	ScopeDataClassificationRestricted   ScopeDataClassification = "restricted"
	ScopeDataClassificationConfidential ScopeDataClassification = "confidential"
	ScopeDataClassificationInternal     ScopeDataClassification = "internal"
	ScopeDataClassificationPublic       ScopeDataClassification = "public"
)

func (e *ScopeDataClassification) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ScopeDataClassification(s)
	case string:
		*e = ScopeDataClassification(s)
	default:
		return fmt.Errorf("unsupported scan type for ScopeDataClassification: %T", src)
	}
	return nil
}

type NullScopeDataClassification struct {
	ScopeDataClassification ScopeDataClassification `json:"scope_data_classification"`
	Valid                   bool                    `json:"valid"` // Valid is true if ScopeDataClassification is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullScopeDataClassification) Scan(value interface{}) error {
	if value == nil {
		ns.ScopeDataClassification, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ScopeDataClassification.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullScopeDataClassification) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ScopeDataClassification), nil
}

type ScopeEnvironment string

const (
	ScopeEnvironmentProd    ScopeEnvironment = "prod"
	ScopeEnvironmentStaging ScopeEnvironment = "staging"
	ScopeEnvironmentDev     ScopeEnvironment = "dev"
	ScopeEnvironmentSandbox ScopeEnvironment = "sandbox"
)

func (e *ScopeEnvironment) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ScopeEnvironment(s)
	case string:
		*e = ScopeEnvironment(s)
	default:
		return fmt.Errorf("unsupported scan type for ScopeEnvironment: %T", src)
	}
	return nil
}

type NullScopeEnvironment struct {
	ScopeEnvironment ScopeEnvironment `json:"scope_environment"`
	Valid            bool             `json:"valid"` // Valid is true if ScopeEnvironment is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullScopeEnvironment) Scan(value interface{}) error {
	if value == nil {
		ns.ScopeEnvironment, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ScopeEnvironment.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullScopeEnvironment) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ScopeEnvironment), nil
}

type VendorCriticality string

const (
	VendorCriticalityLow    VendorCriticality = "low"
	VendorCriticalityMedium VendorCriticality = "medium"
	VendorCriticalityHigh   VendorCriticality = "high"
)

func (e *VendorCriticality) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VendorCriticality(s)
	case string:
		*e = VendorCriticality(s)
	default:
		return fmt.Errorf("unsupported scan type for VendorCriticality: %T", src)
	}
	return nil
}

type NullVendorCriticality struct {
	VendorCriticality VendorCriticality `json:"vendor_criticality"`
	Valid             bool              `json:"valid"` // Valid is true if VendorCriticality is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVendorCriticality) Scan(value interface{}) error {
	if value == nil {
		ns.VendorCriticality, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VendorCriticality.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVendorCriticality) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VendorCriticality), nil
}

type VendorReviewCadence string

const (
	VendorReviewCadenceMonthly   VendorReviewCadence = "monthly"
	VendorReviewCadenceQuarterly VendorReviewCadence = "quarterly"
	VendorReviewCadenceBiannual  VendorReviewCadence = "biannual"
	VendorReviewCadenceAnnual    VendorReviewCadence = "annual"
)

func (e *VendorReviewCadence) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VendorReviewCadence(s)
	case string:
		*e = VendorReviewCadence(s)
	default:
		return fmt.Errorf("unsupported scan type for VendorReviewCadence: %T", src)
	}
	return nil
}

type NullVendorReviewCadence struct {
	VendorReviewCadence VendorReviewCadence `json:"vendor_review_cadence"`
	Valid               bool                `json:"valid"` // Valid is true if VendorReviewCadence is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVendorReviewCadence) Scan(value interface{}) error {
	if value == nil {
		ns.VendorReviewCadence, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VendorReviewCadence.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVendorReviewCadence) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VendorReviewCadence), nil
}

type Control struct {
	ID                 pgtype.UUID               `json:"id"`
	TenantID           pgtype.UUID               `json:"tenant_id"`
	ScfID              *string                   `json:"scf_id"`
	Title              string                    `json:"title"`
	Description        string                    `json:"description"`
	ControlFamily      string                    `json:"control_family"`
	ImplementationType ControlImplementationType `json:"implementation_type"`
	OwnerRole          string                    `json:"owner_role"`
	LifecycleState     ControlLifecycleState     `json:"lifecycle_state"`
	ApplicabilityExpr  string                    `json:"applicability_expr"`
	Version            int32                     `json:"version"`
	CreatedAt          pgtype.Timestamptz        `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz        `json:"updated_at"`
}

type EvidenceKindSchema struct {
	ID                      pgtype.UUID        `json:"id"`
	TenantID                pgtype.UUID        `json:"tenant_id"`
	Kind                    string             `json:"kind"`
	Semver                  string             `json:"semver"`
	Major                   int32              `json:"major"`
	Minor                   int32              `json:"minor"`
	Patch                   int32              `json:"patch"`
	SchemaJson              []byte             `json:"schema_json"`
	Owner                   string             `json:"owner"`
	DefaultScfAnchors       []string           `json:"default_scf_anchors"`
	DeprecatedAt            pgtype.Timestamptz `json:"deprecated_at"`
	DeprecationWindowEndsAt pgtype.Timestamptz `json:"deprecation_window_ends_at"`
	SupersededByVersion     *string            `json:"superseded_by_version"`
	CreatedBy               string             `json:"created_by"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type EvidenceRecord struct {
	ID              pgtype.UUID            `json:"id"`
	TenantID        pgtype.UUID            `json:"tenant_id"`
	EvidenceQueryID pgtype.UUID            `json:"evidence_query_id"`
	ControlID       pgtype.UUID            `json:"control_id"`
	ScopeID         pgtype.UUID            `json:"scope_id"`
	ObservedAt      pgtype.Timestamptz     `json:"observed_at"`
	IngestedAt      pgtype.Timestamptz     `json:"ingested_at"`
	Provenance      []byte                 `json:"provenance"`
	Result          EvidenceResult         `json:"result"`
	Payload         []byte                 `json:"payload"`
	PayloadUri      *string                `json:"payload_uri"`
	Hash            string                 `json:"hash"`
	FreshnessClass  EvidenceFreshnessClass `json:"freshness_class"`
	ValidUntil      pgtype.Timestamptz     `json:"valid_until"`
	CreatedAt       pgtype.Timestamptz     `json:"created_at"`
}

type Framework struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	Name            string             `json:"name"`
	Slug            string             `json:"slug"`
	Issuer          string             `json:"issuer"`
	Description     string             `json:"description"`
	LatestVersionID pgtype.UUID        `json:"latest_version_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type FrameworkScope struct {
	ID                 pgtype.UUID          `json:"id"`
	TenantID           pgtype.UUID          `json:"tenant_id"`
	FrameworkVersionID pgtype.UUID          `json:"framework_version_id"`
	Name               string               `json:"name"`
	Predicate          string               `json:"predicate"`
	EffectiveFrom      pgtype.Date          `json:"effective_from"`
	EffectiveTo        pgtype.Date          `json:"effective_to"`
	Status             FrameworkScopeStatus `json:"status"`
	ApprovedBy         *string              `json:"approved_by"`
	ApprovalEvidence   *string              `json:"approval_evidence"`
	CreatedAt          pgtype.Timestamptz   `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz   `json:"updated_at"`
}

type FrameworkVersion struct {
	ID               pgtype.UUID            `json:"id"`
	TenantID         pgtype.UUID            `json:"tenant_id"`
	FrameworkID      pgtype.UUID            `json:"framework_id"`
	Version          string                 `json:"version"`
	EffectiveFrom    pgtype.Date            `json:"effective_from"`
	EffectiveTo      pgtype.Date            `json:"effective_to"`
	Status           FrameworkVersionStatus `json:"status"`
	RequirementCount int32                  `json:"requirement_count"`
	OscalCatalogUri  *string                `json:"oscal_catalog_uri"`
	CreatedAt        pgtype.Timestamptz     `json:"created_at"`
}

type Policy struct {
	ID                         pgtype.UUID        `json:"id"`
	TenantID                   pgtype.UUID        `json:"tenant_id"`
	Title                      string             `json:"title"`
	Version                    int32              `json:"version"`
	EffectiveDate              pgtype.Date        `json:"effective_date"`
	BodyMd                     string             `json:"body_md"`
	Owner                      string             `json:"owner"`
	Approver                   string             `json:"approver"`
	AcknowledgmentRequiredRole []string           `json:"acknowledgment_required_role"`
	Status                     PolicyStatus       `json:"status"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
}

type Risk struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	Title          string             `json:"title"`
	Description    string             `json:"description"`
	Category       RiskCategory       `json:"category"`
	Methodology    RiskMethodology    `json:"methodology"`
	InherentScore  []byte             `json:"inherent_score"`
	Treatment      RiskTreatment      `json:"treatment"`
	TreatmentOwner string             `json:"treatment_owner"`
	ResidualScore  []byte             `json:"residual_score"`
	ReviewDueAt    pgtype.Timestamptz `json:"review_due_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ScfAnchor struct {
	ID                 pgtype.UUID        `json:"id"`
	FrameworkVersionID pgtype.UUID        `json:"framework_version_id"`
	ScfID              string             `json:"scf_id"`
	Family             string             `json:"family"`
	Title              string             `json:"title"`
	Description        string             `json:"description"`
	Subtopics          []byte             `json:"subtopics"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Scope struct {
	ID                 pgtype.UUID              `json:"id"`
	TenantID           pgtype.UUID              `json:"tenant_id"`
	BusinessUnit       string                   `json:"business_unit"`
	Environment        *ScopeEnvironment        `json:"environment"`
	Geography          *string                  `json:"geography"`
	CloudAccount       *string                  `json:"cloud_account"`
	DataClassification *ScopeDataClassification `json:"data_classification"`
	ProductLine        *string                  `json:"product_line"`
	CreatedAt          pgtype.Timestamptz       `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz       `json:"updated_at"`
}

type ScopeCell struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	Label          string             `json:"label"`
	Dimensions     []byte             `json:"dimensions"`
	DimensionsHash string             `json:"dimensions_hash"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ScopeDimension struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	Name          string             `json:"name"`
	ValueType     string             `json:"value_type"`
	AllowedValues []byte             `json:"allowed_values"`
	IsRequired    bool               `json:"is_required"`
	IsBuiltin     bool               `json:"is_builtin"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Vendor struct {
	ID             pgtype.UUID         `json:"id"`
	TenantID       pgtype.UUID         `json:"tenant_id"`
	Name           string              `json:"name"`
	Domain         *string             `json:"domain"`
	Criticality    VendorCriticality   `json:"criticality"`
	ContractStart  pgtype.Date         `json:"contract_start"`
	ContractEnd    pgtype.Date         `json:"contract_end"`
	DpaSigned      bool                `json:"dpa_signed"`
	DpaSignedAt    pgtype.Date         `json:"dpa_signed_at"`
	ReviewCadence  VendorReviewCadence `json:"review_cadence"`
	LastReviewDate pgtype.Date         `json:"last_review_date"`
	OwnerUser      string              `json:"owner_user"`
	LinkedSowUri   *string             `json:"linked_sow_uri"`
	Notes          string              `json:"notes"`
	CreatedAt      pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz  `json:"updated_at"`
}

type VendorScopeCell struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	VendorID    pgtype.UUID        `json:"vendor_id"`
	ScopeCellID pgtype.UUID        `json:"scope_cell_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
