// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package dbx

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadNotificationsForUser = `-- name: CountUnreadNotificationsForUser :one
SELECT COUNT(*) AS unread_count
FROM notifications
WHERE tenant_id         = $1
  AND recipient_user_id = $2
  AND read_at IS NULL
`

type CountUnreadNotificationsForUserParams struct {
	TenantID        pgtype.UUID `json:"tenant_id"`
	RecipientUserID string      `json:"recipient_user_id"`
}

// Used by the /v1/me/notifications response to surface the unread count
// in the page header.
func (q *Queries) CountUnreadNotificationsForUser(ctx context.Context, arg CountUnreadNotificationsForUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotificationsForUser, arg.TenantID, arg.RecipientUserID)
	var unread_count int64
	err := row.Scan(&unread_count)
	return unread_count, err
}

const createNotification = `-- name: CreateNotification :one

INSERT INTO notifications (
    id, tenant_id, recipient_user_id, type, payload, created_at
)
VALUES ($1, $2, $3, $4, $5, now())
RETURNING id, tenant_id, recipient_user_id, type, payload, created_at, read_at
`

type CreateNotificationParams struct {
	ID              pgtype.UUID `json:"id"`
	TenantID        pgtype.UUID `json:"tenant_id"`
	RecipientUserID string      `json:"recipient_user_id"`
	Type            string      `json:"type"`
	Payload         []byte      `json:"payload"`
}

// Slice 029 -- notifications spine.
//
// In-app notifications. Slice 029 dispatches a row per distinct prior
// thread author when a new audit_note lands; the recipient sees it on
// /v1/me/notifications. Future slices may reuse this spine for other
// notification types (evidence freshness, policy acknowledgment, etc.).
//
// All queries are tenant-scoped via the leading (tenant_id, ...); RLS
// under FORCE keeps the cross-tenant boundary safe even on a
// misconfigured query. The recipient_user_id filter is the second-line
// protection -- a caller cannot list another user's notifications.
// Insert a single notification row. The payload is opaque JSONB; the
// handler/dispatch layer is responsible for the shape consistency per
// notification type.
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.ID,
		arg.TenantID,
		arg.RecipientUserID,
		arg.Type,
		arg.Payload,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RecipientUserID,
		&i.Type,
		&i.Payload,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}

const listNotificationsForUser = `-- name: ListNotificationsForUser :many
SELECT id, tenant_id, recipient_user_id, type, payload, created_at, read_at FROM notifications
WHERE tenant_id         = $1
  AND recipient_user_id = $2
ORDER BY read_at NULLS FIRST, created_at DESC, id ASC
LIMIT $3 OFFSET $4
`

type ListNotificationsForUserParams struct {
	TenantID        pgtype.UUID `json:"tenant_id"`
	RecipientUserID string      `json:"recipient_user_id"`
	Limit           int32       `json:"limit"`
	Offset          int32       `json:"offset"`
}

// Recipient-scoped list. Unread first (NULLS FIRST on read_at), then
// newest first within each read-status bucket. The index
// idx_notifications_recipient_unread_first directly serves this order.
// $3 is the limit and $4 the offset for paging.
func (q *Queries) ListNotificationsForUser(ctx context.Context, arg ListNotificationsForUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsForUser,
		arg.TenantID,
		arg.RecipientUserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RecipientUserID,
			&i.Type,
			&i.Payload,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notifications
SET read_at = COALESCE(read_at, now())
WHERE tenant_id         = $1
  AND recipient_user_id = $2
  AND id                = $3
RETURNING id, tenant_id, recipient_user_id, type, payload, created_at, read_at
`

type MarkNotificationReadParams struct {
	TenantID        pgtype.UUID `json:"tenant_id"`
	RecipientUserID string      `json:"recipient_user_id"`
	ID              pgtype.UUID `json:"id"`
}

// Recipient-scoped mark-read. Idempotent: re-marking an already-read
// notification preserves the original read_at (COALESCE keeps the
// earliest timestamp).
func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationRead, arg.TenantID, arg.RecipientUserID, arg.ID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RecipientUserID,
		&i.Type,
		&i.Payload,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}
