// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oidc_idp_configs.sql

package dbx

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOidcIdpConfig = `-- name: CreateOidcIdpConfig :one
INSERT INTO oidc_idp_configs (
    id, tenant_id, name, issuer_url, client_id, client_secret_enc, redirect_url, allowed_email_domains
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, tenant_id, name, issuer_url, client_id, client_secret_enc, redirect_url, allowed_email_domains, created_at, updated_at
`

type CreateOidcIdpConfigParams struct {
	ID                  pgtype.UUID `json:"id"`
	TenantID            pgtype.UUID `json:"tenant_id"`
	Name                string      `json:"name"`
	IssuerUrl           string      `json:"issuer_url"`
	ClientID            string      `json:"client_id"`
	ClientSecretEnc     []byte      `json:"client_secret_enc"`
	RedirectUrl         string      `json:"redirect_url"`
	AllowedEmailDomains []string    `json:"allowed_email_domains"`
}

func (q *Queries) CreateOidcIdpConfig(ctx context.Context, arg CreateOidcIdpConfigParams) (OidcIdpConfig, error) {
	row := q.db.QueryRow(ctx, createOidcIdpConfig,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.IssuerUrl,
		arg.ClientID,
		arg.ClientSecretEnc,
		arg.RedirectUrl,
		arg.AllowedEmailDomains,
	)
	var i OidcIdpConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.IssuerUrl,
		&i.ClientID,
		&i.ClientSecretEnc,
		&i.RedirectUrl,
		&i.AllowedEmailDomains,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOidcIdpConfigByName = `-- name: GetOidcIdpConfigByName :one
SELECT id, tenant_id, name, issuer_url, client_id, client_secret_enc, redirect_url, allowed_email_domains, created_at, updated_at
FROM oidc_idp_configs
WHERE tenant_id = $1 AND name = $2
`

type GetOidcIdpConfigByNameParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Name     string      `json:"name"`
}

func (q *Queries) GetOidcIdpConfigByName(ctx context.Context, arg GetOidcIdpConfigByNameParams) (OidcIdpConfig, error) {
	row := q.db.QueryRow(ctx, getOidcIdpConfigByName, arg.TenantID, arg.Name)
	var i OidcIdpConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.IssuerUrl,
		&i.ClientID,
		&i.ClientSecretEnc,
		&i.RedirectUrl,
		&i.AllowedEmailDomains,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOidcIdpConfigsByTenant = `-- name: ListOidcIdpConfigsByTenant :many
SELECT id, tenant_id, name, issuer_url, client_id, client_secret_enc, redirect_url, allowed_email_domains, created_at, updated_at
FROM oidc_idp_configs
WHERE tenant_id = $1
ORDER BY name ASC
`

func (q *Queries) ListOidcIdpConfigsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]OidcIdpConfig, error) {
	rows, err := q.db.Query(ctx, listOidcIdpConfigsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OidcIdpConfig
	for rows.Next() {
		var i OidcIdpConfig
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.IssuerUrl,
			&i.ClientID,
			&i.ClientSecretEnc,
			&i.RedirectUrl,
			&i.AllowedEmailDomains,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
