// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: personnel_security.sql

package dbx

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completePersonnelChecklistItem = `-- name: CompletePersonnelChecklistItem :one
UPDATE personnel_security_checklist_items
SET completed_at = $3,
    completed_by = $4,
    evidence_record_id = $5,
    evidence_uri = $6,
    notes = $7,
    updated_at = now()
WHERE tenant_id = $1
  AND id = $2
  AND completed_at IS NULL
RETURNING id, tenant_id, checklist_id, slug, title, category, sort_order, completed_at, completed_by, evidence_record_id, evidence_uri, notes, created_at, updated_at
`

type CompletePersonnelChecklistItemParams struct {
	TenantID         pgtype.UUID        `json:"tenant_id"`
	ID               pgtype.UUID        `json:"id"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	CompletedBy      *string            `json:"completed_by"`
	EvidenceRecordID pgtype.UUID        `json:"evidence_record_id"`
	EvidenceUri      string             `json:"evidence_uri"`
	Notes            string             `json:"notes"`
}

func (q *Queries) CompletePersonnelChecklistItem(ctx context.Context, arg CompletePersonnelChecklistItemParams) (PersonnelSecurityChecklistItem, error) {
	row := q.db.QueryRow(ctx, completePersonnelChecklistItem,
		arg.TenantID,
		arg.ID,
		arg.CompletedAt,
		arg.CompletedBy,
		arg.EvidenceRecordID,
		arg.EvidenceUri,
		arg.Notes,
	)
	var i PersonnelSecurityChecklistItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChecklistID,
		&i.Slug,
		&i.Title,
		&i.Category,
		&i.SortOrder,
		&i.CompletedAt,
		&i.CompletedBy,
		&i.EvidenceRecordID,
		&i.EvidenceUri,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countOpenPersonnelChecklistItems = `-- name: CountOpenPersonnelChecklistItems :one
SELECT count(*)
FROM personnel_security_checklist_items
WHERE tenant_id = $1
  AND checklist_id = $2
  AND completed_at IS NULL
`

type CountOpenPersonnelChecklistItemsParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	ChecklistID pgtype.UUID `json:"checklist_id"`
}

func (q *Queries) CountOpenPersonnelChecklistItems(ctx context.Context, arg CountOpenPersonnelChecklistItemsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenPersonnelChecklistItems, arg.TenantID, arg.ChecklistID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPersonnelChecklistsForTenant = `-- name: CountPersonnelChecklistsForTenant :one
SELECT count(*)
FROM personnel_security_checklists
WHERE tenant_id = $1
`

func (q *Queries) CountPersonnelChecklistsForTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPersonnelChecklistsForTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPersonnelChecklist = `-- name: GetPersonnelChecklist :one
SELECT id, tenant_id, workflow_kind, source, source_event_id, person_external_id, person_work_email, person_display_name, control_id, due_at, status, created_by, created_at, updated_at, completed_at
FROM personnel_security_checklists
WHERE tenant_id = $1 AND id = $2
`

type GetPersonnelChecklistParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetPersonnelChecklist(ctx context.Context, arg GetPersonnelChecklistParams) (PersonnelSecurityChecklist, error) {
	row := q.db.QueryRow(ctx, getPersonnelChecklist, arg.TenantID, arg.ID)
	var i PersonnelSecurityChecklist
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkflowKind,
		&i.Source,
		&i.SourceEventID,
		&i.PersonExternalID,
		&i.PersonWorkEmail,
		&i.PersonDisplayName,
		&i.ControlID,
		&i.DueAt,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getPersonnelChecklistBySourceEvent = `-- name: GetPersonnelChecklistBySourceEvent :one
SELECT id, tenant_id, workflow_kind, source, source_event_id, person_external_id, person_work_email, person_display_name, control_id, due_at, status, created_by, created_at, updated_at, completed_at
FROM personnel_security_checklists
WHERE tenant_id = $1
  AND source = $2
  AND source_event_id = $3
`

type GetPersonnelChecklistBySourceEventParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	Source        string      `json:"source"`
	SourceEventID *string     `json:"source_event_id"`
}

func (q *Queries) GetPersonnelChecklistBySourceEvent(ctx context.Context, arg GetPersonnelChecklistBySourceEventParams) (PersonnelSecurityChecklist, error) {
	row := q.db.QueryRow(ctx, getPersonnelChecklistBySourceEvent, arg.TenantID, arg.Source, arg.SourceEventID)
	var i PersonnelSecurityChecklist
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkflowKind,
		&i.Source,
		&i.SourceEventID,
		&i.PersonExternalID,
		&i.PersonWorkEmail,
		&i.PersonDisplayName,
		&i.ControlID,
		&i.DueAt,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getPersonnelChecklistItem = `-- name: GetPersonnelChecklistItem :one
SELECT id, tenant_id, checklist_id, slug, title, category, sort_order, completed_at, completed_by, evidence_record_id, evidence_uri, notes, created_at, updated_at
FROM personnel_security_checklist_items
WHERE tenant_id = $1 AND id = $2
`

type GetPersonnelChecklistItemParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetPersonnelChecklistItem(ctx context.Context, arg GetPersonnelChecklistItemParams) (PersonnelSecurityChecklistItem, error) {
	row := q.db.QueryRow(ctx, getPersonnelChecklistItem, arg.TenantID, arg.ID)
	var i PersonnelSecurityChecklistItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChecklistID,
		&i.Slug,
		&i.Title,
		&i.Category,
		&i.SortOrder,
		&i.CompletedAt,
		&i.CompletedBy,
		&i.EvidenceRecordID,
		&i.EvidenceUri,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPersonnelChecklist = `-- name: InsertPersonnelChecklist :one

INSERT INTO personnel_security_checklists (
    id, tenant_id, workflow_kind, source, source_event_id,
    person_external_id, person_work_email, person_display_name,
    control_id, due_at, created_by
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9, $10, $11
)
RETURNING id, tenant_id, workflow_kind, source, source_event_id, person_external_id, person_work_email, person_display_name, control_id, due_at, status, created_by, created_at, updated_at, completed_at
`

type InsertPersonnelChecklistParams struct {
	ID                pgtype.UUID        `json:"id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	WorkflowKind      string             `json:"workflow_kind"`
	Source            string             `json:"source"`
	SourceEventID     *string            `json:"source_event_id"`
	PersonExternalID  string             `json:"person_external_id"`
	PersonWorkEmail   string             `json:"person_work_email"`
	PersonDisplayName string             `json:"person_display_name"`
	ControlID         pgtype.UUID        `json:"control_id"`
	DueAt             pgtype.Timestamptz `json:"due_at"`
	CreatedBy         string             `json:"created_by"`
}

// Personnel-security onboarding/offboarding workflow queries.
func (q *Queries) InsertPersonnelChecklist(ctx context.Context, arg InsertPersonnelChecklistParams) (PersonnelSecurityChecklist, error) {
	row := q.db.QueryRow(ctx, insertPersonnelChecklist,
		arg.ID,
		arg.TenantID,
		arg.WorkflowKind,
		arg.Source,
		arg.SourceEventID,
		arg.PersonExternalID,
		arg.PersonWorkEmail,
		arg.PersonDisplayName,
		arg.ControlID,
		arg.DueAt,
		arg.CreatedBy,
	)
	var i PersonnelSecurityChecklist
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkflowKind,
		&i.Source,
		&i.SourceEventID,
		&i.PersonExternalID,
		&i.PersonWorkEmail,
		&i.PersonDisplayName,
		&i.ControlID,
		&i.DueAt,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertPersonnelChecklistItem = `-- name: InsertPersonnelChecklistItem :one
INSERT INTO personnel_security_checklist_items (
    id, tenant_id, checklist_id, slug, title, category, sort_order
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, tenant_id, checklist_id, slug, title, category, sort_order, completed_at, completed_by, evidence_record_id, evidence_uri, notes, created_at, updated_at
`

type InsertPersonnelChecklistItemParams struct {
	ID          pgtype.UUID `json:"id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
	ChecklistID pgtype.UUID `json:"checklist_id"`
	Slug        string      `json:"slug"`
	Title       string      `json:"title"`
	Category    string      `json:"category"`
	SortOrder   int32       `json:"sort_order"`
}

func (q *Queries) InsertPersonnelChecklistItem(ctx context.Context, arg InsertPersonnelChecklistItemParams) (PersonnelSecurityChecklistItem, error) {
	row := q.db.QueryRow(ctx, insertPersonnelChecklistItem,
		arg.ID,
		arg.TenantID,
		arg.ChecklistID,
		arg.Slug,
		arg.Title,
		arg.Category,
		arg.SortOrder,
	)
	var i PersonnelSecurityChecklistItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChecklistID,
		&i.Slug,
		&i.Title,
		&i.Category,
		&i.SortOrder,
		&i.CompletedAt,
		&i.CompletedBy,
		&i.EvidenceRecordID,
		&i.EvidenceUri,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOverdueOffboardingChecklists = `-- name: ListOverdueOffboardingChecklists :many
SELECT id, tenant_id, workflow_kind, source, source_event_id, person_external_id, person_work_email, person_display_name, control_id, due_at, status, created_by, created_at, updated_at, completed_at
FROM personnel_security_checklists
WHERE tenant_id = $1
  AND workflow_kind = 'offboarding'
  AND status = 'open'
  AND due_at < $2
ORDER BY due_at ASC, id ASC
`

type ListOverdueOffboardingChecklistsParams struct {
	TenantID pgtype.UUID        `json:"tenant_id"`
	DueAt    pgtype.Timestamptz `json:"due_at"`
}

func (q *Queries) ListOverdueOffboardingChecklists(ctx context.Context, arg ListOverdueOffboardingChecklistsParams) ([]PersonnelSecurityChecklist, error) {
	rows, err := q.db.Query(ctx, listOverdueOffboardingChecklists, arg.TenantID, arg.DueAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PersonnelSecurityChecklist
	for rows.Next() {
		var i PersonnelSecurityChecklist
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WorkflowKind,
			&i.Source,
			&i.SourceEventID,
			&i.PersonExternalID,
			&i.PersonWorkEmail,
			&i.PersonDisplayName,
			&i.ControlID,
			&i.DueAt,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonnelChecklistItems = `-- name: ListPersonnelChecklistItems :many
SELECT id, tenant_id, checklist_id, slug, title, category, sort_order, completed_at, completed_by, evidence_record_id, evidence_uri, notes, created_at, updated_at
FROM personnel_security_checklist_items
WHERE tenant_id = $1 AND checklist_id = $2
ORDER BY sort_order ASC, id ASC
`

type ListPersonnelChecklistItemsParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	ChecklistID pgtype.UUID `json:"checklist_id"`
}

func (q *Queries) ListPersonnelChecklistItems(ctx context.Context, arg ListPersonnelChecklistItemsParams) ([]PersonnelSecurityChecklistItem, error) {
	rows, err := q.db.Query(ctx, listPersonnelChecklistItems, arg.TenantID, arg.ChecklistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PersonnelSecurityChecklistItem
	for rows.Next() {
		var i PersonnelSecurityChecklistItem
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ChecklistID,
			&i.Slug,
			&i.Title,
			&i.Category,
			&i.SortOrder,
			&i.CompletedAt,
			&i.CompletedBy,
			&i.EvidenceRecordID,
			&i.EvidenceUri,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonnelChecklists = `-- name: ListPersonnelChecklists :many
SELECT id, tenant_id, workflow_kind, source, source_event_id, person_external_id, person_work_email, person_display_name, control_id, due_at, status, created_by, created_at, updated_at, completed_at
FROM personnel_security_checklists
WHERE tenant_id = $1
  AND ($2::text IS NULL
       OR workflow_kind = $2::text)
  AND ($3::text IS NULL
       OR status = $3::text)
  AND (NOT $4::boolean
       OR (status = 'open' AND due_at < $5::timestamptz))
ORDER BY due_at ASC, id ASC
`

type ListPersonnelChecklistsParams struct {
	TenantID     pgtype.UUID        `json:"tenant_id"`
	WorkflowKind *string            `json:"workflow_kind"`
	Status       *string            `json:"status"`
	OverdueOnly  bool               `json:"overdue_only"`
	NowTs        pgtype.Timestamptz `json:"now_ts"`
}

// OE-663: the checklist-index read behind GET /v1/personnel-security/
// checklists. Optional filters compose via the sqlc.narg NULL-collapse
// pattern (see control_detail.sql): a NULL arg keeps the predicate
// vacuously true. overdue_only narrows to open checklists whose due_at
// has passed, mirroring ListOverdueOffboardingChecklists but across
// both workflow kinds.
func (q *Queries) ListPersonnelChecklists(ctx context.Context, arg ListPersonnelChecklistsParams) ([]PersonnelSecurityChecklist, error) {
	rows, err := q.db.Query(ctx, listPersonnelChecklists,
		arg.TenantID,
		arg.WorkflowKind,
		arg.Status,
		arg.OverdueOnly,
		arg.NowTs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PersonnelSecurityChecklist
	for rows.Next() {
		var i PersonnelSecurityChecklist
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WorkflowKind,
			&i.Source,
			&i.SourceEventID,
			&i.PersonExternalID,
			&i.PersonWorkEmail,
			&i.PersonDisplayName,
			&i.ControlID,
			&i.DueAt,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPersonnelChecklistCompleted = `-- name: MarkPersonnelChecklistCompleted :one
UPDATE personnel_security_checklists
SET status = 'completed',
    completed_at = $3,
    updated_at = now()
WHERE tenant_id = $1
  AND id = $2
  AND status = 'open'
RETURNING id, tenant_id, workflow_kind, source, source_event_id, person_external_id, person_work_email, person_display_name, control_id, due_at, status, created_by, created_at, updated_at, completed_at
`

type MarkPersonnelChecklistCompletedParams struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	ID          pgtype.UUID        `json:"id"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) MarkPersonnelChecklistCompleted(ctx context.Context, arg MarkPersonnelChecklistCompletedParams) (PersonnelSecurityChecklist, error) {
	row := q.db.QueryRow(ctx, markPersonnelChecklistCompleted, arg.TenantID, arg.ID, arg.CompletedAt)
	var i PersonnelSecurityChecklist
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkflowKind,
		&i.Source,
		&i.SourceEventID,
		&i.PersonExternalID,
		&i.PersonWorkEmail,
		&i.PersonDisplayName,
		&i.ControlID,
		&i.DueAt,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}
