// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbx

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Idempotent: ON CONFLICT DO NOTHING because the PK already enforces no
	// duplicates, so re-adding is a no-op.
	AddVendorScopeCell(ctx context.Context, arg AddVendorScopeCellParams) error
	// Used before re-binding the full cell set on an update.
	ClearVendorScopeCells(ctx context.Context, arg ClearVendorScopeCellsParams) error
	CountRiskControlLinks(ctx context.Context, arg CountRiskControlLinksParams) (int64, error)
	CountSCFAnchorsForVersion(ctx context.Context, frameworkVersionID pgtype.UUID) (int64, error)
	CountScopeCells(ctx context.Context, tenantID pgtype.UUID) (int64, error)
	// AC-3 burndown: returns total + overdue counts per criticality band. Used
	// by the dashboard panel (slice 040) and the quarterly board pack (slice 032).
	// Returns one row per criticality present in the result set; empty bands are
	// not included (callers fill in zero where needed).
	CountVendorsForBurndown(ctx context.Context, arg CountVendorsForBurndownParams) ([]CountVendorsForBurndownRow, error)
	// Insert a new risk. The application validates methodology-specific
	// inherent_score and per-treatment required fields BEFORE calling this.
	// DB-side CHECK constraints (slice 019) are defense-in-depth, not the
	// primary validation path.
	CreateRisk(ctx context.Context, arg CreateRiskParams) (Risk, error)
	// Insert a scope cell. dimensions_hash is the application-computed canonical
	// hash; the UNIQUE (tenant_id, dimensions_hash) constraint rejects duplicates.
	CreateScopeCell(ctx context.Context, arg CreateScopeCellParams) (ScopeCell, error)
	// Insert a per-tenant scope dimension declaration. Used by the bootstrap seed
	// (is_builtin=true) and by admins adding custom dimensions (is_builtin=false).
	// tenant_id is captured directly so RLS evaluates the policy on insert.
	CreateScopeDimension(ctx context.Context, arg CreateScopeDimensionParams) (ScopeDimension, error)
	// Insert a vendor. tenant_id is captured directly so RLS evaluates the
	// INSERT WITH CHECK policy. dpa_signed_at is required by CHECK constraint
	// whenever dpa_signed=true.
	CreateVendor(ctx context.Context, arg CreateVendorParams) (Vendor, error)
	DeleteRisk(ctx context.Context, arg DeleteRiskParams) error
	DeleteVendor(ctx context.Context, arg DeleteVendorParams) error
	// Flip every "current" framework_version for the given framework to "legacy"
	// so a new release can take over without violating the at-most-one-current
	// invariant. Caller scopes the transaction.
	DemoteCurrentFrameworkVersions(ctx context.Context, frameworkID pgtype.UUID) error
	// Returns the JSON-encoded applicability_expr for a single control. The column
	// is TEXT (slice 002); slice 017 stores JSON in that text.
	GetControlApplicabilityExpr(ctx context.Context, arg GetControlApplicabilityExprParams) (GetControlApplicabilityExprRow, error)
	// Look up one schema visible to the tenant. Prefers the tenant's private
	// row when one exists for the same (kind, semver); otherwise returns the
	// global row. The ORDER BY puts the non-null tenant_id first.
	GetEvidenceKindSchemaForTenant(ctx context.Context, arg GetEvidenceKindSchemaForTenantParams) (EvidenceKindSchema, error)
	// Look up one global schema by (kind, semver). Used by the GET endpoint
	// when no tenant is supplied and by the push validator before slice 013
	// lands tenant-private validation.
	GetEvidenceKindSchemaGlobal(ctx context.Context, arg GetEvidenceKindSchemaGlobalParams) (EvidenceKindSchema, error)
	GetRiskByID(ctx context.Context, arg GetRiskByIDParams) (Risk, error)
	GetSCFAnchorByID(ctx context.Context, id pgtype.UUID) (ScfAnchor, error)
	// Look up an anchor by its SCF code (e.g., "IAC-06") in the current SCF
	// framework version.
	GetSCFAnchorBySCFID(ctx context.Context, scfID string) (ScfAnchor, error)
	// Existing-row lookup. Returns ErrNoRows when the anchor doesn't exist yet.
	// The importer calls this first to classify the upsert as Created /
	// Updated / Unchanged (xmax-based detection inside ON CONFLICT can't
	// distinguish "updated to the same content" from "actually updated").
	GetSCFAnchorByVersionAndSCFID(ctx context.Context, arg GetSCFAnchorByVersionAndSCFIDParams) (ScfAnchor, error)
	// Look up a cell by its dimensions hash. Used by the "create or get" path so
	// a re-seed call does not 409 on the existing default cell.
	GetScopeCellByHash(ctx context.Context, arg GetScopeCellByHashParams) (ScopeCell, error)
	GetScopeCellByID(ctx context.Context, arg GetScopeCellByIDParams) (ScopeCell, error)
	// Resolve a dimension by name within the current tenant context.
	GetScopeDimensionByName(ctx context.Context, arg GetScopeDimensionByNameParams) (ScopeDimension, error)
	GetVendor(ctx context.Context, arg GetVendorParams) (Vendor, error)
	// Returns risk counts grouped by (likelihood, impact) for risks whose
	// methodology shares the 5x5 (likelihood, impact 1..5) shape. nist_800_30
	// and qualitative_5x5 both use this shape (canvas §2.2 + AC-7); other
	// methodologies (FAIR has LEF/LM) are intentionally excluded so the
	// heatmap stays a single coherent visualization.
	//
	// The CAST chain (jsonb -> text -> int) is necessary because pgx cannot
	// read jsonb-number values directly as int4 without an explicit cast.
	HeatmapBuckets(ctx context.Context, tenantID pgtype.UUID) ([]HeatmapBucketsRow, error)
	// Insert a new schema row. The caller (slice 014 registry service) parses
	// semver into major/minor/patch and supplies all three; the DB CHECK
	// prevents negatives. Owner must be non-empty (CHECK constraint). The
	// partial unique indexes on (kind, semver) WHERE tenant_id IS NULL and
	// (tenant_id, kind, semver) WHERE tenant_id IS NOT NULL enforce
	// duplicate-version rejection.
	InsertEvidenceKindSchema(ctx context.Context, arg InsertEvidenceKindSchemaParams) (EvidenceKindSchema, error)
	// Insert a fresh anchor (use after GetSCFAnchorByVersionAndSCFID returned
	// ErrNoRows). Uniqueness is enforced by (framework_version_id, scf_id).
	InsertSCFAnchor(ctx context.Context, arg InsertSCFAnchorParams) (ScfAnchor, error)
	// Idempotent: ON CONFLICT DO NOTHING so re-running a "link these controls"
	// request does not 23505 on a re-link.
	LinkRiskControl(ctx context.Context, arg LinkRiskControlParams) error
	// Bypass-RLS path used at boot by the platform-schema importer running as
	// atlas_migrate. Returns every row regardless of tenant. Never reachable
	// through the app role under RLS.
	ListAllEvidenceKindSchemas(ctx context.Context) ([]EvidenceKindSchema, error)
	// Returns every registered semver for a kind, visible to the tenant.
	// Slice 014 uses this for AC-5 semver enforcement (a POST must check the
	// prior versions of the same kind before accepting a new one).
	ListEvidenceKindSchemaVersionsForKind(ctx context.Context, arg ListEvidenceKindSchemaVersionsForKindParams) ([]EvidenceKindSchema, error)
	// Returns every schema visible to the current tenant — both global rows
	// (tenant_id IS NULL) and the tenant's private rows. RLS already gates
	// tenant rows, but the WHERE clause is explicit so the query is the same
	// shape with or without RLS in effect.
	ListEvidenceKindSchemasForTenant(ctx context.Context, arg ListEvidenceKindSchemasForTenantParams) ([]EvidenceKindSchema, error)
	// Returns every globally-registered schema (tenant_id IS NULL). The HTTP
	// list endpoint pages with limit/offset; ordering by (kind, major DESC,
	// minor DESC, patch DESC) puts the newest versions first within each kind.
	ListEvidenceKindSchemasGlobal(ctx context.Context, arg ListEvidenceKindSchemasGlobalParams) ([]EvidenceKindSchema, error)
	ListFrameworkVersionsBySlug(ctx context.Context, slug string) ([]FrameworkVersion, error)
	ListFrameworks(ctx context.Context) ([]Framework, error)
	// AC-4 overdue calc — vendors whose last_review_date + cadence is older than
	// the cutoff date. NULL last_review_date means "never reviewed" which always
	// counts as overdue (a vendor with no review on file is by definition past
	// due). Cadence -> interval mapping happens with a CASE in SQL so the query
	// plan is stable. Cutoff is passed as DATE so the caller controls "now"
	// (testability) and timezone semantics (vendor reviews are date-granular,
	// not timestamp-granular).
	ListOverdueVendors(ctx context.Context, arg ListOverdueVendorsParams) ([]Vendor, error)
	// Returns all control links for a single risk.
	ListRiskControlLinks(ctx context.Context, arg ListRiskControlLinksParams) ([]ListRiskControlLinksRow, error)
	// Enumerate all risks for the tenant, newest first. Filters are applied
	// in the application layer because sqlc's static typing makes optional
	// WHERE clauses noisy; the row count is bounded by tenant-size anyway.
	ListRisks(ctx context.Context, tenantID pgtype.UUID) ([]Risk, error)
	// Paginated anchor list for a specific framework_version. Caller supplies
	// limit + offset; default at the call site.
	ListSCFAnchorsForVersion(ctx context.Context, arg ListSCFAnchorsForVersionParams) ([]ScfAnchor, error)
	// Paginated anchor list for the latest current SCF framework_version.
	ListSCFAnchorsLatest(ctx context.Context, arg ListSCFAnchorsLatestParams) ([]ScfAnchor, error)
	// Enumerate the active tenant's scope cells. Newest first.
	ListScopeCells(ctx context.Context, tenantID pgtype.UUID) ([]ScopeCell, error)
	// Enumerate the active tenant's declared dimensions. Ordering: builtins first
	// (stable presentation in the admin UI), then alphabetical by name.
	ListScopeDimensions(ctx context.Context, tenantID pgtype.UUID) ([]ScopeDimension, error)
	// Cells attached to one vendor.
	ListVendorScopeCells(ctx context.Context, arg ListVendorScopeCellsParams) ([]pgtype.UUID, error)
	// AC-2 filter by criticality. NULL criticality_filter means "all" — the
	// (sqlc.narg('criticality')::vendor_criticality IS NULL OR criticality = sqlc.narg('criticality'))
	// pattern keeps the query plan stable and lets sqlc emit a *VendorCriticality
	// parameter so callers can pass nil for "no filter".
	ListVendors(ctx context.Context, arg ListVendorsParams) ([]Vendor, error)
	// Point a framework at its current version.
	SetLatestVersion(ctx context.Context, arg SetLatestVersionParams) error
	UnlinkRiskControl(ctx context.Context, arg UnlinkRiskControlParams) error
	// Full-update path (PATCH handler reads existing, mutates fields, writes).
	// updated_at is set explicitly so the schema's per-row default doesn't
	// silently keep stale values.
	UpdateRisk(ctx context.Context, arg UpdateRiskParams) (Risk, error)
	// Update an existing anchor in place. Touches updated_at; the caller
	// decides whether to call this based on a content-equality check.
	UpdateSCFAnchor(ctx context.Context, arg UpdateSCFAnchorParams) (ScfAnchor, error)
	// Full-row update. Caller is responsible for sending every field; partial
	// updates are not supported in lite (no PATCH semantics merge). updated_at
	// is application-owned (no trigger).
	UpdateVendor(ctx context.Context, arg UpdateVendorParams) (Vendor, error)
	// Insert or update a framework row. The (tenant_id, slug) UNIQUE constraint
	// in slice 002's schema treats NULLs as distinct, so a partial unique index
	// on slug-when-tenant-is-null would be needed to catch global-catalog dupes
	// via the natural key. To avoid a follow-on migration, the importer uses a
	// deterministic id derived from the slug; ON CONFLICT (id) DO UPDATE then
	// handles re-imports cleanly.
	UpsertFramework(ctx context.Context, arg UpsertFrameworkParams) (Framework, error)
	// Insert or update a framework_versions row. Same deterministic-id pattern
	// as UpsertFramework above (avoids the NULLs-distinct gotcha on natural-key
	// ON CONFLICT targets).
	UpsertFrameworkVersion(ctx context.Context, arg UpsertFrameworkVersionParams) (FrameworkVersion, error)
}

var _ Querier = (*Queries)(nil)
