// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: risks.sql

package dbx

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRiskControlLinks = `-- name: CountRiskControlLinks :one
SELECT COUNT(*)::bigint
FROM risk_control_links
WHERE tenant_id = $1 AND risk_id = $2
`

type CountRiskControlLinksParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	RiskID   pgtype.UUID `json:"risk_id"`
}

func (q *Queries) CountRiskControlLinks(ctx context.Context, arg CountRiskControlLinksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRiskControlLinks, arg.TenantID, arg.RiskID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createAggregateRisk = `-- name: CreateAggregateRisk :one
INSERT INTO risks (
    id, tenant_id, title, description, category, methodology,
    inherent_score, treatment, treatment_owner, residual_score,
    accepter, instrument_reference, level, org_unit_id, themes
)
VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12, $13, $14, $15::text[]
)
RETURNING id, tenant_id, title, description, category, methodology, inherent_score, treatment, treatment_owner, residual_score, review_due_at, created_at, updated_at, accepted_until, accepter, instrument_reference, level, org_unit_id, themes
`

type CreateAggregateRiskParams struct {
	ID                  pgtype.UUID     `json:"id"`
	TenantID            pgtype.UUID     `json:"tenant_id"`
	Title               string          `json:"title"`
	Description         string          `json:"description"`
	Category            RiskCategory    `json:"category"`
	Methodology         RiskMethodology `json:"methodology"`
	InherentScore       []byte          `json:"inherent_score"`
	Treatment           RiskTreatment   `json:"treatment"`
	TreatmentOwner      string          `json:"treatment_owner"`
	ResidualScore       []byte          `json:"residual_score"`
	Accepter            string          `json:"accepter"`
	InstrumentReference string          `json:"instrument_reference"`
	Level               RiskLevel       `json:"level"`
	OrgUnitID           pgtype.UUID     `json:"org_unit_id"`
	Column15            []string        `json:"column_15"`
}

// Insert a parent risk for slice 053 manual aggregation. The shape mirrors
// CreateRisk but with `level`, `org_unit_id`, and `themes` plumbed through —
// those columns exist on `risks` per slice 052's ALTER. The aggregated
// severity, severity_function, child_count, and aggregation_key live inside
// the `inherent_score` JSONB.
func (q *Queries) CreateAggregateRisk(ctx context.Context, arg CreateAggregateRiskParams) (Risk, error) {
	row := q.db.QueryRow(ctx, createAggregateRisk,
		arg.ID,
		arg.TenantID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.Methodology,
		arg.InherentScore,
		arg.Treatment,
		arg.TreatmentOwner,
		arg.ResidualScore,
		arg.Accepter,
		arg.InstrumentReference,
		arg.Level,
		arg.OrgUnitID,
		arg.Column15,
	)
	var i Risk
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Methodology,
		&i.InherentScore,
		&i.Treatment,
		&i.TreatmentOwner,
		&i.ResidualScore,
		&i.ReviewDueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcceptedUntil,
		&i.Accepter,
		&i.InstrumentReference,
		&i.Level,
		&i.OrgUnitID,
		&i.Themes,
	)
	return i, err
}

const createRisk = `-- name: CreateRisk :one
INSERT INTO risks (
    id, tenant_id, title, description, category, methodology,
    inherent_score, treatment, treatment_owner, residual_score,
    review_due_at, accepted_until, accepter, instrument_reference
)
VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12, $13, $14
)
RETURNING id, tenant_id, title, description, category, methodology, inherent_score, treatment, treatment_owner, residual_score, review_due_at, created_at, updated_at, accepted_until, accepter, instrument_reference, level, org_unit_id, themes
`

type CreateRiskParams struct {
	ID                  pgtype.UUID        `json:"id"`
	TenantID            pgtype.UUID        `json:"tenant_id"`
	Title               string             `json:"title"`
	Description         string             `json:"description"`
	Category            RiskCategory       `json:"category"`
	Methodology         RiskMethodology    `json:"methodology"`
	InherentScore       []byte             `json:"inherent_score"`
	Treatment           RiskTreatment      `json:"treatment"`
	TreatmentOwner      string             `json:"treatment_owner"`
	ResidualScore       []byte             `json:"residual_score"`
	ReviewDueAt         pgtype.Timestamptz `json:"review_due_at"`
	AcceptedUntil       pgtype.Date        `json:"accepted_until"`
	Accepter            string             `json:"accepter"`
	InstrumentReference string             `json:"instrument_reference"`
}

// Insert a new risk. The application validates methodology-specific
// inherent_score and per-treatment required fields BEFORE calling this.
// DB-side CHECK constraints (slice 019) are defense-in-depth, not the
// primary validation path.
func (q *Queries) CreateRisk(ctx context.Context, arg CreateRiskParams) (Risk, error) {
	row := q.db.QueryRow(ctx, createRisk,
		arg.ID,
		arg.TenantID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.Methodology,
		arg.InherentScore,
		arg.Treatment,
		arg.TreatmentOwner,
		arg.ResidualScore,
		arg.ReviewDueAt,
		arg.AcceptedUntil,
		arg.Accepter,
		arg.InstrumentReference,
	)
	var i Risk
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Methodology,
		&i.InherentScore,
		&i.Treatment,
		&i.TreatmentOwner,
		&i.ResidualScore,
		&i.ReviewDueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcceptedUntil,
		&i.Accepter,
		&i.InstrumentReference,
		&i.Level,
		&i.OrgUnitID,
		&i.Themes,
	)
	return i, err
}

const deleteRisk = `-- name: DeleteRisk :exec
DELETE FROM risks
WHERE tenant_id = $1 AND id = $2
`

type DeleteRiskParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteRisk(ctx context.Context, arg DeleteRiskParams) error {
	_, err := q.db.Exec(ctx, deleteRisk, arg.TenantID, arg.ID)
	return err
}

const getRiskByAggregationKey = `-- name: GetRiskByAggregationKey :one
SELECT id, tenant_id, title, description, category, methodology, inherent_score, treatment, treatment_owner, residual_score, review_due_at, created_at, updated_at, accepted_until, accepter, instrument_reference, level, org_unit_id, themes
FROM risks
WHERE tenant_id = $1
  AND inherent_score->>'aggregation_key' = $2::text
LIMIT 1
`

type GetRiskByAggregationKeyParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Column2  string      `json:"column_2"`
}

// Lookup an existing parent risk by the sha256 idempotency key stored on
// inherent_score. Used by slice 053's POST /v1/risks/aggregate to satisfy
// AC-7: same (parent_title, child_set) returns the existing parent
// rather than creating a duplicate.
//
// The $2::text cast pins the parameter type to text (sqlc's inference
// otherwise borrows the type of `inherent_score`, which is bytea via JSONB
// and would force the caller to pass []byte).
func (q *Queries) GetRiskByAggregationKey(ctx context.Context, arg GetRiskByAggregationKeyParams) (Risk, error) {
	row := q.db.QueryRow(ctx, getRiskByAggregationKey, arg.TenantID, arg.Column2)
	var i Risk
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Methodology,
		&i.InherentScore,
		&i.Treatment,
		&i.TreatmentOwner,
		&i.ResidualScore,
		&i.ReviewDueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcceptedUntil,
		&i.Accepter,
		&i.InstrumentReference,
		&i.Level,
		&i.OrgUnitID,
		&i.Themes,
	)
	return i, err
}

const getRiskByID = `-- name: GetRiskByID :one
SELECT id, tenant_id, title, description, category, methodology, inherent_score, treatment, treatment_owner, residual_score, review_due_at, created_at, updated_at, accepted_until, accepter, instrument_reference, level, org_unit_id, themes
FROM risks
WHERE tenant_id = $1 AND id = $2
`

type GetRiskByIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetRiskByID(ctx context.Context, arg GetRiskByIDParams) (Risk, error) {
	row := q.db.QueryRow(ctx, getRiskByID, arg.TenantID, arg.ID)
	var i Risk
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Methodology,
		&i.InherentScore,
		&i.Treatment,
		&i.TreatmentOwner,
		&i.ResidualScore,
		&i.ReviewDueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcceptedUntil,
		&i.Accepter,
		&i.InstrumentReference,
		&i.Level,
		&i.OrgUnitID,
		&i.Themes,
	)
	return i, err
}

const heatmapBuckets = `-- name: HeatmapBuckets :many
SELECT
    (inherent_score->>'likelihood')::int  AS likelihood,
    (inherent_score->>'impact')::int      AS impact,
    COUNT(*)::int                         AS count
FROM risks
WHERE tenant_id = $1
  AND methodology IN ('nist_800_30', 'qualitative_5x5')
  AND jsonb_typeof(inherent_score->'likelihood') = 'number'
  AND jsonb_typeof(inherent_score->'impact')     = 'number'
  AND (inherent_score->>'likelihood')::int BETWEEN 1 AND 5
  AND (inherent_score->>'impact')::int     BETWEEN 1 AND 5
GROUP BY likelihood, impact
ORDER BY likelihood, impact
`

type HeatmapBucketsRow struct {
	Likelihood int32 `json:"likelihood"`
	Impact     int32 `json:"impact"`
	Count      int32 `json:"count"`
}

// Returns risk counts grouped by (likelihood, impact) for risks whose
// methodology shares the 5x5 (likelihood, impact 1..5) shape. nist_800_30
// and qualitative_5x5 both use this shape (canvas §2.2 + AC-7); other
// methodologies (FAIR has LEF/LM) are intentionally excluded so the
// heatmap stays a single coherent visualization.
//
// The CAST chain (jsonb -> text -> int) is necessary because pgx cannot
// read jsonb-number values directly as int4 without an explicit cast.
func (q *Queries) HeatmapBuckets(ctx context.Context, tenantID pgtype.UUID) ([]HeatmapBucketsRow, error) {
	rows, err := q.db.Query(ctx, heatmapBuckets, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HeatmapBucketsRow
	for rows.Next() {
		var i HeatmapBucketsRow
		if err := rows.Scan(&i.Likelihood, &i.Impact, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkRiskControl = `-- name: LinkRiskControl :exec
INSERT INTO risk_control_links (risk_id, control_id, tenant_id)
VALUES ($1, $2, $3)
ON CONFLICT (tenant_id, risk_id, control_id) DO NOTHING
`

type LinkRiskControlParams struct {
	RiskID    pgtype.UUID `json:"risk_id"`
	ControlID pgtype.UUID `json:"control_id"`
	TenantID  pgtype.UUID `json:"tenant_id"`
}

// Idempotent: ON CONFLICT DO NOTHING so re-running a "link these controls"
// request does not 23505 on a re-link.
func (q *Queries) LinkRiskControl(ctx context.Context, arg LinkRiskControlParams) error {
	_, err := q.db.Exec(ctx, linkRiskControl, arg.RiskID, arg.ControlID, arg.TenantID)
	return err
}

const listRiskControlLinks = `-- name: ListRiskControlLinks :many
SELECT control_id, created_at
FROM risk_control_links
WHERE tenant_id = $1 AND risk_id = $2
ORDER BY created_at ASC, control_id ASC
`

type ListRiskControlLinksParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	RiskID   pgtype.UUID `json:"risk_id"`
}

type ListRiskControlLinksRow struct {
	ControlID pgtype.UUID        `json:"control_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Returns all control links for a single risk.
func (q *Queries) ListRiskControlLinks(ctx context.Context, arg ListRiskControlLinksParams) ([]ListRiskControlLinksRow, error) {
	rows, err := q.db.Query(ctx, listRiskControlLinks, arg.TenantID, arg.RiskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRiskControlLinksRow
	for rows.Next() {
		var i ListRiskControlLinksRow
		if err := rows.Scan(&i.ControlID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRisks = `-- name: ListRisks :many
SELECT id, tenant_id, title, description, category, methodology, inherent_score, treatment, treatment_owner, residual_score, review_due_at, created_at, updated_at, accepted_until, accepter, instrument_reference, level, org_unit_id, themes
FROM risks
WHERE tenant_id = $1
ORDER BY created_at DESC, id ASC
`

// Enumerate all risks for the tenant, newest first. Filters are applied
// in the application layer because sqlc's static typing makes optional
// WHERE clauses noisy; the row count is bounded by tenant-size anyway.
func (q *Queries) ListRisks(ctx context.Context, tenantID pgtype.UUID) ([]Risk, error) {
	rows, err := q.db.Query(ctx, listRisks, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Risk
	for rows.Next() {
		var i Risk
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.Methodology,
			&i.InherentScore,
			&i.Treatment,
			&i.TreatmentOwner,
			&i.ResidualScore,
			&i.ReviewDueAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AcceptedUntil,
			&i.Accepter,
			&i.InstrumentReference,
			&i.Level,
			&i.OrgUnitID,
			&i.Themes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRisksByIDs = `-- name: ListRisksByIDs :many
SELECT id, tenant_id, title, description, category, methodology, inherent_score, treatment, treatment_owner, residual_score, review_due_at, created_at, updated_at, accepted_until, accepter, instrument_reference, level, org_unit_id, themes
FROM risks
WHERE tenant_id = $1 AND id = ANY($2::uuid[])
ORDER BY id ASC
`

type ListRisksByIDsParams struct {
	TenantID pgtype.UUID   `json:"tenant_id"`
	Column2  []pgtype.UUID `json:"column_2"`
}

// Reads a set of risks by id for the active tenant. RLS makes cross-tenant
// rows invisible; the caller compares len(returned)==len(requested) for the
// existence check.
func (q *Queries) ListRisksByIDs(ctx context.Context, arg ListRisksByIDsParams) ([]Risk, error) {
	rows, err := q.db.Query(ctx, listRisksByIDs, arg.TenantID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Risk
	for rows.Next() {
		var i Risk
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.Methodology,
			&i.InherentScore,
			&i.Treatment,
			&i.TreatmentOwner,
			&i.ResidualScore,
			&i.ReviewDueAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AcceptedUntil,
			&i.Accepter,
			&i.InstrumentReference,
			&i.Level,
			&i.OrgUnitID,
			&i.Themes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkRiskControl = `-- name: UnlinkRiskControl :exec
DELETE FROM risk_control_links
WHERE tenant_id = $1 AND risk_id = $2 AND control_id = $3
`

type UnlinkRiskControlParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	RiskID    pgtype.UUID `json:"risk_id"`
	ControlID pgtype.UUID `json:"control_id"`
}

func (q *Queries) UnlinkRiskControl(ctx context.Context, arg UnlinkRiskControlParams) error {
	_, err := q.db.Exec(ctx, unlinkRiskControl, arg.TenantID, arg.RiskID, arg.ControlID)
	return err
}

const updateRisk = `-- name: UpdateRisk :one
UPDATE risks
SET title = $3,
    description = $4,
    category = $5,
    methodology = $6,
    inherent_score = $7,
    treatment = $8,
    treatment_owner = $9,
    residual_score = $10,
    review_due_at = $11,
    accepted_until = $12,
    accepter = $13,
    instrument_reference = $14,
    updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, title, description, category, methodology, inherent_score, treatment, treatment_owner, residual_score, review_due_at, created_at, updated_at, accepted_until, accepter, instrument_reference, level, org_unit_id, themes
`

type UpdateRiskParams struct {
	TenantID            pgtype.UUID        `json:"tenant_id"`
	ID                  pgtype.UUID        `json:"id"`
	Title               string             `json:"title"`
	Description         string             `json:"description"`
	Category            RiskCategory       `json:"category"`
	Methodology         RiskMethodology    `json:"methodology"`
	InherentScore       []byte             `json:"inherent_score"`
	Treatment           RiskTreatment      `json:"treatment"`
	TreatmentOwner      string             `json:"treatment_owner"`
	ResidualScore       []byte             `json:"residual_score"`
	ReviewDueAt         pgtype.Timestamptz `json:"review_due_at"`
	AcceptedUntil       pgtype.Date        `json:"accepted_until"`
	Accepter            string             `json:"accepter"`
	InstrumentReference string             `json:"instrument_reference"`
}

// Full-update path (PATCH handler reads existing, mutates fields, writes).
// updated_at is set explicitly so the schema's per-row default doesn't
// silently keep stale values.
func (q *Queries) UpdateRisk(ctx context.Context, arg UpdateRiskParams) (Risk, error) {
	row := q.db.QueryRow(ctx, updateRisk,
		arg.TenantID,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.Methodology,
		arg.InherentScore,
		arg.Treatment,
		arg.TreatmentOwner,
		arg.ResidualScore,
		arg.ReviewDueAt,
		arg.AcceptedUntil,
		arg.Accepter,
		arg.InstrumentReference,
	)
	var i Risk
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Methodology,
		&i.InherentScore,
		&i.Treatment,
		&i.TreatmentOwner,
		&i.ResidualScore,
		&i.ReviewDueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcceptedUntil,
		&i.Accepter,
		&i.InstrumentReference,
		&i.Level,
		&i.OrgUnitID,
		&i.Themes,
	)
	return i, err
}

const updateRiskThemes = `-- name: UpdateRiskThemes :one
UPDATE risks
SET themes = $3::text[],
    updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, title, description, category, methodology, inherent_score, treatment, treatment_owner, residual_score, review_due_at, created_at, updated_at, accepted_until, accepter, instrument_reference, level, org_unit_id, themes
`

type UpdateRiskThemesParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
	Column3  []string    `json:"column_3"`
}

// Replaces the themes array on a risk. The application validates that every
// supplied theme is in the visible vocabulary (defaults + tenant-private)
// BEFORE calling. Returns the updated row. Slice 053 (POST/DELETE
// /v1/risks/{id}/themes).
func (q *Queries) UpdateRiskThemes(ctx context.Context, arg UpdateRiskThemesParams) (Risk, error) {
	row := q.db.QueryRow(ctx, updateRiskThemes, arg.TenantID, arg.ID, arg.Column3)
	var i Risk
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Methodology,
		&i.InherentScore,
		&i.Treatment,
		&i.TreatmentOwner,
		&i.ResidualScore,
		&i.ReviewDueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcceptedUntil,
		&i.Accepter,
		&i.InstrumentReference,
		&i.Level,
		&i.OrgUnitID,
		&i.Themes,
	)
	return i, err
}
