// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ucf_traversal.sql

package dbx

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getFrameworkVersionBySlugAndVersion = `-- name: GetFrameworkVersionBySlugAndVersion :one
SELECT fv.id, fv.tenant_id, fv.framework_id, fv.version, fv.effective_from, fv.effective_to, fv.status, fv.requirement_count, fv.oscal_catalog_uri, fv.created_at
FROM framework_versions fv
JOIN frameworks f ON f.id = fv.framework_id
WHERE f.slug = $1
  AND fv.version = $2
  AND f.tenant_id IS NULL
`

type GetFrameworkVersionBySlugAndVersionParams struct {
	Slug    string `json:"slug"`
	Version string `json:"version"`
}

// Resolves "?framework_version=slug:version" into a framework_versions
// row. Used by both the anchor->requirements and control->coverage
// handlers to translate the URL param into a stable id for the pinned
// traversal. NULL tenant_id constraint scopes to the global catalog.
func (q *Queries) GetFrameworkVersionBySlugAndVersion(ctx context.Context, arg GetFrameworkVersionBySlugAndVersionParams) (FrameworkVersion, error) {
	row := q.db.QueryRow(ctx, getFrameworkVersionBySlugAndVersion, arg.Slug, arg.Version)
	var i FrameworkVersion
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FrameworkID,
		&i.Version,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.Status,
		&i.RequirementCount,
		&i.OscalCatalogUri,
		&i.CreatedAt,
	)
	return i, err
}

const listAnchorsForRequirementWithEdges = `-- name: ListAnchorsForRequirementWithEdges :many

SELECT
    e.id                AS edge_id,
    e.scf_anchor_id,
    e.relationship_type,
    e.strength,
    e.source_attribution,
    e.mapping_tier,
    e.rationale,
    a.scf_id,
    a.family,
    a.title            AS anchor_title,
    a.description      AS anchor_description
FROM fw_to_scf_edges e
JOIN scf_anchors a ON a.id = e.scf_anchor_id
WHERE e.framework_requirement_id = $1
  AND e.relationship_type <> 'no_relationship'
ORDER BY e.strength DESC, a.scf_id
`

type ListAnchorsForRequirementWithEdgesRow struct {
	EdgeID            pgtype.UUID                `json:"edge_id"`
	ScfAnchorID       pgtype.UUID                `json:"scf_anchor_id"`
	RelationshipType  StrmRelationshipType       `json:"relationship_type"`
	Strength          float64                    `json:"strength"`
	SourceAttribution CrosswalkSourceAttribution `json:"source_attribution"`
	MappingTier       CrosswalkMappingTier       `json:"mapping_tier"`
	Rationale         string                     `json:"rationale"`
	ScfID             string                     `json:"scf_id"`
	Family            string                     `json:"family"`
	AnchorTitle       string                     `json:"anchor_title"`
	AnchorDescription string                     `json:"anchor_description"`
}

// Slice 008: UCF graph traversal queries.
//
// All traversals go through the SCF anchor spine (constitutional invariant 1
// per CLAUDE.md / canvas §3.1). The path is two index-backed JOINs, not a
// recursive CTE — see Plans/UCF_GRAPH_MODEL.md §7. Fan-out is bounded
// (typical requirement maps to 1-6 anchors; typical anchor maps to 1-8
// requirements) so the queries return in milliseconds at production
// cardinality.
//
// `no_relationship` STRM edges are filtered out of coverage responses
// (canvas §3.2 stores them as data to suppress false suggestions; they
// shouldn't appear in coverage views).
//
// Tenant scoping: queries that touch the `controls` table run inside the
// request's `app.current_tenant` GUC set by tenancy.Middleware; RLS does
// the filtering. Catalog tables (`framework_requirements`,
// `fw_to_scf_edges`, `scf_anchors`, `framework_versions`) have no
// tenant_id and no RLS — global, platform-bundled. No app-level
// `WHERE tenant_id = ?` clause is permitted on the controls reads
// (constitutional invariant 6 per CLAUDE.md / canvas §5.4).
// AC-1 (anchors arm). Given a framework_requirement id, return every
// non-`no_relationship` STRM edge to an SCF anchor, joined to scf_anchors
// so callers get scf_id + family + title in one round-trip. Sorted by
// strength DESC (strongest matches first) then scf_id (stable order).
func (q *Queries) ListAnchorsForRequirementWithEdges(ctx context.Context, frameworkRequirementID pgtype.UUID) ([]ListAnchorsForRequirementWithEdgesRow, error) {
	rows, err := q.db.Query(ctx, listAnchorsForRequirementWithEdges, frameworkRequirementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAnchorsForRequirementWithEdgesRow
	for rows.Next() {
		var i ListAnchorsForRequirementWithEdgesRow
		if err := rows.Scan(
			&i.EdgeID,
			&i.ScfAnchorID,
			&i.RelationshipType,
			&i.Strength,
			&i.SourceAttribution,
			&i.MappingTier,
			&i.Rationale,
			&i.ScfID,
			&i.Family,
			&i.AnchorTitle,
			&i.AnchorDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnchorsForRequirementWithEdgesByFrameworkVersion = `-- name: ListAnchorsForRequirementWithEdgesByFrameworkVersion :many
SELECT
    e.id                AS edge_id,
    e.scf_anchor_id,
    e.relationship_type,
    e.strength,
    e.source_attribution,
    e.mapping_tier,
    e.rationale,
    a.scf_id,
    a.family,
    a.title            AS anchor_title,
    a.description      AS anchor_description
FROM fw_to_scf_edges e
JOIN scf_anchors a ON a.id = e.scf_anchor_id
WHERE e.framework_requirement_id = $1
  AND e.relationship_type <> 'no_relationship'
  AND a.framework_version_id = $2
ORDER BY e.strength DESC, a.scf_id
`

type ListAnchorsForRequirementWithEdgesByFrameworkVersionParams struct {
	FrameworkRequirementID pgtype.UUID `json:"framework_requirement_id"`
	FrameworkVersionID     pgtype.UUID `json:"framework_version_id"`
}

type ListAnchorsForRequirementWithEdgesByFrameworkVersionRow struct {
	EdgeID            pgtype.UUID                `json:"edge_id"`
	ScfAnchorID       pgtype.UUID                `json:"scf_anchor_id"`
	RelationshipType  StrmRelationshipType       `json:"relationship_type"`
	Strength          float64                    `json:"strength"`
	SourceAttribution CrosswalkSourceAttribution `json:"source_attribution"`
	MappingTier       CrosswalkMappingTier       `json:"mapping_tier"`
	Rationale         string                     `json:"rationale"`
	ScfID             string                     `json:"scf_id"`
	Family            string                     `json:"family"`
	AnchorTitle       string                     `json:"anchor_title"`
	AnchorDescription string                     `json:"anchor_description"`
}

// AC-1 + AC-4 (historical pinning arm). Same as
// ListAnchorsForRequirementWithEdges, but additionally filtered by the
// SCF framework_version_id so callers can pin to a specific SCF
// release. When no SCF release is pinned, callers use the unfiltered
// variant above.
func (q *Queries) ListAnchorsForRequirementWithEdgesByFrameworkVersion(ctx context.Context, arg ListAnchorsForRequirementWithEdgesByFrameworkVersionParams) ([]ListAnchorsForRequirementWithEdgesByFrameworkVersionRow, error) {
	rows, err := q.db.Query(ctx, listAnchorsForRequirementWithEdgesByFrameworkVersion, arg.FrameworkRequirementID, arg.FrameworkVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAnchorsForRequirementWithEdgesByFrameworkVersionRow
	for rows.Next() {
		var i ListAnchorsForRequirementWithEdgesByFrameworkVersionRow
		if err := rows.Scan(
			&i.EdgeID,
			&i.ScfAnchorID,
			&i.RelationshipType,
			&i.Strength,
			&i.SourceAttribution,
			&i.MappingTier,
			&i.Rationale,
			&i.ScfID,
			&i.Family,
			&i.AnchorTitle,
			&i.AnchorDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listControlsForAnchors = `-- name: ListControlsForAnchors :many
SELECT
    c.id,
    c.bundle_id,
    c.version,
    c.scf_id,
    c.scf_anchor_id,
    c.title,
    c.description,
    c.control_family,
    c.implementation_type,
    c.owner_role,
    c.lifecycle_state,
    c.applicability_expr,
    c.freshness_class,
    c.created_at
FROM controls c
WHERE c.scf_anchor_id = ANY($1::uuid[])
  AND c.superseded_by IS NULL
ORDER BY c.bundle_id
`

type ListControlsForAnchorsRow struct {
	ID                 pgtype.UUID               `json:"id"`
	BundleID           string                    `json:"bundle_id"`
	Version            int32                     `json:"version"`
	ScfID              *string                   `json:"scf_id"`
	ScfAnchorID        pgtype.UUID               `json:"scf_anchor_id"`
	Title              string                    `json:"title"`
	Description        string                    `json:"description"`
	ControlFamily      string                    `json:"control_family"`
	ImplementationType ControlImplementationType `json:"implementation_type"`
	OwnerRole          string                    `json:"owner_role"`
	LifecycleState     ControlLifecycleState     `json:"lifecycle_state"`
	ApplicabilityExpr  string                    `json:"applicability_expr"`
	FreshnessClass     *string                   `json:"freshness_class"`
	CreatedAt          pgtype.Timestamptz        `json:"created_at"`
}

// AC-1 (controls arm). Given a list of SCF anchor ids, return every
// active control anchored on any of them. Runs inside the tenant GUC so
// RLS filters to the caller's tenant. Supersededs are excluded —
// coverage only counts the currently active control versions.
//
// NO `WHERE tenant_id = ?` clause: invariant 6 — RLS does the tenant
// filtering. Adding such a clause would be a constitutional violation.
func (q *Queries) ListControlsForAnchors(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListControlsForAnchorsRow, error) {
	rows, err := q.db.Query(ctx, listControlsForAnchors, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListControlsForAnchorsRow
	for rows.Next() {
		var i ListControlsForAnchorsRow
		if err := rows.Scan(
			&i.ID,
			&i.BundleID,
			&i.Version,
			&i.ScfID,
			&i.ScfAnchorID,
			&i.Title,
			&i.Description,
			&i.ControlFamily,
			&i.ImplementationType,
			&i.OwnerRole,
			&i.LifecycleState,
			&i.ApplicabilityExpr,
			&i.FreshnessClass,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequirementsForAnchor = `-- name: ListRequirementsForAnchor :many
SELECT
    e.id               AS edge_id,
    e.framework_requirement_id,
    e.relationship_type,
    e.strength,
    e.source_attribution,
    e.mapping_tier,
    e.rationale,
    r.code,
    r.title            AS requirement_title,
    r.body             AS requirement_body,
    fv.id              AS framework_version_id,
    fv.version         AS framework_version,
    fv.status          AS framework_version_status,
    f.slug             AS framework_slug,
    f.name             AS framework_name
FROM fw_to_scf_edges e
JOIN framework_requirements r ON r.id = e.framework_requirement_id
JOIN framework_versions fv    ON fv.id = r.framework_version_id
JOIN frameworks f             ON f.id = fv.framework_id
WHERE e.scf_anchor_id = $1
  AND e.relationship_type <> 'no_relationship'
ORDER BY f.slug, fv.version, r.code
`

type ListRequirementsForAnchorRow struct {
	EdgeID                 pgtype.UUID                `json:"edge_id"`
	FrameworkRequirementID pgtype.UUID                `json:"framework_requirement_id"`
	RelationshipType       StrmRelationshipType       `json:"relationship_type"`
	Strength               float64                    `json:"strength"`
	SourceAttribution      CrosswalkSourceAttribution `json:"source_attribution"`
	MappingTier            CrosswalkMappingTier       `json:"mapping_tier"`
	Rationale              string                     `json:"rationale"`
	Code                   string                     `json:"code"`
	RequirementTitle       string                     `json:"requirement_title"`
	RequirementBody        string                     `json:"requirement_body"`
	FrameworkVersionID     pgtype.UUID                `json:"framework_version_id"`
	FrameworkVersion       string                     `json:"framework_version"`
	FrameworkVersionStatus FrameworkVersionStatus     `json:"framework_version_status"`
	FrameworkSlug          string                     `json:"framework_slug"`
	FrameworkName          string                     `json:"framework_name"`
}

// AC-2. Reverse traversal — given an SCF anchor, return every framework
// requirement it satisfies, joined to framework_versions + frameworks so
// callers see the full natural key (slug + version + code) in one
// round-trip. Sorted by framework slug + version + code for stable
// output. `no_relationship` edges excluded.
func (q *Queries) ListRequirementsForAnchor(ctx context.Context, scfAnchorID pgtype.UUID) ([]ListRequirementsForAnchorRow, error) {
	rows, err := q.db.Query(ctx, listRequirementsForAnchor, scfAnchorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRequirementsForAnchorRow
	for rows.Next() {
		var i ListRequirementsForAnchorRow
		if err := rows.Scan(
			&i.EdgeID,
			&i.FrameworkRequirementID,
			&i.RelationshipType,
			&i.Strength,
			&i.SourceAttribution,
			&i.MappingTier,
			&i.Rationale,
			&i.Code,
			&i.RequirementTitle,
			&i.RequirementBody,
			&i.FrameworkVersionID,
			&i.FrameworkVersion,
			&i.FrameworkVersionStatus,
			&i.FrameworkSlug,
			&i.FrameworkName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequirementsForAnchorByFrameworkVersion = `-- name: ListRequirementsForAnchorByFrameworkVersion :many
SELECT
    e.id               AS edge_id,
    e.framework_requirement_id,
    e.relationship_type,
    e.strength,
    e.source_attribution,
    e.mapping_tier,
    e.rationale,
    r.code,
    r.title            AS requirement_title,
    r.body             AS requirement_body,
    fv.id              AS framework_version_id,
    fv.version         AS framework_version,
    fv.status          AS framework_version_status,
    f.slug             AS framework_slug,
    f.name             AS framework_name
FROM fw_to_scf_edges e
JOIN framework_requirements r ON r.id = e.framework_requirement_id
JOIN framework_versions fv    ON fv.id = r.framework_version_id
JOIN frameworks f             ON f.id = fv.framework_id
WHERE e.scf_anchor_id = $1
  AND e.relationship_type <> 'no_relationship'
  AND r.framework_version_id = $2
ORDER BY f.slug, fv.version, r.code
`

type ListRequirementsForAnchorByFrameworkVersionParams struct {
	ScfAnchorID        pgtype.UUID `json:"scf_anchor_id"`
	FrameworkVersionID pgtype.UUID `json:"framework_version_id"`
}

type ListRequirementsForAnchorByFrameworkVersionRow struct {
	EdgeID                 pgtype.UUID                `json:"edge_id"`
	FrameworkRequirementID pgtype.UUID                `json:"framework_requirement_id"`
	RelationshipType       StrmRelationshipType       `json:"relationship_type"`
	Strength               float64                    `json:"strength"`
	SourceAttribution      CrosswalkSourceAttribution `json:"source_attribution"`
	MappingTier            CrosswalkMappingTier       `json:"mapping_tier"`
	Rationale              string                     `json:"rationale"`
	Code                   string                     `json:"code"`
	RequirementTitle       string                     `json:"requirement_title"`
	RequirementBody        string                     `json:"requirement_body"`
	FrameworkVersionID     pgtype.UUID                `json:"framework_version_id"`
	FrameworkVersion       string                     `json:"framework_version"`
	FrameworkVersionStatus FrameworkVersionStatus     `json:"framework_version_status"`
	FrameworkSlug          string                     `json:"framework_slug"`
	FrameworkName          string                     `json:"framework_name"`
}

// AC-2 + AC-4 (framework_version pinning). Same as
// ListRequirementsForAnchor but filtered to a specific framework
// version id. Used when the caller passes ?framework_version=slug:version.
func (q *Queries) ListRequirementsForAnchorByFrameworkVersion(ctx context.Context, arg ListRequirementsForAnchorByFrameworkVersionParams) ([]ListRequirementsForAnchorByFrameworkVersionRow, error) {
	rows, err := q.db.Query(ctx, listRequirementsForAnchorByFrameworkVersion, arg.ScfAnchorID, arg.FrameworkVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRequirementsForAnchorByFrameworkVersionRow
	for rows.Next() {
		var i ListRequirementsForAnchorByFrameworkVersionRow
		if err := rows.Scan(
			&i.EdgeID,
			&i.FrameworkRequirementID,
			&i.RelationshipType,
			&i.Strength,
			&i.SourceAttribution,
			&i.MappingTier,
			&i.Rationale,
			&i.Code,
			&i.RequirementTitle,
			&i.RequirementBody,
			&i.FrameworkVersionID,
			&i.FrameworkVersion,
			&i.FrameworkVersionStatus,
			&i.FrameworkSlug,
			&i.FrameworkName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
