-- security-atlas — docker-compose self-host first-boot seed (slice 037).
--
-- Runs ONCE, after migrations/bootstrap/01-roles.sql and migrations/sql/*
-- have been applied, via the atlas-bootstrap one-shot container. It seeds
-- the minimum a fresh deployment needs to be usable:
--
--   1. a default tenant row        — slice 144 introduced the `tenants`
--                                    table; slice 210 populates it here so
--                                    `is_bootstrap_tenant=true` resolves
--                                    cleanly for the slice-209 login UX.
--   2. a builtin scope dimension   — `environment`, the canonical first
--                                    dimension. is_builtin = TRUE.
--   3. a default single-cell scope — the solo-operator's whole-org cell.
--   4. a default local user        — email + argon2id password hash, for
--                                    slice 209 local sign-in.
--   5. a user_roles grant          — slice 211. role='admin' in the
--                                    bootstrap tenant so the JWT minted on
--                                    sign-in actually authorizes against
--                                    /v1/* admin gates.
--   6. a super_admins grant        — slice 211. platform-global, mirrors
--                                    the slice-198 OIDC first-install path.
--
-- Idempotent: every INSERT uses ON CONFLICT DO NOTHING so re-running the
-- bootstrap (e.g. `docker compose up` after a restart) is a safe no-op.
--
-- This script connects as atlas_migrate (BYPASSRLS) so it can write rows
-- across the RLS boundary during bootstrap. No application code path ever
-- connects as atlas_migrate.
--
-- The IDs below are well-known constants the bootstrap shell script and
-- docs/getting-started/first-evidence.md both reference. They are NOT
-- secrets — they are deployment-stable identifiers.
--
-- :default_tenant_id, :default_user_email, :default_user_password_hash are
-- passed in via `psql -v` from bootstrap.sh.

\set ON_ERROR_STOP on

BEGIN;

-- ===== 0. Default tenant row (slice 210) =====
--
-- Populates the slice-144 `tenants` row so the slice-210
-- `BootstrapTenantID` primary query resolves on every fresh install
-- going forward. The fallback path in `internal/platform/status.go`
-- (oldest-user's tenant_id) remains for pre-slice-210 installs that
-- did not run this seed step. `is_bootstrap_tenant=true` is the
-- slice-198 column the OIDC first-install path also writes; the
-- `idx_tenants_bootstrap_singleton` partial index serializes concurrent
-- writers (irrelevant here — bootstrap.sh runs once before atlas comes
-- up). `ON CONFLICT (id) DO NOTHING` keeps re-bootstraps no-op.
INSERT INTO tenants (id, name, is_bootstrap_tenant)
VALUES (
    :'default_tenant_id',
    'Default Tenant',
    TRUE
)
ON CONFLICT (id) DO NOTHING;

-- ===== 1 + 2. Builtin scope dimension for the default tenant =====
--
-- `environment` is the canonical builtin first dimension (prod / staging /
-- dev). The solo operator can add more dimensions later via the UI; this
-- one exists so the default scope cell below has a dimension to range over.
INSERT INTO scope_dimensions (id, tenant_id, name, value_type, allowed_values, is_required, is_builtin)
VALUES (
    'a0000000-0000-4000-8000-000000000001',
    :'default_tenant_id',
    'environment',
    'string',
    '["prod", "staging", "dev"]'::jsonb,
    FALSE,
    TRUE
)
ON CONFLICT (tenant_id, name) DO NOTHING;

-- ===== 3. Default single-cell scope =====
--
-- The solo operator's "everything" cell: environment = prod. dimensions_hash
-- is the SHA-256 of the canonical (key-sorted) JSON `{"environment":"prod"}`.
-- Pre-computed here because the UNIQUE constraint is on the hash, not the
-- JSONB (Postgres does not order object keys deterministically — see the
-- scope_cells table comment in migration _003).
INSERT INTO scope_cells (id, tenant_id, label, dimensions, dimensions_hash)
VALUES (
    'b0000000-0000-4000-8000-000000000001',
    :'default_tenant_id',
    'Default (prod)',
    '{"environment": "prod"}'::jsonb,
    encode(digest('{"environment":"prod"}', 'sha256'), 'hex')
)
ON CONFLICT (tenant_id, dimensions_hash) DO NOTHING;

-- ===== 4. Default local user =====
--
-- A local-mode user (idp_issuer / idp_subject left empty = "no IdP
-- backing"). The password hash is argon2id, generated by bootstrap.sh
-- from ATLAS_DEFAULT_USER_PASSWORD and passed in as
-- :default_user_password_hash. The two rows (users + local_credentials)
-- are inserted in the same transaction so they live or die together —
-- the same invariant users.Store.CreateLocal enforces in Go.
INSERT INTO users (id, tenant_id, email, display_name, status)
VALUES (
    'c0000000-0000-4000-8000-000000000001',
    :'default_tenant_id',
    :'default_user_email',
    'Default Administrator',
    'active'
)
ON CONFLICT (tenant_id, email) DO NOTHING;

INSERT INTO local_credentials (user_id, tenant_id, password_hash, algo, params)
VALUES (
    'c0000000-0000-4000-8000-000000000001',
    :'default_tenant_id',
    :'default_user_password_hash',
    'argon2id',
    '{}'::jsonb
)
ON CONFLICT (user_id) DO NOTHING;

-- ===== 5. Default user role grant (slice 211) =====
--
-- Grants the bootstrap user role='admin' in the bootstrap tenant.
-- Without this, the slice-209 email/password sign-in succeeds but the
-- JWT carries empty `atlas:roles`, so every admin/auditor-gated
-- endpoint returns 403 — dashboards render "Could not load this panel
-- · 403 Forbidden" on every authz-gated card.
--
-- Mirrors the slice-198 OIDC first-install path
-- (internal/auth/users/users.go:351). The role enum is locked at the
-- five canvas §9.5 values; 'admin' is the canonical bootstrap role.
-- `granted_by='system:bootstrap_seed'` distinguishes this provenance
-- from the OIDC path's `'system:bootstrap_first_install'` so the
-- audit trail tags which bootstrap shape the operator used.
--
-- Sub-SELECT instead of hardcoded UUID: if a future slice changes the
-- seed user's id, the grant follows. user_roles.user_id is TEXT (not
-- UUID) per the slice 018 schema; the cast is required.
INSERT INTO user_roles (tenant_id, user_id, role, granted_by)
SELECT
    :'default_tenant_id',
    u.id::text,
    'admin',
    'system:bootstrap_seed'
FROM users u
WHERE u.tenant_id = :'default_tenant_id'
  AND u.email = :'default_user_email'
ON CONFLICT (tenant_id, user_id, role) DO NOTHING;

-- ===== 6. Default user super_admin grant (slice 211) =====
--
-- Platform-global super_admin. Mirrors the slice-198 OIDC
-- BootstrapFirstInstallOrUpsert path (users.go:360). Single permitted
-- `granted_via` value per the slice-198 CHECK constraint:
-- 'bootstrap_first_install'. Re-used here because this IS
-- semantically a first-install grant — extending the CHECK to add a
-- 'bootstrap_seed' value would require a separate migration.
--
-- super_admins has no tenant_id column (P0-198-5: super_admin is
-- platform-global, not tenant-scoped). user_id is UUID (no cast).
INSERT INTO super_admins (user_id, granted_via)
SELECT
    u.id,
    'bootstrap_first_install'
FROM users u
WHERE u.tenant_id = :'default_tenant_id'
  AND u.email = :'default_user_email'
ON CONFLICT (user_id) DO NOTHING;

COMMIT;
